CREATE Global Temporary TABLE T_FB_PAYDUE_MAIL_DETAIL_TMP
(
       COMP_CODE            VARCHAR2(20) NULL,
       PAY_DUE_YMD          VARCHAR2(8) NULL,
       VAT_REGISTRATION_NUM VARCHAR2(12) NULL,
       MAIL_SUB_SEQ         NUMBER NULL,
       CASH_BILL_GUBUN      VARCHAR2(1) NULL,
       KEY_VALUE            VARCHAR2(40) NOT NULL,
       PAY_AMT              NUMBER NULL,
       BANK_CODE            VARCHAR2(2) NOT NULL,
       IN_ACCOUNT_NO        VARCHAR2(50) NOT NULL,
       CHECK_NO             VARCHAR2(20) NULL,
       FUTURE_PAY_DUE_YMD   VARCHAR2(8) NULL,
       CONSTRUCTION_SITE_CODE VARCHAR2(20) NULL,
       CONTRUCTION_SITE_NAME VARCHAR2(300) NULL,
       MAIL_SEQ             NUMBER NULL
)
/
CREATE Global Temporary TABLE T_FB_PAYDUE_MAIL_MASTER_TMP (
       MAIL_SEQ             NUMBER NULL,
       COMP_CODE            VARCHAR2(20) NULL,
       PAY_DUE_YMD          VARCHAR2(8) NULL,
       VAT_REGISTRATION_NUM VARCHAR2(12) NULL
)
/
