<%@ page import="com.cj.common.*, com.cj.database.*, com.cj.util.*, com.gauce.*, com.gauce.io.*, java.sql.*" errorPage="../common/Error.jsp" contentType="text/html;charset=euc-kr"%>
<%
/**************************************************************************/
/* 1. 프 로 그 램 id : 
/* 2. 유형(시나리오) : Select Page
/* 3. 기  능  정  의 : 
/* 4. 변  경  이  력 : 한재원 작성(2006-05-03)
/* 5. 관련  프로그램 : 
/* 6. 특  기  사  항 : 
/**************************************************************************/
 
	CITGauceInfo GauceInfo = null;
	
	CITData lrReturnData = null;
	GauceDataSet lrDataset = null;

	String	strSql = "";
	String	strAct = "";
	
	try
	{
		GauceInfo = CITCommon.initServerPage(request, response, session);
		
		CITData lrArgData = new CITData();
		
		strAct = CITCommon.toKOR(request.getParameter("ACT"));
		
		if (strAct.equals("MAIN"))
		{
			String strCOMP_CODE = CITCommon.toKOR(request.getParameter("COMP_CODE"));
			String strCLSE_ACC_ID = CITCommon.toKOR(request.getParameter("CLSE_ACC_ID"));
			
			strSql  = " select		div, \n";
			strSql += " 			p_no, \n";
			strSql += " 		    biz_plan_item_no, \n";
			strSql += " 		    biz_plan_item_name, \n";
			strSql += " 			exec_amt01, \n";
			strSql += " 			plan_amt01,       \n";
			strSql += " 			forecast_amt01, \n";
			strSql += " 			exec_amt02, \n";
			strSql += " 			plan_amt02,       \n";
			strSql += " 			forecast_amt02, \n";
			strSql += " 			exec_amt03, \n";
			strSql += " 			plan_amt03,       \n";
			strSql += " 			forecast_amt03, \n";
			strSql += " 			exec_amt04, \n";
			strSql += " 			plan_amt04,       \n";
			strSql += " 			forecast_amt04, \n";
			strSql += " 			exec_amt05, \n";
			strSql += " 			plan_amt05,       \n";
			strSql += " 			forecast_amt05, \n";
			strSql += " 			exec_amt06, \n";
			strSql += " 			plan_amt06,       \n";
			strSql += " 			forecast_amt06, \n";
			strSql += " 			exec_amt07, \n";
			strSql += " 			plan_amt07,       \n";
			strSql += " 			forecast_amt07, \n";
			strSql += " 			exec_amt08, \n";
			strSql += " 			plan_amt08,       \n";
			strSql += " 			forecast_amt08,       \n";
			strSql += " 			exec_amt09, \n";
			strSql += " 			plan_amt09,       \n";
			strSql += " 			forecast_amt09, \n";
			strSql += " 			exec_amt10, \n";
			strSql += " 			plan_amt10,       \n";
			strSql += " 			forecast_amt10, \n";
			strSql += " 			exec_amt11,   \n";
			strSql += " 			plan_amt11,       \n";
			strSql += " 			forecast_amt11,   \n";
			strSql += " 			exec_amt12, \n";
			strSql += " 			plan_amt12,       \n";
			strSql += " 			forecast_amt12 \n";
			strSql += " from \n";
			strSql += " 	( \n";
			strSql += " 	select 	    div, \n";
			strSql += " 				p_no, \n";
			strSql += " 			    biz_plan_item_no, \n";
			strSql += " 			    biz_plan_item_name, \n";
			strSql += " 				exec_amt01, \n";
			strSql += " 				plan_amt01,       \n";
			strSql += " 				forecast_amt01, \n";
			strSql += " 				exec_amt02, \n";
			strSql += " 				plan_amt02,       \n";
			strSql += " 				forecast_amt02, \n";
			strSql += " 				exec_amt03, \n";
			strSql += " 				plan_amt03,       \n";
			strSql += " 				forecast_amt03, \n";
			strSql += " 				exec_amt04, \n";
			strSql += " 				plan_amt04,       \n";
			strSql += " 				forecast_amt04, \n";
			strSql += " 				exec_amt05, \n";
			strSql += " 				plan_amt05,       \n";
			strSql += " 				forecast_amt05, \n";
			strSql += " 				exec_amt06, \n";
			strSql += " 				plan_amt06,       \n";
			strSql += " 				forecast_amt06, \n";
			strSql += " 				exec_amt07, \n";
			strSql += " 				plan_amt07,       \n";
			strSql += " 				forecast_amt07, \n";
			strSql += " 				exec_amt08, \n";
			strSql += " 				plan_amt08,       \n";
			strSql += " 				forecast_amt08,       \n";
			strSql += " 				exec_amt09, \n";
			strSql += " 				plan_amt09,       \n";
			strSql += " 				forecast_amt09, \n";
			strSql += " 				exec_amt10, \n";
			strSql += " 				plan_amt10,       \n";
			strSql += " 				forecast_amt10, \n";
			strSql += " 				exec_amt11,   \n";
			strSql += " 				plan_amt11,       \n";
			strSql += " 				forecast_amt11,   \n";
			strSql += " 				exec_amt12, \n";
			strSql += " 				plan_amt12,       \n";
			strSql += " 				forecast_amt12 \n";
			strSql += " 		   \n";
			strSql += " 	from \n";
			strSql += " 		( \n";
			strSql += " 		select  '11' div, \n";
			strSql += " 				a.p_no, \n";
			strSql += " 			    a.biz_plan_item_no, \n";
			strSql += " 			    lpad(' ', (level-1) *2 ) || biz_plan_item_name biz_plan_item_name, \n";
			strSql += " 				exec_amt01, \n";
			strSql += " 				plan_amt01,       \n";
			strSql += " 				forecast_amt01, \n";
			strSql += " 				exec_amt02, \n";
			strSql += " 				plan_amt02,       \n";
			strSql += " 				forecast_amt02, \n";
			strSql += " 				exec_amt03, \n";
			strSql += " 				plan_amt03,       \n";
			strSql += " 				forecast_amt03, \n";
			strSql += " 				exec_amt04, \n";
			strSql += " 				plan_amt04,       \n";
			strSql += " 				forecast_amt04, \n";
			strSql += " 				exec_amt05, \n";
			strSql += " 				plan_amt05,       \n";
			strSql += " 				forecast_amt05, \n";
			strSql += " 				exec_amt06, \n";
			strSql += " 				plan_amt06,       \n";
			strSql += " 				forecast_amt06, \n";
			strSql += " 				exec_amt07, \n";
			strSql += " 				plan_amt07,       \n";
			strSql += " 				forecast_amt07, \n";
			strSql += " 				exec_amt08, \n";
			strSql += " 				plan_amt08,       \n";
			strSql += " 				forecast_amt08,       \n";
			strSql += " 				exec_amt09, \n";
			strSql += " 				plan_amt09,       \n";
			strSql += " 				forecast_amt09, \n";
			strSql += " 				exec_amt10, \n";
			strSql += " 				plan_amt10,       \n";
			strSql += " 				forecast_amt10, \n";
			strSql += " 				exec_amt11,   \n";
			strSql += " 				plan_amt11,       \n";
			strSql += " 				forecast_amt11,   \n";
			strSql += " 				exec_amt12, \n";
			strSql += " 				plan_amt12,       \n";
			strSql += " 				forecast_amt12  \n";
			strSql += " 		from \n";
			strSql += " 			( \n";
			strSql += " 			select  a.p_no, \n";
			strSql += " 					a.biz_plan_item_no, \n";
			strSql += " 					sum(exec_amt01)      exec_amt01,     \n";
			strSql += " 					sum(plan_amt01)      plan_amt01,      \n";
			strSql += " 					sum(forecast_amt01)  forecast_amt01, \n";
			strSql += " 					sum(exec_amt02)      exec_amt02,     \n";
			strSql += " 					sum(plan_amt02)      plan_amt02,      \n";
			strSql += " 					sum(forecast_amt02)  forecast_amt02, \n";
			strSql += " 					sum(exec_amt03)      exec_amt03,     \n";
			strSql += " 					sum(plan_amt03)      plan_amt03,      \n";
			strSql += " 					sum(forecast_amt03)  forecast_amt03, \n";
			strSql += " 					sum(exec_amt04)      exec_amt04,     \n";
			strSql += " 					sum(plan_amt04)      plan_amt04,      \n";
			strSql += " 					sum(forecast_amt04)  forecast_amt04, \n";
			strSql += " 					sum(exec_amt05)      exec_amt05,     \n";
			strSql += " 					sum(plan_amt05)      plan_amt05,      \n";
			strSql += " 					sum(forecast_amt05)  forecast_amt05, \n";
			strSql += " 					sum(exec_amt06)      exec_amt06,     \n";
			strSql += " 					sum(plan_amt06)      plan_amt06,      \n";
			strSql += " 					sum(forecast_amt06)  forecast_amt06, \n";
			strSql += " 					sum(exec_amt07)      exec_amt07,     \n";
			strSql += " 					sum(plan_amt07)      plan_amt07,      \n";
			strSql += " 					sum(forecast_amt07)  forecast_amt07, \n";
			strSql += " 					sum(exec_amt08)      exec_amt08,     \n";
			strSql += " 					sum(plan_amt08)      plan_amt08,      \n";
			strSql += " 					sum(forecast_amt08)  forecast_amt08, \n";
			strSql += " 					sum(exec_amt09)      exec_amt09,     \n";
			strSql += " 					sum(plan_amt09)      plan_amt09,      \n";
			strSql += " 					sum(forecast_amt09)  forecast_amt09, \n";
			strSql += " 					sum(exec_amt10)      exec_amt10,     \n";
			strSql += " 					sum(plan_amt10)      plan_amt10,      \n";
			strSql += " 					sum(forecast_amt10)  forecast_amt10, \n";
			strSql += " 					sum(exec_amt11)      exec_amt11,      \n";
			strSql += " 					sum(plan_amt11)      plan_amt11,      \n";
			strSql += " 					sum(forecast_amt11)  forecast_amt11,  \n";
			strSql += " 					sum(exec_amt12)      exec_amt12,      \n";
			strSql += " 					sum(plan_amt12)      plan_amt12,      \n";
			strSql += " 					sum(forecast_amt12)  forecast_amt12           \n";
			strSql += " 			from 	t_pl_item a, \n";
			strSql += " 				    (   \n";
			strSql += " 				    select  \n";
			strSql += " 							 b2.biz_plan_item_no, \n";
			strSql += " 							 decode(nvl(exec_amt01,0), 0, 0, round(exec_amt01/1000000,0)) exec_amt01, \n";
			strSql += " 							 decode(nvl(plan_amt01,0), 0, 0, round(plan_amt01/1000000,0)) plan_amt01,  \n";
			strSql += " 							 decode(nvl(forecast_amt01,0), 0, 0, round(forecast_amt01/1000000,0)) forecast_amt01, \n";
			strSql += " 							 decode(nvl(exec_amt02,0), 0, 0, round(exec_amt02/1000000,0)) exec_amt02, \n";
			strSql += " 							 decode(nvl(plan_amt02,0), 0, 0, round(plan_amt02/1000000,0)) plan_amt02,  \n";
			strSql += " 							 decode(nvl(forecast_amt02,0), 0, 0, round(forecast_amt02/1000000,0)) forecast_amt02, \n";
			strSql += " 							 decode(nvl(exec_amt03,0), 0, 0, round(exec_amt03/1000000,0)) exec_amt03, \n";
			strSql += " 							 decode(nvl(plan_amt03,0), 0, 0, round(plan_amt03/1000000,0)) plan_amt03,  \n";
			strSql += " 							 decode(nvl(forecast_amt03,0), 0, 0, round(forecast_amt03/1000000,0)) forecast_amt03, \n";
			strSql += " 							 decode(nvl(exec_amt04,0), 0, 0, round(exec_amt04/1000000,0)) exec_amt04, \n";
			strSql += " 							 decode(nvl(plan_amt04,0), 0, 0, round(plan_amt04/1000000,0)) plan_amt04,  \n";
			strSql += " 							 decode(nvl(forecast_amt04,0), 0, 0, round(forecast_amt04/1000000,0)) forecast_amt04, \n";
			strSql += " 							 decode(nvl(exec_amt05,0), 0, 0, round(exec_amt05/1000000,0)) exec_amt05, \n";
			strSql += " 							 decode(nvl(plan_amt05,0), 0, 0, round(plan_amt05/1000000,0)) plan_amt05,  \n";
			strSql += " 							 decode(nvl(forecast_amt05,0), 0, 0, round(forecast_amt05/1000000,0)) forecast_amt05, \n";
			strSql += " 							 decode(nvl(exec_amt06,0), 0, 0, round(exec_amt06/1000000,0)) exec_amt06, \n";
			strSql += " 							 decode(nvl(plan_amt06,0), 0, 0, round(plan_amt06/1000000,0)) plan_amt06,  \n";
			strSql += " 							 decode(nvl(forecast_amt06,0), 0, 0, round(forecast_amt06/1000000,0)) forecast_amt06, \n";
			strSql += " 							 decode(nvl(exec_amt07,0), 0, 0, round(exec_amt07/1000000,0)) exec_amt07, \n";
			strSql += " 							 decode(nvl(plan_amt07,0), 0, 0, round(plan_amt07/1000000,0)) plan_amt07,  \n";
			strSql += " 							 decode(nvl(forecast_amt07,0), 0, 0, round(forecast_amt07/1000000,0)) forecast_amt07, \n";
			strSql += " 							 decode(nvl(exec_amt08,0), 0, 0, round(exec_amt08/1000000,0)) exec_amt08, \n";
			strSql += " 							 decode(nvl(plan_amt08,0), 0, 0, round(plan_amt08/1000000,0)) plan_amt08,  \n";
			strSql += " 							 decode(nvl(forecast_amt08,0), 0, 0, round(forecast_amt08/1000000,0)) forecast_amt08, \n";
			strSql += " 							 decode(nvl(exec_amt09,0), 0, 0, round(exec_amt09/1000000,0)) exec_amt09, \n";
			strSql += " 							 decode(nvl(plan_amt09,0), 0, 0, round(plan_amt09/1000000,0)) plan_amt09,  \n";
			strSql += " 							 decode(nvl(forecast_amt09,0), 0, 0, round(forecast_amt09/1000000,0)) forecast_amt09,					  \n";
			strSql += " 							 decode(nvl(exec_amt10,0), 0, 0, round(exec_amt10/1000000,0)) exec_amt10, \n";
			strSql += " 							 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10,  \n";
			strSql += " 							 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 							 decode(nvl(exec_amt11,0), 0, 0, round(exec_amt11/1000000,0)) exec_amt11, \n";
			strSql += " 							 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11,  \n";
			strSql += " 							 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 							 decode(nvl(exec_amt12,0), 0, 0, round(exec_amt12/1000000,0)) exec_amt12, \n";
			strSql += " 							 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 							 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12 \n";
			strSql += " 				    from  \n";
			strSql += " 						  ( \n";
			strSql += " 						  select comp_code, clse_acc_id+1  clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 						  		 exec_amt01, \n";
			strSql += " 								 exec_amt02, \n";
			strSql += " 								 exec_amt03,  \n";
			strSql += " 								 exec_amt04, \n";
			strSql += " 								 exec_amt05, \n";
			strSql += " 								 exec_amt06,  \n";
			strSql += " 							  	 exec_amt07, \n";
			strSql += " 								 exec_amt08, \n";
			strSql += " 								 exec_amt09,  \n";
			strSql += " 								 exec_amt10, \n";
			strSql += " 								 exec_amt11, \n";
			strSql += " 								 exec_amt12 \n";
			strSql += " 						  from \n";
			strSql += " 						  	  ( \n";
			strSql += " 							  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 							  		 sum(exec_amt01) exec_amt01, \n";
			strSql += " 									 sum(exec_amt02) exec_amt02, \n";
			strSql += " 									 sum(exec_amt03) exec_amt03,  \n";
			strSql += " 									 sum(exec_amt04) exec_amt04, \n";
			strSql += " 									 sum(exec_amt05) exec_amt05, \n";
			strSql += " 									 sum(exec_amt06) exec_amt06,  \n";
			strSql += " 							  		 sum(exec_amt07) exec_amt07, \n";
			strSql += " 									 sum(exec_amt08) exec_amt08, \n";
			strSql += " 									 sum(exec_amt09) exec_amt09,  \n";
			strSql += " 									 sum(exec_amt10) exec_amt10, \n";
			strSql += " 									 sum(exec_amt11) exec_amt11, \n";
			strSql += " 									 sum(exec_amt12) exec_amt12  \n";
			strSql += " 							  from \n";
			strSql += " 							  	  ( \n";
			strSql += " 								  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'01', sum(exec_amt), '') 	   exec_amt01,  \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'02', sum(exec_amt), '') 	   exec_amt02, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'03', sum(exec_amt), '') 	   exec_amt03, \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'04', sum(exec_amt), '') 	   exec_amt04,  \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'05', sum(exec_amt), '') 	   exec_amt05, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'06', sum(exec_amt), '') 	   exec_amt06, \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'07', sum(exec_amt), '') 	   exec_amt07,  \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'08', sum(exec_amt), '') 	   exec_amt08, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'09', sum(exec_amt), '') 	   exec_amt09, \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'10', sum(exec_amt), '') 	   exec_amt10,  \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'11', sum(exec_amt), '') 	   exec_amt11, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'12', sum(exec_amt), '') 	   exec_amt12 \n";
			strSql += " 								  from   t_pl_comp_plan_exec \n";
			strSql += " 								  where  comp_code =  ?  \n";
			strSql += " 								  and	 clse_acc_id =  ?  - 1 \n";
			strSql += " 								  and    substr(work_ym, 5,6) in ('01','02','03','04','05','06','07','08','09','10','11','12') \n";
			strSql += " 								  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 								  		   substr(work_ym, 5,6) \n";
			strSql += " 								  ) \n";
			strSql += " 							  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 							  ) \n";
			strSql += " 						   ) b1, \n";
			strSql += " 						   (select   comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 							  		 sum(plan_amt01) plan_amt01, \n";
			strSql += " 									 sum(forecast_amt01) forecast_amt01, \n";
			strSql += " 									 sum(plan_amt02) plan_amt02, \n";
			strSql += " 									 sum(forecast_amt02) forecast_amt02, \n";
			strSql += " 									 sum(plan_amt03) plan_amt03,  \n";
			strSql += " 									 sum(forecast_amt03) forecast_amt03, \n";
			strSql += " 									 sum(plan_amt04) plan_amt04, \n";
			strSql += " 									 sum(forecast_amt04) forecast_amt04, \n";
			strSql += " 									 sum(plan_amt05) plan_amt05, \n";
			strSql += " 									 sum(forecast_amt05) forecast_amt05, \n";
			strSql += " 									 sum(plan_amt06) plan_amt06,  \n";
			strSql += " 									 sum(forecast_amt06) forecast_amt06,  \n";
			strSql += " 							  		 sum(plan_amt07) plan_amt07, \n";
			strSql += " 									 sum(forecast_amt07) forecast_amt07, \n";
			strSql += " 									 sum(plan_amt08) plan_amt08, \n";
			strSql += " 									 sum(forecast_amt08) forecast_amt08, \n";
			strSql += " 									 sum(plan_amt09) plan_amt09,  \n";
			strSql += " 									 sum(forecast_amt09) forecast_amt09, \n";
			strSql += " 									 sum(plan_amt10) plan_amt10, \n";
			strSql += " 									 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 									 sum(plan_amt11) plan_amt11, \n";
			strSql += " 									 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 									 sum(plan_amt12) plan_amt12,  \n";
			strSql += " 									 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 						    from \n";
			strSql += " 							  	  ( \n";
			strSql += " 								  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'01', sum(plan_amt), '') 	   plan_amt01,  \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'01', sum(forecast_amt), '') forecast_amt01, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'02', sum(plan_amt), '') 	   plan_amt02, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'02', sum(forecast_amt), '') forecast_amt02, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'03', sum(plan_amt), '') 	   plan_amt03, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'03', sum(forecast_amt), '') forecast_amt03, \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'04', sum(plan_amt), '') 	   plan_amt04,  \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'04', sum(forecast_amt), '') forecast_amt04, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'05', sum(plan_amt), '') 	   plan_amt05, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'05', sum(forecast_amt), '') forecast_amt05, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'06', sum(plan_amt), '') 	   plan_amt06, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'06', sum(forecast_amt), '') forecast_amt06, \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'07', sum(plan_amt), '') 	   plan_amt07,  \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'07', sum(forecast_amt), '') forecast_amt07, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'08', sum(plan_amt), '') 	   plan_amt08, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'08', sum(forecast_amt), '') forecast_amt08, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'09', sum(plan_amt), '') 	   plan_amt09, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'09', sum(forecast_amt), '') forecast_amt09, \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10,  \n";
			strSql += " 								  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 										 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 								  from   t_pl_comp_plan_exec \n";
			strSql += " 								  where  comp_code =  ?  \n";
			strSql += " 								  and	 clse_acc_id =  ?  \n";
			strSql += " 								  and    substr(work_ym, 5,6) in ('01','02','03','04','05','06','07','08','09','10','11','12') \n";
			strSql += " 								  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 								  		   substr(work_ym, 5,6) \n";
			strSql += " 								  ) \n";
			strSql += " 							 group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 						  ) b2 \n";
			strSql += " 				  where   b2.comp_code = b1.comp_code(+) \n";
			strSql += " 				  and	  b2.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 				  and	  b2.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 				  ) b \n";
			strSql += " 			where a.biz_plan_item_no = b.biz_plan_item_no(+) \n";
			strSql += " 			--group by rollup(a.p_no, a.biz_plan_item_no, biz_plan_item_name) \n";
			strSql += " 			group by grouping sets ((a.p_no, \n";
			strSql += " 					 		  	     a.biz_plan_item_no, \n";
			strSql += " 									 biz_plan_item_name), \n";
			strSql += " 									(a.p_no) \n";
			strSql += " 								   ) \n";
			strSql += " 			)	a, \n";
			strSql += " 			t_pl_item b \n";
			strSql += " 		where b.biz_plan_item_no = a.biz_plan_item_no(+)					 \n";
			strSql += " 		start with a.p_no = 3 \n";
			strSql += " 		connect by prior a.biz_plan_item_no = a.p_no \n";
			strSql += " 		order siblings by item_level_seq \n";
			strSql += " 	) \n";
			strSql += " 	 \n";
			strSql += " 	union all \n";
			strSql += " 	 \n";
			strSql += " 	select  '12' div, \n";
			strSql += " 			p_no, \n";
			strSql += " 			-1 biz_plan_item_no, \n";
			strSql += " 			'합계' biz_plan_item_name, \n";
			strSql += " 		    exec_amt01, \n";
			strSql += " 			plan_amt01,       \n";
			strSql += " 			forecast_amt01, \n";
			strSql += " 			exec_amt02, \n";
			strSql += " 			plan_amt02,       \n";
			strSql += " 			forecast_amt02, \n";
			strSql += " 			exec_amt03, \n";
			strSql += " 			plan_amt03,       \n";
			strSql += " 			forecast_amt03, \n";
			strSql += " 			exec_amt04, \n";
			strSql += " 			plan_amt04,       \n";
			strSql += " 			forecast_amt04, \n";
			strSql += " 			exec_amt05, \n";
			strSql += " 			plan_amt05,       \n";
			strSql += " 			forecast_amt05, \n";
			strSql += " 			exec_amt06, \n";
			strSql += " 			plan_amt06,       \n";
			strSql += " 			forecast_amt06, \n";
			strSql += " 			exec_amt07, \n";
			strSql += " 			plan_amt07,       \n";
			strSql += " 			forecast_amt07, \n";
			strSql += " 			exec_amt08, \n";
			strSql += " 			plan_amt08,       \n";
			strSql += " 			forecast_amt08,       \n";
			strSql += " 			exec_amt09, \n";
			strSql += " 			plan_amt09,       \n";
			strSql += " 			forecast_amt09, \n";
			strSql += " 			exec_amt10, \n";
			strSql += " 			plan_amt10,       \n";
			strSql += " 			forecast_amt10, \n";
			strSql += " 			exec_amt11,   \n";
			strSql += " 			plan_amt11,       \n";
			strSql += " 			forecast_amt11,   \n";
			strSql += " 			exec_amt12, \n";
			strSql += " 			plan_amt12,       \n";
			strSql += " 			forecast_amt12  \n";
			strSql += " 	from \n";
			strSql += " 		( \n";
			strSql += " 		select 	    \n";
			strSql += " 					p_no, \n";
			strSql += " 					sum(exec_amt01) exec_amt01, \n";
			strSql += " 					sum(plan_amt01) plan_amt01,       \n";
			strSql += " 					sum(forecast_amt01) forecast_amt01, \n";
			strSql += " 					sum(exec_amt02) exec_amt02, \n";
			strSql += " 					sum(plan_amt02) plan_amt02,       \n";
			strSql += " 					sum(forecast_amt02) forecast_amt02, \n";
			strSql += " 					sum(exec_amt03) exec_amt03, \n";
			strSql += " 					sum(plan_amt03) plan_amt03,       \n";
			strSql += " 					sum(forecast_amt03) forecast_amt03, \n";
			strSql += " 					sum(exec_amt04) exec_amt04, \n";
			strSql += " 					sum(plan_amt04) plan_amt04,       \n";
			strSql += " 					sum(forecast_amt04) forecast_amt04, \n";
			strSql += " 					sum(exec_amt05) exec_amt05, \n";
			strSql += " 					sum(plan_amt05) plan_amt05,       \n";
			strSql += " 					sum(forecast_amt05) forecast_amt05, \n";
			strSql += " 					sum(exec_amt06) exec_amt06, \n";
			strSql += " 					sum(plan_amt06) plan_amt06,       \n";
			strSql += " 					sum(forecast_amt06) forecast_amt06, \n";
			strSql += " 					sum(exec_amt07) exec_amt07, \n";
			strSql += " 					sum(plan_amt07) plan_amt07,       \n";
			strSql += " 					sum(forecast_amt07) forecast_amt07, \n";
			strSql += " 					sum(exec_amt08) exec_amt08, \n";
			strSql += " 					sum(plan_amt08) plan_amt08,       \n";
			strSql += " 					sum(forecast_amt08) forecast_amt08,       \n";
			strSql += " 					sum(exec_amt09) exec_amt09, \n";
			strSql += " 					sum(plan_amt09) plan_amt09,       \n";
			strSql += " 					sum(forecast_amt09) forecast_amt09, \n";
			strSql += " 					sum(exec_amt10) exec_amt10, \n";
			strSql += " 					sum(plan_amt10) plan_amt10,       \n";
			strSql += " 					sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 					sum(exec_amt11) exec_amt11,   \n";
			strSql += " 					sum(plan_amt11) plan_amt11,       \n";
			strSql += " 					sum(forecast_amt11) forecast_amt11,   \n";
			strSql += " 					sum(exec_amt12) exec_amt12, \n";
			strSql += " 					sum(plan_amt12) plan_amt12,       \n";
			strSql += " 					sum(forecast_amt12) forecast_amt12  \n";
			strSql += " 			   \n";
			strSql += " 		from \n";
			strSql += " 			( \n";
			strSql += " 			select  '11' div, \n";
			strSql += " 					a.p_no, \n";
			strSql += " 				    a.biz_plan_item_no, \n";
			strSql += " 				    lpad(' ', (level-1) *2 ) || biz_plan_item_name biz_plan_item_name, \n";
			strSql += " 					exec_amt01, \n";
			strSql += " 					plan_amt01,       \n";
			strSql += " 					forecast_amt01, \n";
			strSql += " 					exec_amt02, \n";
			strSql += " 					plan_amt02,       \n";
			strSql += " 					forecast_amt02, \n";
			strSql += " 					exec_amt03, \n";
			strSql += " 					plan_amt03,       \n";
			strSql += " 					forecast_amt03, \n";
			strSql += " 					exec_amt04, \n";
			strSql += " 					plan_amt04,       \n";
			strSql += " 					forecast_amt04, \n";
			strSql += " 					exec_amt05, \n";
			strSql += " 					plan_amt05,       \n";
			strSql += " 					forecast_amt05, \n";
			strSql += " 					exec_amt06, \n";
			strSql += " 					plan_amt06,       \n";
			strSql += " 					forecast_amt06, \n";
			strSql += " 					exec_amt07, \n";
			strSql += " 					plan_amt07,       \n";
			strSql += " 					forecast_amt07, \n";
			strSql += " 					exec_amt08, \n";
			strSql += " 					plan_amt08,       \n";
			strSql += " 					forecast_amt08,       \n";
			strSql += " 					exec_amt09, \n";
			strSql += " 					plan_amt09,       \n";
			strSql += " 					forecast_amt09, \n";
			strSql += " 					exec_amt10, \n";
			strSql += " 					plan_amt10,       \n";
			strSql += " 					forecast_amt10, \n";
			strSql += " 					exec_amt11,   \n";
			strSql += " 					plan_amt11,       \n";
			strSql += " 					forecast_amt11,   \n";
			strSql += " 					exec_amt12, \n";
			strSql += " 					plan_amt12,       \n";
			strSql += " 					forecast_amt12  \n";
			strSql += " 			from \n";
			strSql += " 				( \n";
			strSql += " 				select  a.p_no, \n";
			strSql += " 						a.biz_plan_item_no, \n";
			strSql += " 						sum(exec_amt01)      exec_amt01,     \n";
			strSql += " 						sum(plan_amt01)      plan_amt01,      \n";
			strSql += " 						sum(forecast_amt01)  forecast_amt01, \n";
			strSql += " 						sum(exec_amt02)      exec_amt02,     \n";
			strSql += " 						sum(plan_amt02)      plan_amt02,      \n";
			strSql += " 						sum(forecast_amt02)  forecast_amt02, \n";
			strSql += " 						sum(exec_amt03)      exec_amt03,     \n";
			strSql += " 						sum(plan_amt03)      plan_amt03,      \n";
			strSql += " 						sum(forecast_amt03)  forecast_amt03, \n";
			strSql += " 						sum(exec_amt04)      exec_amt04,     \n";
			strSql += " 						sum(plan_amt04)      plan_amt04,      \n";
			strSql += " 						sum(forecast_amt04)  forecast_amt04, \n";
			strSql += " 						sum(exec_amt05)      exec_amt05,     \n";
			strSql += " 						sum(plan_amt05)      plan_amt05,      \n";
			strSql += " 						sum(forecast_amt05)  forecast_amt05, \n";
			strSql += " 						sum(exec_amt06)      exec_amt06,     \n";
			strSql += " 						sum(plan_amt06)      plan_amt06,      \n";
			strSql += " 						sum(forecast_amt06)  forecast_amt06, \n";
			strSql += " 						sum(exec_amt07)      exec_amt07,     \n";
			strSql += " 						sum(plan_amt07)      plan_amt07,      \n";
			strSql += " 						sum(forecast_amt07)  forecast_amt07, \n";
			strSql += " 						sum(exec_amt08)      exec_amt08,     \n";
			strSql += " 						sum(plan_amt08)      plan_amt08,      \n";
			strSql += " 						sum(forecast_amt08)  forecast_amt08, \n";
			strSql += " 						sum(exec_amt09)      exec_amt09,     \n";
			strSql += " 						sum(plan_amt09)      plan_amt09,      \n";
			strSql += " 						sum(forecast_amt09)  forecast_amt09, \n";
			strSql += " 						sum(exec_amt10)      exec_amt10,     \n";
			strSql += " 						sum(plan_amt10)      plan_amt10,      \n";
			strSql += " 						sum(forecast_amt10)  forecast_amt10, \n";
			strSql += " 						sum(exec_amt11)      exec_amt11,      \n";
			strSql += " 						sum(plan_amt11)      plan_amt11,      \n";
			strSql += " 						sum(forecast_amt11)  forecast_amt11,  \n";
			strSql += " 						sum(exec_amt12)      exec_amt12,      \n";
			strSql += " 						sum(plan_amt12)      plan_amt12,      \n";
			strSql += " 						sum(forecast_amt12)  forecast_amt12           \n";
			strSql += " 				from 	t_pl_item a, \n";
			strSql += " 					    (   \n";
			strSql += " 					    select  \n";
			strSql += " 								 b2.biz_plan_item_no, \n";
			strSql += " 								 decode(nvl(exec_amt01,0), 0, 0, round(exec_amt01/1000000,0)) exec_amt01, \n";
			strSql += " 								 decode(nvl(plan_amt01,0), 0, 0, round(plan_amt01/1000000,0)) plan_amt01,  \n";
			strSql += " 								 decode(nvl(forecast_amt01,0), 0, 0, round(forecast_amt01/1000000,0)) forecast_amt01, \n";
			strSql += " 								 decode(nvl(exec_amt02,0), 0, 0, round(exec_amt02/1000000,0)) exec_amt02, \n";
			strSql += " 								 decode(nvl(plan_amt02,0), 0, 0, round(plan_amt02/1000000,0)) plan_amt02,  \n";
			strSql += " 								 decode(nvl(forecast_amt02,0), 0, 0, round(forecast_amt02/1000000,0)) forecast_amt02, \n";
			strSql += " 								 decode(nvl(exec_amt03,0), 0, 0, round(exec_amt03/1000000,0)) exec_amt03, \n";
			strSql += " 								 decode(nvl(plan_amt03,0), 0, 0, round(plan_amt03/1000000,0)) plan_amt03,  \n";
			strSql += " 								 decode(nvl(forecast_amt03,0), 0, 0, round(forecast_amt03/1000000,0)) forecast_amt03, \n";
			strSql += " 								 decode(nvl(exec_amt04,0), 0, 0, round(exec_amt04/1000000,0)) exec_amt04, \n";
			strSql += " 								 decode(nvl(plan_amt04,0), 0, 0, round(plan_amt04/1000000,0)) plan_amt04,  \n";
			strSql += " 								 decode(nvl(forecast_amt04,0), 0, 0, round(forecast_amt04/1000000,0)) forecast_amt04, \n";
			strSql += " 								 decode(nvl(exec_amt05,0), 0, 0, round(exec_amt05/1000000,0)) exec_amt05, \n";
			strSql += " 								 decode(nvl(plan_amt05,0), 0, 0, round(plan_amt05/1000000,0)) plan_amt05,  \n";
			strSql += " 								 decode(nvl(forecast_amt05,0), 0, 0, round(forecast_amt05/1000000,0)) forecast_amt05, \n";
			strSql += " 								 decode(nvl(exec_amt06,0), 0, 0, round(exec_amt06/1000000,0)) exec_amt06, \n";
			strSql += " 								 decode(nvl(plan_amt06,0), 0, 0, round(plan_amt06/1000000,0)) plan_amt06,  \n";
			strSql += " 								 decode(nvl(forecast_amt06,0), 0, 0, round(forecast_amt06/1000000,0)) forecast_amt06, \n";
			strSql += " 								 decode(nvl(exec_amt07,0), 0, 0, round(exec_amt07/1000000,0)) exec_amt07, \n";
			strSql += " 								 decode(nvl(plan_amt07,0), 0, 0, round(plan_amt07/1000000,0)) plan_amt07,  \n";
			strSql += " 								 decode(nvl(forecast_amt07,0), 0, 0, round(forecast_amt07/1000000,0)) forecast_amt07, \n";
			strSql += " 								 decode(nvl(exec_amt08,0), 0, 0, round(exec_amt08/1000000,0)) exec_amt08, \n";
			strSql += " 								 decode(nvl(plan_amt08,0), 0, 0, round(plan_amt08/1000000,0)) plan_amt08,  \n";
			strSql += " 								 decode(nvl(forecast_amt08,0), 0, 0, round(forecast_amt08/1000000,0)) forecast_amt08, \n";
			strSql += " 								 decode(nvl(exec_amt09,0), 0, 0, round(exec_amt09/1000000,0)) exec_amt09, \n";
			strSql += " 								 decode(nvl(plan_amt09,0), 0, 0, round(plan_amt09/1000000,0)) plan_amt09,  \n";
			strSql += " 								 decode(nvl(forecast_amt09,0), 0, 0, round(forecast_amt09/1000000,0)) forecast_amt09,					  \n";
			strSql += " 								 decode(nvl(exec_amt10,0), 0, 0, round(exec_amt10/1000000,0)) exec_amt10, \n";
			strSql += " 								 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10,  \n";
			strSql += " 								 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 								 decode(nvl(exec_amt11,0), 0, 0, round(exec_amt11/1000000,0)) exec_amt11, \n";
			strSql += " 								 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11,  \n";
			strSql += " 								 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 								 decode(nvl(exec_amt12,0), 0, 0, round(exec_amt12/1000000,0)) exec_amt12, \n";
			strSql += " 								 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 								 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12 \n";
			strSql += " 					    from  \n";
			strSql += " 							  ( \n";
			strSql += " 							  select comp_code, clse_acc_id+1  clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 							  		 exec_amt01, \n";
			strSql += " 									 exec_amt02, \n";
			strSql += " 									 exec_amt03,  \n";
			strSql += " 									 exec_amt04, \n";
			strSql += " 									 exec_amt05, \n";
			strSql += " 									 exec_amt06,  \n";
			strSql += " 								  	 exec_amt07, \n";
			strSql += " 									 exec_amt08, \n";
			strSql += " 									 exec_amt09,  \n";
			strSql += " 									 exec_amt10, \n";
			strSql += " 									 exec_amt11, \n";
			strSql += " 									 exec_amt12 \n";
			strSql += " 							  from \n";
			strSql += " 							  	  ( \n";
			strSql += " 								  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 								  		 sum(exec_amt01) exec_amt01, \n";
			strSql += " 										 sum(exec_amt02) exec_amt02, \n";
			strSql += " 										 sum(exec_amt03) exec_amt03,  \n";
			strSql += " 										 sum(exec_amt04) exec_amt04, \n";
			strSql += " 										 sum(exec_amt05) exec_amt05, \n";
			strSql += " 										 sum(exec_amt06) exec_amt06,  \n";
			strSql += " 								  		 sum(exec_amt07) exec_amt07, \n";
			strSql += " 										 sum(exec_amt08) exec_amt08, \n";
			strSql += " 										 sum(exec_amt09) exec_amt09,  \n";
			strSql += " 										 sum(exec_amt10) exec_amt10, \n";
			strSql += " 										 sum(exec_amt11) exec_amt11, \n";
			strSql += " 										 sum(exec_amt12) exec_amt12  \n";
			strSql += " 								  from \n";
			strSql += " 								  	  ( \n";
			strSql += " 									  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'01', sum(exec_amt), '') 	   exec_amt01,  \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'02', sum(exec_amt), '') 	   exec_amt02, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'03', sum(exec_amt), '') 	   exec_amt03, \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'04', sum(exec_amt), '') 	   exec_amt04,  \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'05', sum(exec_amt), '') 	   exec_amt05, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'06', sum(exec_amt), '') 	   exec_amt06, \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'07', sum(exec_amt), '') 	   exec_amt07,  \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'08', sum(exec_amt), '') 	   exec_amt08, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'09', sum(exec_amt), '') 	   exec_amt09, \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'10', sum(exec_amt), '') 	   exec_amt10,  \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'11', sum(exec_amt), '') 	   exec_amt11, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'12', sum(exec_amt), '') 	   exec_amt12 \n";
			strSql += " 									  from   t_pl_comp_plan_exec \n";
			strSql += " 									  where  comp_code =  ?  \n";
			strSql += " 									  and	 clse_acc_id =  ?  - 1 \n";
			strSql += " 									  and    substr(work_ym, 5,6) in ('01','02','03','04','05','06','07','08','09','10','11','12') \n";
			strSql += " 									  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 									  		   substr(work_ym, 5,6) \n";
			strSql += " 									  ) \n";
			strSql += " 								  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 								  ) \n";
			strSql += " 							   ) b1, \n";
			strSql += " 							   (select   comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 								  		 sum(plan_amt01) plan_amt01, \n";
			strSql += " 										 sum(forecast_amt01) forecast_amt01, \n";
			strSql += " 										 sum(plan_amt02) plan_amt02, \n";
			strSql += " 										 sum(forecast_amt02) forecast_amt02, \n";
			strSql += " 										 sum(plan_amt03) plan_amt03,  \n";
			strSql += " 										 sum(forecast_amt03) forecast_amt03, \n";
			strSql += " 										 sum(plan_amt04) plan_amt04, \n";
			strSql += " 										 sum(forecast_amt04) forecast_amt04, \n";
			strSql += " 										 sum(plan_amt05) plan_amt05, \n";
			strSql += " 										 sum(forecast_amt05) forecast_amt05, \n";
			strSql += " 										 sum(plan_amt06) plan_amt06,  \n";
			strSql += " 										 sum(forecast_amt06) forecast_amt06,  \n";
			strSql += " 								  		 sum(plan_amt07) plan_amt07, \n";
			strSql += " 										 sum(forecast_amt07) forecast_amt07, \n";
			strSql += " 										 sum(plan_amt08) plan_amt08, \n";
			strSql += " 										 sum(forecast_amt08) forecast_amt08, \n";
			strSql += " 										 sum(plan_amt09) plan_amt09,  \n";
			strSql += " 										 sum(forecast_amt09) forecast_amt09, \n";
			strSql += " 										 sum(plan_amt10) plan_amt10, \n";
			strSql += " 										 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 										 sum(plan_amt11) plan_amt11, \n";
			strSql += " 										 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 										 sum(plan_amt12) plan_amt12,  \n";
			strSql += " 										 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 							    from \n";
			strSql += " 								  	  ( \n";
			strSql += " 									  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'01', sum(plan_amt), '') 	   plan_amt01,  \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'01', sum(forecast_amt), '') forecast_amt01, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'02', sum(plan_amt), '') 	   plan_amt02, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'02', sum(forecast_amt), '') forecast_amt02, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'03', sum(plan_amt), '') 	   plan_amt03, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'03', sum(forecast_amt), '') forecast_amt03, \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'04', sum(plan_amt), '') 	   plan_amt04,  \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'04', sum(forecast_amt), '') forecast_amt04, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'05', sum(plan_amt), '') 	   plan_amt05, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'05', sum(forecast_amt), '') forecast_amt05, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'06', sum(plan_amt), '') 	   plan_amt06, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'06', sum(forecast_amt), '') forecast_amt06, \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'07', sum(plan_amt), '') 	   plan_amt07,  \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'07', sum(forecast_amt), '') forecast_amt07, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'08', sum(plan_amt), '') 	   plan_amt08, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'08', sum(forecast_amt), '') forecast_amt08, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'09', sum(plan_amt), '') 	   plan_amt09, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'09', sum(forecast_amt), '') forecast_amt09, \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10,  \n";
			strSql += " 									  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 											 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 									  from   t_pl_comp_plan_exec \n";
			strSql += " 									  where  comp_code =  ?  \n";
			strSql += " 									  and	 clse_acc_id =  ?  \n";
			strSql += " 									  and    substr(work_ym, 5,6) in ('01','02','03','04','05','06','07','08','09','10','11','12') \n";
			strSql += " 									  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 									  		   substr(work_ym, 5,6) \n";
			strSql += " 									  ) \n";
			strSql += " 								 group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 							  ) b2 \n";
			strSql += " 					  where   b2.comp_code = b1.comp_code(+) \n";
			strSql += " 					  and	  b2.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 					  and	  b2.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 					  ) b \n";
			strSql += " 				where a.biz_plan_item_no = b.biz_plan_item_no(+) \n";
			strSql += " 				--group by rollup(a.p_no, a.biz_plan_item_no, biz_plan_item_name) \n";
			strSql += " 				group by grouping sets ((a.p_no, \n";
			strSql += " 						 		  	     a.biz_plan_item_no, \n";
			strSql += " 										 biz_plan_item_name), \n";
			strSql += " 										(a.p_no) \n";
			strSql += " 									   ) \n";
			strSql += " 				)	a, \n";
			strSql += " 				t_pl_item b \n";
			strSql += " 			where b.biz_plan_item_no = a.biz_plan_item_no(+)					 \n";
			strSql += " 			start with a.p_no = 3 \n";
			strSql += " 			connect by prior a.biz_plan_item_no = a.p_no \n";
			strSql += " 			order siblings by item_level_seq \n";
			strSql += " 			) \n";
			strSql += " 		where p_no=3 \n";
			strSql += " 		group by p_no \n";
			strSql += " 		) \n";
			strSql += " 	order by div \n";
			strSql += " 	) ";
			
			lrArgData.addColumn("1COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("2CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("3COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("4CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("5COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("6CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("7COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("8CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addRow();
			lrArgData.setValue("1COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("2CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("3COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("4CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("5COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("6CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("7COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("8CLSE_ACC_ID", strCLSE_ACC_ID);
			try
			{
				lrReturnData = CITDatabase.selectQuery(strSql, lrArgData);
				


				
				lrDataset = CITCommon.toGauceDataSet(lrReturnData);
				GauceInfo.response.enableFirstRow(lrDataset);
				lrDataset.flush();
			}
			catch (Exception ex)
			{
				if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
				GauceInfo.response.writeException("USER", "900001","MAIN Select 오류-> "+ ex.getMessage());
			}
		}
		else if (strAct.equals("COPY"))
		{

			
			strSql  = " select '######' comp_code, \n";
			strSql += " 	   '######' clse_acc_id, \n";
			strSql += " 	   '######' dept_code, \n";
			strSql += " 	   '######' month, \n";
			strSql += " 	   '######' bungi, \n";
			strSql += " 	   '######' mon1, \n";
			strSql += " 	   '######' mon2, \n";
			strSql += " 	   '######' mon3, \n";
			strSql += " 	   '######' b_clse_acc_id, \n";
			strSql += " 	   '######' n_clse_acc_id, \n";
			strSql += " 	   '######' emp_no \n";
			strSql += " from dual ";
			

			try
			{
				lrReturnData = CITDatabase.selectQuery(strSql, lrArgData);
				


				
				lrDataset = CITCommon.toGauceDataSet(lrReturnData);
				GauceInfo.response.enableFirstRow(lrDataset);
				lrDataset.flush();
			}
			catch (Exception ex)
			{
				if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
				GauceInfo.response.writeException("USER", "900001","COPY Select 오류-> "+ ex.getMessage());
			}
		}
		
	}
	catch (Exception ex)
	{
		if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
		GauceInfo.response.writeException("SYS", "100001", "페이지 초기화 오류 -> " + ex.getMessage());
	}
	finally
	{
		try
		{
			CITCommon.finalServerPage(GauceInfo);
		}
		catch (Exception ex)
		{
			if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
			GauceInfo.response.writeException("SYS", "100002", "페이지 종료 오류 -> " + ex.getMessage());
		}
	}
%>