<%@ page import="com.cj.common.*, com.cj.database.*, com.cj.util.*, com.gauce.*, com.gauce.io.*, java.sql.*" errorPage="../common/Error.jsp" contentType="text/html;charset=euc-kr"%>
<%
/**************************************************************************/
/* 1. 프 로 그 램 id : 
/* 2. 유형(시나리오) : Select Page
/* 3. 기  능  정  의 : 
/* 4. 변  경  이  력 : 한재원 작성(2006-05-03)
/* 5. 관련  프로그램 : 
/* 6. 특  기  사  항 : 
/**************************************************************************/
 
	CITGauceInfo GauceInfo = null;
	
	CITData lrReturnData = null;
	GauceDataSet lrDataset = null;

	String	strSql = "";
	String	strAct = "";
	
	try
	{
		GauceInfo = CITCommon.initServerPage(request, response, session);
		
		CITData lrArgData = new CITData();
		
		strAct = CITCommon.toKOR(request.getParameter("ACT"));
		
		if (strAct.equals("MAIN"))
		{
			String strCOMP_CODE = CITCommon.toKOR(request.getParameter("COMP_CODE"));
			String strCLSE_ACC_ID = CITCommon.toKOR(request.getParameter("CLSE_ACC_ID"));
			String strBUNGI = CITCommon.toKOR(request.getParameter("BUNGI"));
			
			strSql  = " select  div, \n";
			strSql += " 		a.p_no, \n";
			strSql += " 	    b.biz_plan_item_no, \n";
			strSql += " 	    lpad(' ', (level-1) *2 ) || a.biz_plan_item_name biz_plan_item_name,    \n";
			strSql += " 	    b_y_exec_bg,   \n";
			strSql += " 	    c_y_plan_bg,   \n";
			strSql += " 	    c_y_forecast_bg,   \n";
			strSql += " 		c_plan_rate19,       \n";
			strSql += " 		b_rate19    \n";
			strSql += " from \n";
			strSql += " 	( \n";
			strSql += " 	select  '11' div, \n";
			strSql += " 			a.p_no, \n";
			strSql += " 			a.biz_plan_item_no, \n";
			strSql += " 			biz_plan_item_name, \n";
			strSql += " 			sum(b_y_exec_bg)  b_y_exec_bg,      \n";
			strSql += " 			sum(c_y_plan_bg)  c_y_plan_bg,      \n";
			strSql += " 			sum(c_y_forecast_bg)  c_y_forecast_bg,      \n";
			strSql += " 			sum(c_plan_rate19)   c_plan_rate19,      \n";
			strSql += " 			sum(b_rate19)        b_rate19 \n";
			strSql += " 	from t_pl_item a, \n";
			strSql += " 		 (select  \n";
			strSql += " 				 b3.biz_plan_item_no, \n";
			strSql += " 				 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 				 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg,  \n";
			strSql += " 		 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 				 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 				 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19 \n";
			strSql += " 		  from  \n";
			strSql += " 				  \n";
			strSql += " 				 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  b_y_exec_bg \n";
			strSql += " 				  from  \n";
			strSql += " 					  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 					 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 					   from   t_pl_comp_plan_exec \n";
			strSql += " 					   where  comp_code   =  ?  \n";
			strSql += " 					   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 					   and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 					   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 				 ) b2, \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(plan_amt) c_y_plan_bg,  \n";
			strSql += " 				 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 				  from  t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  \n";
			strSql += " 				  and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 				 ) b3 \n";
			strSql += "    \n";
			strSql += " 		  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 		  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 		  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 		  ) b \n";
			strSql += " 	where a.biz_plan_item_no = b.biz_plan_item_no(+) \n";
			strSql += " 	group by grouping sets ((a.p_no, \n";
			strSql += " 			 		  	     a.biz_plan_item_no, \n";
			strSql += " 							 biz_plan_item_name), \n";
			strSql += " 							(a.p_no)) \n";
			strSql += " 							 \n";
			strSql += " 	union all \n";
			strSql += " 	 \n";
			strSql += " 	select \n";
			strSql += " 		  '12' div, \n";
			strSql += " 		  b1.p_no, \n";
			strSql += " 	      b1.biz_plan_item_no, \n";
			strSql += " 	      '(%)' biz_plan_item_name, \n";
			strSql += " 		  decode(a1.b_y_exec_bg, 0, 0, round((b1.b_y_exec_bg/a1.b_y_exec_bg)*100,1)) b_y_exec_bg, \n";
			strSql += " 		  decode(a1.c_y_plan_bg, 0, 0, round((b1.c_y_plan_bg/a1.c_y_plan_bg)*100,1)) c_y_plan_bg, \n";
			strSql += " 		  decode(a1.c_y_forecast_bg, 0, 0, round((b1.c_y_forecast_bg/a1.c_y_forecast_bg)*100,1)) c_y_forecast_bg, \n";
			strSql += " 		  0 c_plan_rate19, \n";
			strSql += " 		  0 b_rate19 \n";
			strSql += " 	 from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19 \n";
			strSql += " 	  from \n";
			strSql += " 			  \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19 \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출이익') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) b1 \n";
			strSql += " 	 where b1.div = a1.div(+) \n";
			strSql += "  \n";
			strSql += " 	 union all \n";
			strSql += "  \n";
			strSql += " 	 select \n";
			strSql += " 	  '12' div, \n";
			strSql += " 	  b1.p_no, \n";
			strSql += "       b1.biz_plan_item_no, \n";
			strSql += "       '(%)' biz_plan_item_name, \n";
			strSql += " 	  decode(a1.b_y_exec_bg, 0, 0, round((b1.b_y_exec_bg/a1.b_y_exec_bg)*100,1)) b_y_exec_bg, \n";
			strSql += " 	  decode(a1.c_y_plan_bg, 0, 0, round((b1.c_y_plan_bg/a1.c_y_plan_bg)*100,1)) c_y_plan_bg, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg, 0, 0, round((b1.c_y_forecast_bg/a1.c_y_forecast_bg)*100,1)) c_y_forecast_bg, \n";
			strSql += " 	  0 c_plan_rate19, \n";
			strSql += " 	  0 b_rate19 \n";
			strSql += " from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19 \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19 \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '영업이익') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) b1 \n";
			strSql += " 	 where b1.div = a1.div(+) \n";
			strSql += " 	  \n";
			strSql += " 	 union all \n";
			strSql += "  \n";
			strSql += " 	 select \n";
			strSql += " 	  '12' div, \n";
			strSql += " 	  b1.p_no, \n";
			strSql += "       b1.biz_plan_item_no, \n";
			strSql += "       '(%)' biz_plan_item_name, \n";
			strSql += " 	  decode(a1.b_y_exec_bg, 0, 0, round((b1.b_y_exec_bg/a1.b_y_exec_bg)*100,1)) b_y_exec_bg, \n";
			strSql += " 	  decode(a1.c_y_plan_bg, 0, 0, round((b1.c_y_plan_bg/a1.c_y_plan_bg)*100,1)) c_y_plan_bg, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg, 0, 0, round((b1.c_y_forecast_bg/a1.c_y_forecast_bg)*100,1)) c_y_forecast_bg, \n";
			strSql += " 	  0 c_plan_rate19, \n";
			strSql += " 	  0 b_rate19 \n";
			strSql += " from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19 \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19 \n";
			strSql += " 	  from \n";
			strSql += " 			  \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '경상이익') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) b1 \n";
			strSql += " 	 where b1.div = a1.div(+) \n";
			strSql += " 	  \n";
			strSql += " 	 union all \n";
			strSql += "  \n";
			strSql += " 	 select \n";
			strSql += " 	  '12' div, \n";
			strSql += " 	  b1.p_no, \n";
			strSql += "       b1.biz_plan_item_no, \n";
			strSql += "       '(%)' biz_plan_item_name, \n";
			strSql += " 	  decode(a1.b_y_exec_bg, 0, 0, round((b1.b_y_exec_bg/a1.b_y_exec_bg)*100,1)) b_y_exec_bg, \n";
			strSql += " 	  decode(a1.c_y_plan_bg, 0, 0, round((b1.c_y_plan_bg/a1.c_y_plan_bg)*100,1)) c_y_plan_bg, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg, 0, 0, round((b1.c_y_forecast_bg/a1.c_y_forecast_bg)*100,1)) c_y_forecast_bg, \n";
			strSql += " 	  0 c_plan_rate19, \n";
			strSql += " 	  0 b_rate19 \n";
			strSql += " 	  from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round(b_y_exec_amt/100000000,0))  b_y_exec_amt, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19 \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id, \n";
			strSql += " 		 		  biz_plan_item_no,  b_y_exec_amt \n";
			strSql += " 			  from \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(exec_amt) b_y_exec_amt \n";
			strSql += " 				  from t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  - 1 \n";
			strSql += " 				  group by comp_code, clse_acc_id, biz_plan_item_no) \n";
			strSql += " 			  ) b1, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			   \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19 \n";
			strSql += " 	  from \n";
			strSql += " 			 \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) between F_T_Get_Bungi_Month( ? , 'F') and F_T_Get_Bungi_Month( ? , 'E') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '세전이익') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) b1 \n";
			strSql += " 	 where b1.div = a1.div(+) \n";
			strSql += " 	)	a, \n";
			strSql += " 	(select * \n";
			strSql += " 	from t_pl_item \n";
			strSql += " 	where level_tag in ('1','2')) b \n";
			strSql += " where b.biz_plan_item_no = a.biz_plan_item_no					 \n";
			strSql += " start with a.p_no = '0' \n";
			strSql += " connect by prior a.biz_plan_item_no = a.p_no \n";
			strSql += " order siblings by item_level_seq \n";
			strSql += "  ";
			
			lrArgData.addColumn("1COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("2CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("3BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("4BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("5COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("6CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("7BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("8BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("9COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("10CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("11BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("12BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("13COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("14CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("15BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("16BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("17COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("18CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("19BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("20BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("21COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("22CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("23BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("24BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("25COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("26CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("27BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("28BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("29COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("30CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("31BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("32BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("33COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("34CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("35BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("36BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("37COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("38CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("39BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("40BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("41COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("42CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("43BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("44BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("45COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("46CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("47BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("48BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("49COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("50CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("51BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("52BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("53COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("54CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("55BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("56BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("57COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("58CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("59COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("60CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("61BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("62BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("63COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("64CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("65BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("66BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("67COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("68CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("69BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("70BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("71COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("72CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("73BUNGI", CITData.VARCHAR2);
			lrArgData.addColumn("74BUNGI", CITData.VARCHAR2);
			lrArgData.addRow();
			lrArgData.setValue("1COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("2CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("3BUNGI", strBUNGI);
			lrArgData.setValue("4BUNGI", strBUNGI);
			lrArgData.setValue("5COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("6CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("7BUNGI", strBUNGI);
			lrArgData.setValue("8BUNGI", strBUNGI);
			lrArgData.setValue("9COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("10CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("11BUNGI", strBUNGI);
			lrArgData.setValue("12BUNGI", strBUNGI);
			lrArgData.setValue("13COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("14CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("15BUNGI", strBUNGI);
			lrArgData.setValue("16BUNGI", strBUNGI);
			lrArgData.setValue("17COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("18CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("19BUNGI", strBUNGI);
			lrArgData.setValue("20BUNGI", strBUNGI);
			lrArgData.setValue("21COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("22CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("23BUNGI", strBUNGI);
			lrArgData.setValue("24BUNGI", strBUNGI);
			lrArgData.setValue("25COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("26CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("27BUNGI", strBUNGI);
			lrArgData.setValue("28BUNGI", strBUNGI);
			lrArgData.setValue("29COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("30CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("31BUNGI", strBUNGI);
			lrArgData.setValue("32BUNGI", strBUNGI);
			lrArgData.setValue("33COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("34CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("35BUNGI", strBUNGI);
			lrArgData.setValue("36BUNGI", strBUNGI);
			lrArgData.setValue("37COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("38CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("39BUNGI", strBUNGI);
			lrArgData.setValue("40BUNGI", strBUNGI);
			lrArgData.setValue("41COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("42CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("43BUNGI", strBUNGI);
			lrArgData.setValue("44BUNGI", strBUNGI);
			lrArgData.setValue("45COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("46CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("47BUNGI", strBUNGI);
			lrArgData.setValue("48BUNGI", strBUNGI);
			lrArgData.setValue("49COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("50CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("51BUNGI", strBUNGI);
			lrArgData.setValue("52BUNGI", strBUNGI);
			lrArgData.setValue("53COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("54CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("55BUNGI", strBUNGI);
			lrArgData.setValue("56BUNGI", strBUNGI);
			lrArgData.setValue("57COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("58CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("59COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("60CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("61BUNGI", strBUNGI);
			lrArgData.setValue("62BUNGI", strBUNGI);
			lrArgData.setValue("63COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("64CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("65BUNGI", strBUNGI);
			lrArgData.setValue("66BUNGI", strBUNGI);
			lrArgData.setValue("67COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("68CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("69BUNGI", strBUNGI);
			lrArgData.setValue("70BUNGI", strBUNGI);
			lrArgData.setValue("71COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("72CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("73BUNGI", strBUNGI);
			lrArgData.setValue("74BUNGI", strBUNGI);
			try
			{
				lrReturnData = CITDatabase.selectQuery(strSql, lrArgData);
				


				
				lrDataset = CITCommon.toGauceDataSet(lrReturnData);
				GauceInfo.response.enableFirstRow(lrDataset);
				lrDataset.flush();
			}
			catch (Exception ex)
			{
				if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
				GauceInfo.response.writeException("USER", "900001","MAIN Select 오류-> "+ ex.getMessage());
			}
		}
		else if (strAct.equals("COPY"))
		{

			
			strSql  = " select '######' comp_code, \n";
			strSql += " 	   '######' clse_acc_id, \n";
			strSql += " 	   '######' dept_code, \n";
			strSql += " 	   '######' month, \n";
			strSql += " 	   '######' bungi, \n";
			strSql += " 	   '######' b_clse_acc_id, \n";
			strSql += " 	   '######' n_clse_acc_id, \n";
			strSql += " 	   '######' emp_no \n";
			strSql += " from dual ";
			

			try
			{
				lrReturnData = CITDatabase.selectQuery(strSql, lrArgData);
				


				
				lrDataset = CITCommon.toGauceDataSet(lrReturnData);
				GauceInfo.response.enableFirstRow(lrDataset);
				lrDataset.flush();
			}
			catch (Exception ex)
			{
				if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
				GauceInfo.response.writeException("USER", "900001","COPY Select 오류-> "+ ex.getMessage());
			}
		}
		
	}
	catch (Exception ex)
	{
		if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
		GauceInfo.response.writeException("SYS", "100001", "페이지 초기화 오류 -> " + ex.getMessage());
	}
	finally
	{
		try
		{
			CITCommon.finalServerPage(GauceInfo);
		}
		catch (Exception ex)
		{
			if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
			GauceInfo.response.writeException("SYS", "100002", "페이지 종료 오류 -> " + ex.getMessage());
		}
	}
%>