<%@ page import="com.cj.common.*, com.cj.database.*, com.cj.util.*, com.gauce.*, com.gauce.io.*, java.sql.*" errorPage="../common/Error.jsp" contentType="text/html;charset=euc-kr"%>
<%
/**************************************************************************/
/* 1. 프 로 그 램 id : 
/* 2. 유형(시나리오) : Select Page
/* 3. 기  능  정  의 : 
/* 4. 변  경  이  력 : 한재원 작성(2006-05-03)
/* 5. 관련  프로그램 : 
/* 6. 특  기  사  항 : 
/**************************************************************************/
 
	CITGauceInfo GauceInfo = null;
	
	CITData lrReturnData = null;
	GauceDataSet lrDataset = null;

	String	strSql = "";
	String	strAct = "";
	
	try
	{
		GauceInfo = CITCommon.initServerPage(request, response, session);
		
		CITData lrArgData = new CITData();
		
		strAct = CITCommon.toKOR(request.getParameter("ACT"));
		
		if (strAct.equals("MAIN"))
		{
			String strCOMP_CODE = CITCommon.toKOR(request.getParameter("COMP_CODE"));
			String strCLSE_ACC_ID = CITCommon.toKOR(request.getParameter("CLSE_ACC_ID"));
			String strMON1 = CITCommon.toKOR(request.getParameter("MON1"));
			String strMON2 = CITCommon.toKOR(request.getParameter("MON2"));
			String strMON3 = CITCommon.toKOR(request.getParameter("MON3"));
			
			strSql  = " select  div, \n";
			strSql += " 		a.p_no, \n";
			strSql += " 	    b.biz_plan_item_no, \n";
			strSql += " 	    lpad(' ', (level-1) *2 ) || a.biz_plan_item_name biz_plan_item_name,    \n";
			strSql += " 	    b_y_exec_bg,   \n";
			strSql += " 	    c_y_plan_bg,   \n";
			strSql += " 	    c_y_forecast_bg,   \n";
			strSql += " 		c_plan_rate19,       \n";
			strSql += " 		b_rate19, \n";
			strSql += " 		b_y_exec_bg2,   \n";
			strSql += " 	    c_y_plan_bg2,   \n";
			strSql += " 	    c_y_forecast_bg2,   \n";
			strSql += " 		c_plan_rate192,       \n";
			strSql += " 		b_rate192, \n";
			strSql += " 		b_y_exec_bg3,   \n";
			strSql += " 	    c_y_plan_bg3,   \n";
			strSql += " 	    c_y_forecast_bg3,   \n";
			strSql += " 		c_plan_rate193,       \n";
			strSql += " 		b_rate193    \n";
			strSql += " from \n";
			strSql += " 	( \n";
			strSql += " 	select  '11' div, \n";
			strSql += " 			a.p_no, \n";
			strSql += " 			a.biz_plan_item_no, \n";
			strSql += " 			biz_plan_item_name, \n";
			strSql += " 			sum(b_y_exec_bg)  b_y_exec_bg,      \n";
			strSql += " 			sum(c_y_plan_bg)  c_y_plan_bg,      \n";
			strSql += " 			sum(c_y_forecast_bg)  c_y_forecast_bg,      \n";
			strSql += " 			sum(c_plan_rate19)   c_plan_rate19,      \n";
			strSql += " 			sum(b_rate19)        b_rate19, \n";
			strSql += " 			sum(b_y_exec_bg2)  b_y_exec_bg2,      \n";
			strSql += " 			sum(c_y_plan_bg2)  c_y_plan_bg2,      \n";
			strSql += " 			sum(c_y_forecast_bg2)  c_y_forecast_bg2,      \n";
			strSql += " 			sum(c_plan_rate192)   c_plan_rate192,      \n";
			strSql += " 			sum(b_rate192)        b_rate192, \n";
			strSql += " 			sum(b_y_exec_bg3)  b_y_exec_bg3,      \n";
			strSql += " 			sum(c_y_plan_bg3)  c_y_plan_bg3,      \n";
			strSql += " 			sum(c_y_forecast_bg3)  c_y_forecast_bg3,      \n";
			strSql += " 			sum(c_plan_rate193)   c_plan_rate193,      \n";
			strSql += " 			sum(b_rate193)        b_rate193 \n";
			strSql += " 	from t_pl_item a, \n";
			strSql += " 		 (select  \n";
			strSql += " 				 b3.biz_plan_item_no, \n";
			strSql += " 				 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 				 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 		 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 				 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 				 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19, \n";
			strSql += " 				 decode(nvl(b_y_exec_bg2,0),0, 0, round(b_y_exec_bg2/100000000,0)) b_y_exec_bg2, \n";
			strSql += " 				 decode(nvl(c_y_plan_bg2,0),0, 0, round(c_y_plan_bg2/100000000,0)) c_y_plan_bg2, \n";
			strSql += " 		 		 decode(nvl(c_y_forecast_bg2,0),0, 0, round(c_y_forecast_bg2/100000000,0)) c_y_forecast_bg2, \n";
			strSql += " 				 decode(nvl(c_y_plan_bg2,0),0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(c_y_plan_bg2,0))*100,1)) c_plan_rate192, \n";
			strSql += " 				 decode(nvl(b_y_exec_bg2,0), 0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(b_y_exec_bg2,0))*100,1)) b_rate192, \n";
			strSql += " 				 decode(nvl(b_y_exec_bg3,0),0, 0, round(b_y_exec_bg3/100000000,0)) b_y_exec_bg3, \n";
			strSql += " 				 decode(nvl(c_y_plan_bg3,0),0, 0, round(c_y_plan_bg3/100000000,0)) c_y_plan_bg3, \n";
			strSql += " 		 		 decode(nvl(c_y_forecast_bg3,0),0, 0, round(c_y_forecast_bg3/100000000,0)) c_y_forecast_bg3, \n";
			strSql += " 				 decode(nvl(c_y_plan_bg3,0),0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(c_y_plan_bg3,0))*100,1)) c_plan_rate193, \n";
			strSql += " 				 decode(nvl(b_y_exec_bg3,0), 0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(b_y_exec_bg3,0))*100,1)) b_rate193 \n";
			strSql += " 		  from  \n";
			strSql += " 				  \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg2 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg2 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg2, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg2 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg3 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg3 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_3, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg3, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg3 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_3 \n";
			strSql += " 		  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 		  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 		  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 		  and     b3_2.comp_code = b2_2.comp_code(+) \n";
			strSql += " 		  and	  b3_2.clse_acc_id = b2_2.clse_acc_id(+) \n";
			strSql += " 		  and	  b3_2.biz_plan_item_no = b2_2.biz_plan_item_no(+) \n";
			strSql += " 		  and     b3_3.comp_code = b2_3.comp_code(+) \n";
			strSql += " 		  and	  b3_3.clse_acc_id = b2_3.clse_acc_id(+) \n";
			strSql += " 		  and	  b3_3.biz_plan_item_no = b2_3.biz_plan_item_no(+) \n";
			strSql += " 		  and     b3.comp_code = b3_2.comp_code(+) \n";
			strSql += " 		  and	  b3.clse_acc_id = b3_2.clse_acc_id(+) \n";
			strSql += " 		  and	  b3.biz_plan_item_no = b3_2.biz_plan_item_no(+) \n";
			strSql += " 		  and     b3.comp_code = b3_3.comp_code(+) \n";
			strSql += " 		  and	  b3.clse_acc_id = b3_3.clse_acc_id(+) \n";
			strSql += " 		  and	  b3.biz_plan_item_no = b3_3.biz_plan_item_no(+) \n";
			strSql += " 		  ) b \n";
			strSql += " 	where a.biz_plan_item_no = b.biz_plan_item_no(+) \n";
			strSql += " 	group by grouping sets ((a.p_no, \n";
			strSql += " 			 		  	     a.biz_plan_item_no, \n";
			strSql += " 							 biz_plan_item_name), \n";
			strSql += " 							(a.p_no)) \n";
			strSql += " 							 \n";
			strSql += " 	union all \n";
			strSql += " 	 \n";
			strSql += " 	select \n";
			strSql += " 		  '12' div, \n";
			strSql += " 		  b1.p_no, \n";
			strSql += " 	      b1.biz_plan_item_no, \n";
			strSql += " 	      '(%)' biz_plan_item_name, \n";
			strSql += " 		  decode(a1.b_y_exec_bg, 0, 0, round((b1.b_y_exec_bg/a1.b_y_exec_bg)*100,1)) b_y_exec_bg, \n";
			strSql += " 		  decode(a1.c_y_plan_bg, 0, 0, round((b1.c_y_plan_bg/a1.c_y_plan_bg)*100,1)) c_y_plan_bg, \n";
			strSql += " 		  decode(a1.c_y_forecast_bg, 0, 0, round((b1.c_y_forecast_bg/a1.c_y_forecast_bg)*100,1)) c_y_forecast_bg, \n";
			strSql += " 		  0 c_plan_rate19, \n";
			strSql += " 		  0 b_rate19, \n";
			strSql += " 		  decode(a1.b_y_exec_bg2, 0, 0, round((b1.b_y_exec_bg2/a1.b_y_exec_bg2)*100,1)) b_y_exec_bg2, \n";
			strSql += " 		  decode(a1.c_y_plan_bg2, 0, 0, round((b1.c_y_plan_bg2/a1.c_y_plan_bg2)*100,1)) c_y_plan_bg2, \n";
			strSql += " 		  decode(a1.c_y_forecast_bg2, 0, 0, round((b1.c_y_forecast_bg2/a1.c_y_forecast_bg2)*100,1)) c_y_forecast_bg2, \n";
			strSql += " 		  0 c_plan_rate192, \n";
			strSql += " 		  0 b_rate192, \n";
			strSql += " 		  decode(a1.b_y_exec_bg3, 0, 0, round((b1.b_y_exec_bg3/a1.b_y_exec_bg3)*100,1)) b_y_exec_bg3, \n";
			strSql += " 		  decode(a1.c_y_plan_bg3, 0, 0, round((b1.c_y_plan_bg3/a1.c_y_plan_bg3)*100,1)) c_y_plan_bg3, \n";
			strSql += " 		  decode(a1.c_y_forecast_bg3, 0, 0, round((b1.c_y_forecast_bg3/a1.c_y_forecast_bg3)*100,1)) c_y_forecast_bg3, \n";
			strSql += " 		  0 c_plan_rate193, \n";
			strSql += " 		  0 b_rate193 \n";
			strSql += " 	 from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0),0, 0, round(b_y_exec_bg2/100000000,0)) b_y_exec_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round(c_y_plan_bg2/100000000,0)) c_y_plan_bg2, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg2,0),0, 0, round(c_y_forecast_bg2/100000000,0)) c_y_forecast_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(c_y_plan_bg2,0))*100,1)) c_plan_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0), 0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(b_y_exec_bg2,0))*100,1)) b_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0),0, 0, round(b_y_exec_bg3/100000000,0)) b_y_exec_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round(c_y_plan_bg3/100000000,0)) c_y_plan_bg3, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg3,0),0, 0, round(c_y_forecast_bg3/100000000,0)) c_y_forecast_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(c_y_plan_bg3,0))*100,1)) c_plan_rate193, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0), 0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(b_y_exec_bg3,0))*100,1)) b_rate193 \n";
			strSql += " 	  from \n";
			strSql += " 			  \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg2 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg2 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg2, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg2 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg3 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg3 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_3, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg3, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg3 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_2.comp_code = b2_2.comp_code(+) \n";
			strSql += " 	  and	  b3_2.clse_acc_id = b2_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_2.biz_plan_item_no = b2_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_3.comp_code = b2_3.comp_code(+) \n";
			strSql += " 	  and	  b3_3.clse_acc_id = b2_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_3.biz_plan_item_no = b2_3.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_3.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0),0, 0, round(b_y_exec_bg2/100000000,0)) b_y_exec_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round(c_y_plan_bg2/100000000,0)) c_y_plan_bg2, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg2,0),0, 0, round(c_y_forecast_bg2/100000000,0)) c_y_forecast_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(c_y_plan_bg2,0))*100,1)) c_plan_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0), 0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(b_y_exec_bg2,0))*100,1)) b_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0),0, 0, round(b_y_exec_bg3/100000000,0)) b_y_exec_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round(c_y_plan_bg3/100000000,0)) c_y_plan_bg3, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg3,0),0, 0, round(c_y_forecast_bg3/100000000,0)) c_y_forecast_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(c_y_plan_bg3,0))*100,1)) c_plan_rate193, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0), 0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(b_y_exec_bg3,0))*100,1)) b_rate193 \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg2 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg2 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg2, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg2 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg3 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg3 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_3, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg3, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg3 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출이익') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_2.comp_code = b2_2.comp_code(+) \n";
			strSql += " 	  and	  b3_2.clse_acc_id = b2_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_2.biz_plan_item_no = b2_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_3.comp_code = b2_3.comp_code(+) \n";
			strSql += " 	  and	  b3_3.clse_acc_id = b2_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_3.biz_plan_item_no = b2_3.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_3.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) b1 \n";
			strSql += " 	 where b1.div = a1.div(+) \n";
			strSql += "  \n";
			strSql += " 	 union all \n";
			strSql += "  \n";
			strSql += " 	 select \n";
			strSql += " 	  '12' div, \n";
			strSql += " 	  b1.p_no, \n";
			strSql += "       b1.biz_plan_item_no, \n";
			strSql += "       '(%)' biz_plan_item_name, \n";
			strSql += " 	  decode(a1.b_y_exec_bg, 0, 0, round((b1.b_y_exec_bg/a1.b_y_exec_bg)*100,1)) b_y_exec_bg, \n";
			strSql += " 	  decode(a1.c_y_plan_bg, 0, 0, round((b1.c_y_plan_bg/a1.c_y_plan_bg)*100,1)) c_y_plan_bg, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg, 0, 0, round((b1.c_y_forecast_bg/a1.c_y_forecast_bg)*100,1)) c_y_forecast_bg, \n";
			strSql += " 	  0 c_plan_rate19, \n";
			strSql += " 	  0 b_rate19, \n";
			strSql += " 	  decode(a1.b_y_exec_bg2, 0, 0, round((b1.b_y_exec_bg2/a1.b_y_exec_bg2)*100,1)) b_y_exec_bg2, \n";
			strSql += " 	  decode(a1.c_y_plan_bg2, 0, 0, round((b1.c_y_plan_bg2/a1.c_y_plan_bg2)*100,1)) c_y_plan_bg2, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg2, 0, 0, round((b1.c_y_forecast_bg2/a1.c_y_forecast_bg2)*100,1)) c_y_forecast_bg2, \n";
			strSql += " 	  0 c_plan_rate192, \n";
			strSql += " 	  0 b_rate192, \n";
			strSql += " 	  decode(a1.b_y_exec_bg3, 0, 0, round((b1.b_y_exec_bg3/a1.b_y_exec_bg3)*100,1)) b_y_exec_bg3, \n";
			strSql += " 	  decode(a1.c_y_plan_bg3, 0, 0, round((b1.c_y_plan_bg3/a1.c_y_plan_bg3)*100,1)) c_y_plan_bg3, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg3, 0, 0, round((b1.c_y_forecast_bg3/a1.c_y_forecast_bg3)*100,1)) c_y_forecast_bg3, \n";
			strSql += " 	  0 c_plan_rate193, \n";
			strSql += " 	  0 b_rate193 \n";
			strSql += " from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0),0, 0, round(b_y_exec_bg2/100000000,0)) b_y_exec_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round(c_y_plan_bg2/100000000,0)) c_y_plan_bg2, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg2,0),0, 0, round(c_y_forecast_bg2/100000000,0)) c_y_forecast_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(c_y_plan_bg2,0))*100,1)) c_plan_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0), 0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(b_y_exec_bg2,0))*100,1)) b_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0),0, 0, round(b_y_exec_bg3/100000000,0)) b_y_exec_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round(c_y_plan_bg3/100000000,0)) c_y_plan_bg3, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg3,0),0, 0, round(c_y_forecast_bg3/100000000,0)) c_y_forecast_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(c_y_plan_bg3,0))*100,1)) c_plan_rate193, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0), 0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(b_y_exec_bg3,0))*100,1)) b_rate193 \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg2 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg2 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg2, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg2 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg3 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg3 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_3, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg3, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg3 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_2.comp_code = b2_2.comp_code(+) \n";
			strSql += " 	  and	  b3_2.clse_acc_id = b2_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_2.biz_plan_item_no = b2_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_3.comp_code = b2_3.comp_code(+) \n";
			strSql += " 	  and	  b3_3.clse_acc_id = b2_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_3.biz_plan_item_no = b2_3.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_3.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0),0, 0, round(b_y_exec_bg2/100000000,0)) b_y_exec_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round(c_y_plan_bg2/100000000,0)) c_y_plan_bg2, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg2,0),0, 0, round(c_y_forecast_bg2/100000000,0)) c_y_forecast_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(c_y_plan_bg2,0))*100,1)) c_plan_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0), 0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(b_y_exec_bg2,0))*100,1)) b_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0),0, 0, round(b_y_exec_bg3/100000000,0)) b_y_exec_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round(c_y_plan_bg3/100000000,0)) c_y_plan_bg3, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg3,0),0, 0, round(c_y_forecast_bg3/100000000,0)) c_y_forecast_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(c_y_plan_bg3,0))*100,1)) c_plan_rate193, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0), 0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(b_y_exec_bg3,0))*100,1)) b_rate193 \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg2 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg2 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg2, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg2 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg3 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg3 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_3, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg3, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg3 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '영업이익') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_2.comp_code = b2_2.comp_code(+) \n";
			strSql += " 	  and	  b3_2.clse_acc_id = b2_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_2.biz_plan_item_no = b2_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_3.comp_code = b2_3.comp_code(+) \n";
			strSql += " 	  and	  b3_3.clse_acc_id = b2_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_3.biz_plan_item_no = b2_3.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_3.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) b1 \n";
			strSql += " 	 where b1.div = a1.div(+) \n";
			strSql += " 	  \n";
			strSql += " 	 union all \n";
			strSql += "  \n";
			strSql += " 	 select \n";
			strSql += " 	  '12' div, \n";
			strSql += " 	  b1.p_no, \n";
			strSql += "       b1.biz_plan_item_no, \n";
			strSql += "       '(%)' biz_plan_item_name, \n";
			strSql += " 	  decode(a1.b_y_exec_bg, 0, 0, round((b1.b_y_exec_bg/a1.b_y_exec_bg)*100,1)) b_y_exec_bg, \n";
			strSql += " 	  decode(a1.c_y_plan_bg, 0, 0, round((b1.c_y_plan_bg/a1.c_y_plan_bg)*100,1)) c_y_plan_bg, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg, 0, 0, round((b1.c_y_forecast_bg/a1.c_y_forecast_bg)*100,1)) c_y_forecast_bg, \n";
			strSql += " 	  0 c_plan_rate19, \n";
			strSql += " 	  0 b_rate19, \n";
			strSql += " 	  decode(a1.b_y_exec_bg2, 0, 0, round((b1.b_y_exec_bg2/a1.b_y_exec_bg2)*100,1)) b_y_exec_bg2, \n";
			strSql += " 	  decode(a1.c_y_plan_bg2, 0, 0, round((b1.c_y_plan_bg2/a1.c_y_plan_bg2)*100,1)) c_y_plan_bg2, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg2, 0, 0, round((b1.c_y_forecast_bg2/a1.c_y_forecast_bg2)*100,1)) c_y_forecast_bg2, \n";
			strSql += " 	  0 c_plan_rate192, \n";
			strSql += " 	  0 b_rate192, \n";
			strSql += " 	  decode(a1.b_y_exec_bg3, 0, 0, round((b1.b_y_exec_bg3/a1.b_y_exec_bg3)*100,1)) b_y_exec_bg3, \n";
			strSql += " 	  decode(a1.c_y_plan_bg3, 0, 0, round((b1.c_y_plan_bg3/a1.c_y_plan_bg3)*100,1)) c_y_plan_bg3, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg3, 0, 0, round((b1.c_y_forecast_bg3/a1.c_y_forecast_bg3)*100,1)) c_y_forecast_bg3, \n";
			strSql += " 	  0 c_plan_rate193, \n";
			strSql += " 	  0 b_rate193 \n";
			strSql += " from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0),0, 0, round(b_y_exec_bg2/100000000,0)) b_y_exec_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round(c_y_plan_bg2/100000000,0)) c_y_plan_bg2, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg2,0),0, 0, round(c_y_forecast_bg2/100000000,0)) c_y_forecast_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(c_y_plan_bg2,0))*100,1)) c_plan_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0), 0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(b_y_exec_bg2,0))*100,1)) b_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0),0, 0, round(b_y_exec_bg3/100000000,0)) b_y_exec_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round(c_y_plan_bg3/100000000,0)) c_y_plan_bg3, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg3,0),0, 0, round(c_y_forecast_bg3/100000000,0)) c_y_forecast_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(c_y_plan_bg3,0))*100,1)) c_plan_rate193, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0), 0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(b_y_exec_bg3,0))*100,1)) b_rate193 \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg2 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg2 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg2, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg2 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg3 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg3 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_3, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg3, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg3 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_2.comp_code = b2_2.comp_code(+) \n";
			strSql += " 	  and	  b3_2.clse_acc_id = b2_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_2.biz_plan_item_no = b2_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_3.comp_code = b2_3.comp_code(+) \n";
			strSql += " 	  and	  b3_3.clse_acc_id = b2_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_3.biz_plan_item_no = b2_3.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_3.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0),0, 0, round(b_y_exec_bg2/100000000,0)) b_y_exec_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round(c_y_plan_bg2/100000000,0)) c_y_plan_bg2, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg2,0),0, 0, round(c_y_forecast_bg2/100000000,0)) c_y_forecast_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(c_y_plan_bg2,0))*100,1)) c_plan_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0), 0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(b_y_exec_bg2,0))*100,1)) b_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0),0, 0, round(b_y_exec_bg3/100000000,0)) b_y_exec_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round(c_y_plan_bg3/100000000,0)) c_y_plan_bg3, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg3,0),0, 0, round(c_y_forecast_bg3/100000000,0)) c_y_forecast_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(c_y_plan_bg3,0))*100,1)) c_plan_rate193, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0), 0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(b_y_exec_bg3,0))*100,1)) b_rate193 \n";
			strSql += " 	  from \n";
			strSql += " 			  \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg2 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg2 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg2, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg2 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg3 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg3 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_3, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg3, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg3 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '경상이익') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_2.comp_code = b2_2.comp_code(+) \n";
			strSql += " 	  and	  b3_2.clse_acc_id = b2_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_2.biz_plan_item_no = b2_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_3.comp_code = b2_3.comp_code(+) \n";
			strSql += " 	  and	  b3_3.clse_acc_id = b2_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_3.biz_plan_item_no = b2_3.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_3.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) b1 \n";
			strSql += " 	 where b1.div = a1.div(+) \n";
			strSql += " 	  \n";
			strSql += " 	 union all \n";
			strSql += "  \n";
			strSql += " 	 select \n";
			strSql += " 	  '12' div, \n";
			strSql += " 	  b1.p_no, \n";
			strSql += "       b1.biz_plan_item_no, \n";
			strSql += "       '(%)' biz_plan_item_name, \n";
			strSql += " 	  decode(a1.b_y_exec_bg, 0, 0, round((b1.b_y_exec_bg/a1.b_y_exec_bg)*100,1)) b_y_exec_bg, \n";
			strSql += " 	  decode(a1.c_y_plan_bg, 0, 0, round((b1.c_y_plan_bg/a1.c_y_plan_bg)*100,1)) c_y_plan_bg, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg, 0, 0, round((b1.c_y_forecast_bg/a1.c_y_forecast_bg)*100,1)) c_y_forecast_bg, \n";
			strSql += " 	  0 c_plan_rate19, \n";
			strSql += " 	  0 b_rate19, \n";
			strSql += " 	  decode(a1.b_y_exec_bg2, 0, 0, round((b1.b_y_exec_bg2/a1.b_y_exec_bg2)*100,1)) b_y_exec_bg2, \n";
			strSql += " 	  decode(a1.c_y_plan_bg2, 0, 0, round((b1.c_y_plan_bg2/a1.c_y_plan_bg2)*100,1)) c_y_plan_bg2, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg2, 0, 0, round((b1.c_y_forecast_bg2/a1.c_y_forecast_bg2)*100,1)) c_y_forecast_bg2, \n";
			strSql += " 	  0 c_plan_rate192, \n";
			strSql += " 	  0 b_rate192, \n";
			strSql += " 	  decode(a1.b_y_exec_bg3, 0, 0, round((b1.b_y_exec_bg3/a1.b_y_exec_bg3)*100,1)) b_y_exec_bg3, \n";
			strSql += " 	  decode(a1.c_y_plan_bg3, 0, 0, round((b1.c_y_plan_bg3/a1.c_y_plan_bg3)*100,1)) c_y_plan_bg3, \n";
			strSql += " 	  decode(a1.c_y_forecast_bg3, 0, 0, round((b1.c_y_forecast_bg3/a1.c_y_forecast_bg3)*100,1)) c_y_forecast_bg3, \n";
			strSql += " 	  0 c_plan_rate193, \n";
			strSql += " 	  0 b_rate193 \n";
			strSql += " 	  from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0),0, 0, round(b_y_exec_bg2/100000000,0)) b_y_exec_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round(c_y_plan_bg2/100000000,0)) c_y_plan_bg2, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg2,0),0, 0, round(c_y_forecast_bg2/100000000,0)) c_y_forecast_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(c_y_plan_bg2,0))*100,1)) c_plan_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0), 0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(b_y_exec_bg2,0))*100,1)) b_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0),0, 0, round(b_y_exec_bg3/100000000,0)) b_y_exec_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round(c_y_plan_bg3/100000000,0)) c_y_plan_bg3, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg3,0),0, 0, round(c_y_forecast_bg3/100000000,0)) c_y_forecast_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(c_y_plan_bg3,0))*100,1)) c_plan_rate193, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0), 0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(b_y_exec_bg3,0))*100,1)) b_rate193 \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg2 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg2 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg2, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg2 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg3 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg3 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_3, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg3, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg3 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_2.comp_code = b2_2.comp_code(+) \n";
			strSql += " 	  and	  b3_2.clse_acc_id = b2_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_2.biz_plan_item_no = b2_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_3.comp_code = b2_3.comp_code(+) \n";
			strSql += " 	  and	  b3_3.clse_acc_id = b2_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_3.biz_plan_item_no = b2_3.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_3.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 '12' div, \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b3.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0),0, 0, round(b_y_exec_bg/100000000,0)) b_y_exec_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round(c_y_plan_bg/100000000,0)) c_y_plan_bg, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg,0),0, 0, round(c_y_forecast_bg/100000000,0)) c_y_forecast_bg, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg,0),0, 0, round((nvl(c_y_forecast_bg,0)/nvl(c_y_plan_bg,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg,0), 0, 0, round((nvl(c_y_forecast_bg,0)/nvl(b_y_exec_bg,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0),0, 0, round(b_y_exec_bg2/100000000,0)) b_y_exec_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round(c_y_plan_bg2/100000000,0)) c_y_plan_bg2, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg2,0),0, 0, round(c_y_forecast_bg2/100000000,0)) c_y_forecast_bg2, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg2,0),0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(c_y_plan_bg2,0))*100,1)) c_plan_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg2,0), 0, 0, round((nvl(c_y_forecast_bg2,0)/nvl(b_y_exec_bg2,0))*100,1)) b_rate192, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0),0, 0, round(b_y_exec_bg3/100000000,0)) b_y_exec_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round(c_y_plan_bg3/100000000,0)) c_y_plan_bg3, \n";
			strSql += " 	 		 decode(nvl(c_y_forecast_bg3,0),0, 0, round(c_y_forecast_bg3/100000000,0)) c_y_forecast_bg3, \n";
			strSql += " 			 decode(nvl(c_y_plan_bg3,0),0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(c_y_plan_bg3,0))*100,1)) c_plan_rate193, \n";
			strSql += " 			 decode(nvl(b_y_exec_bg3,0), 0, 0, round((nvl(c_y_forecast_bg3,0)/nvl(b_y_exec_bg3,0))*100,1)) b_rate193 \n";
			strSql += " 	  from \n";
			strSql += " 			 \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg2 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg2 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg2, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg2 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_2, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_bg3 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_bg3 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2_3, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_bg3, \n";
			strSql += " 			 		 sum(forecast_amt) c_y_forecast_bg3 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and    substr(work_ym, 5,6) =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3_3, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '세전이익') c \n";
			strSql += " 	  where   b3.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_2.comp_code = b2_2.comp_code(+) \n";
			strSql += " 	  and	  b3_2.clse_acc_id = b2_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_2.biz_plan_item_no = b2_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3_3.comp_code = b2_3.comp_code(+) \n";
			strSql += " 	  and	  b3_3.clse_acc_id = b2_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3_3.biz_plan_item_no = b2_3.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_2.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_2.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_2.biz_plan_item_no(+) \n";
			strSql += " 	  and     b3.comp_code = b3_3.comp_code(+) \n";
			strSql += " 	  and	  b3.clse_acc_id = b3_3.clse_acc_id(+) \n";
			strSql += " 	  and	  b3.biz_plan_item_no = b3_3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  c.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	 ) b1 \n";
			strSql += " 	 where a1.div = b1.div(+) \n";
			strSql += " 	)	a, \n";
			strSql += " 	(select * \n";
			strSql += " 	from t_pl_item \n";
			strSql += " 	where level_tag in ('1','2')) b \n";
			strSql += " where b.biz_plan_item_no = a.biz_plan_item_no					 \n";
			strSql += " start with a.p_no = '0' \n";
			strSql += " connect by prior a.biz_plan_item_no = a.p_no \n";
			strSql += " order siblings by item_level_seq \n";
			strSql += "  ";
			
			lrArgData.addColumn("1COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("2CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("3MON1", CITData.VARCHAR2);
			lrArgData.addColumn("4COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("5CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("6MON1", CITData.VARCHAR2);
			lrArgData.addColumn("7COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("8CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("9MON2", CITData.VARCHAR2);
			lrArgData.addColumn("10COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("11CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("12MON2", CITData.VARCHAR2);
			lrArgData.addColumn("13COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("14CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("15MON3", CITData.VARCHAR2);
			lrArgData.addColumn("16COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("17CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("18MON3", CITData.VARCHAR2);
			lrArgData.addColumn("19COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("20CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("21MON1", CITData.VARCHAR2);
			lrArgData.addColumn("22COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("23CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("24MON1", CITData.VARCHAR2);
			lrArgData.addColumn("25COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("26CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("27MON2", CITData.VARCHAR2);
			lrArgData.addColumn("28COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("29CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("30MON2", CITData.VARCHAR2);
			lrArgData.addColumn("31COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("32CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("33MON3", CITData.VARCHAR2);
			lrArgData.addColumn("34COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("35CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("36MON3", CITData.VARCHAR2);
			lrArgData.addColumn("37COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("38CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("39MON1", CITData.VARCHAR2);
			lrArgData.addColumn("40COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("41CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("42MON1", CITData.VARCHAR2);
			lrArgData.addColumn("43COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("44CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("45MON2", CITData.VARCHAR2);
			lrArgData.addColumn("46COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("47CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("48MON2", CITData.VARCHAR2);
			lrArgData.addColumn("49COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("50CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("51MON3", CITData.VARCHAR2);
			lrArgData.addColumn("52COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("53CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("54MON3", CITData.VARCHAR2);
			lrArgData.addColumn("55COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("56CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("57MON1", CITData.VARCHAR2);
			lrArgData.addColumn("58COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("59CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("60MON1", CITData.VARCHAR2);
			lrArgData.addColumn("61COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("62CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("63MON2", CITData.VARCHAR2);
			lrArgData.addColumn("64COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("65CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("66MON2", CITData.VARCHAR2);
			lrArgData.addColumn("67COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("68CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("69MON3", CITData.VARCHAR2);
			lrArgData.addColumn("70COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("71CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("72MON3", CITData.VARCHAR2);
			lrArgData.addColumn("73COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("74CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("75MON1", CITData.VARCHAR2);
			lrArgData.addColumn("76COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("77CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("78MON1", CITData.VARCHAR2);
			lrArgData.addColumn("79COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("80CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("81MON2", CITData.VARCHAR2);
			lrArgData.addColumn("82COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("83CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("84MON2", CITData.VARCHAR2);
			lrArgData.addColumn("85COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("86CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("87MON3", CITData.VARCHAR2);
			lrArgData.addColumn("88COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("89CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("90MON3", CITData.VARCHAR2);
			lrArgData.addColumn("91COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("92CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("93MON1", CITData.VARCHAR2);
			lrArgData.addColumn("94COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("95CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("96MON1", CITData.VARCHAR2);
			lrArgData.addColumn("97COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("98CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("99MON2", CITData.VARCHAR2);
			lrArgData.addColumn("100COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("101CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("102MON2", CITData.VARCHAR2);
			lrArgData.addColumn("103COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("104CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("105MON3", CITData.VARCHAR2);
			lrArgData.addColumn("106COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("107CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("108MON3", CITData.VARCHAR2);
			lrArgData.addColumn("109COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("110CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("111MON1", CITData.VARCHAR2);
			lrArgData.addColumn("112COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("113CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("114MON1", CITData.VARCHAR2);
			lrArgData.addColumn("115COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("116CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("117MON2", CITData.VARCHAR2);
			lrArgData.addColumn("118COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("119CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("120MON2", CITData.VARCHAR2);
			lrArgData.addColumn("121COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("122CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("123MON3", CITData.VARCHAR2);
			lrArgData.addColumn("124COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("125CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("126MON3", CITData.VARCHAR2);
			lrArgData.addColumn("127COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("128CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("129MON1", CITData.VARCHAR2);
			lrArgData.addColumn("130COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("131CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("132MON1", CITData.VARCHAR2);
			lrArgData.addColumn("133COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("134CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("135MON2", CITData.VARCHAR2);
			lrArgData.addColumn("136COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("137CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("138MON2", CITData.VARCHAR2);
			lrArgData.addColumn("139COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("140CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("141MON3", CITData.VARCHAR2);
			lrArgData.addColumn("142COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("143CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("144MON3", CITData.VARCHAR2);
			lrArgData.addColumn("145COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("146CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("147MON1", CITData.VARCHAR2);
			lrArgData.addColumn("148COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("149CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("150MON1", CITData.VARCHAR2);
			lrArgData.addColumn("151COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("152CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("153MON2", CITData.VARCHAR2);
			lrArgData.addColumn("154COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("155CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("156MON2", CITData.VARCHAR2);
			lrArgData.addColumn("157COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("158CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("159MON3", CITData.VARCHAR2);
			lrArgData.addColumn("160COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("161CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("162MON3", CITData.VARCHAR2);
			lrArgData.addRow();
			lrArgData.setValue("1COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("2CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("3MON1", strMON1);
			lrArgData.setValue("4COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("5CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("6MON1", strMON1);
			lrArgData.setValue("7COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("8CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("9MON2", strMON2);
			lrArgData.setValue("10COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("11CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("12MON2", strMON2);
			lrArgData.setValue("13COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("14CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("15MON3", strMON3);
			lrArgData.setValue("16COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("17CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("18MON3", strMON3);
			lrArgData.setValue("19COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("20CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("21MON1", strMON1);
			lrArgData.setValue("22COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("23CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("24MON1", strMON1);
			lrArgData.setValue("25COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("26CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("27MON2", strMON2);
			lrArgData.setValue("28COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("29CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("30MON2", strMON2);
			lrArgData.setValue("31COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("32CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("33MON3", strMON3);
			lrArgData.setValue("34COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("35CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("36MON3", strMON3);
			lrArgData.setValue("37COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("38CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("39MON1", strMON1);
			lrArgData.setValue("40COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("41CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("42MON1", strMON1);
			lrArgData.setValue("43COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("44CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("45MON2", strMON2);
			lrArgData.setValue("46COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("47CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("48MON2", strMON2);
			lrArgData.setValue("49COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("50CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("51MON3", strMON3);
			lrArgData.setValue("52COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("53CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("54MON3", strMON3);
			lrArgData.setValue("55COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("56CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("57MON1", strMON1);
			lrArgData.setValue("58COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("59CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("60MON1", strMON1);
			lrArgData.setValue("61COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("62CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("63MON2", strMON2);
			lrArgData.setValue("64COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("65CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("66MON2", strMON2);
			lrArgData.setValue("67COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("68CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("69MON3", strMON3);
			lrArgData.setValue("70COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("71CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("72MON3", strMON3);
			lrArgData.setValue("73COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("74CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("75MON1", strMON1);
			lrArgData.setValue("76COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("77CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("78MON1", strMON1);
			lrArgData.setValue("79COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("80CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("81MON2", strMON2);
			lrArgData.setValue("82COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("83CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("84MON2", strMON2);
			lrArgData.setValue("85COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("86CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("87MON3", strMON3);
			lrArgData.setValue("88COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("89CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("90MON3", strMON3);
			lrArgData.setValue("91COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("92CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("93MON1", strMON1);
			lrArgData.setValue("94COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("95CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("96MON1", strMON1);
			lrArgData.setValue("97COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("98CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("99MON2", strMON2);
			lrArgData.setValue("100COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("101CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("102MON2", strMON2);
			lrArgData.setValue("103COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("104CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("105MON3", strMON3);
			lrArgData.setValue("106COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("107CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("108MON3", strMON3);
			lrArgData.setValue("109COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("110CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("111MON1", strMON1);
			lrArgData.setValue("112COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("113CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("114MON1", strMON1);
			lrArgData.setValue("115COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("116CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("117MON2", strMON2);
			lrArgData.setValue("118COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("119CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("120MON2", strMON2);
			lrArgData.setValue("121COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("122CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("123MON3", strMON3);
			lrArgData.setValue("124COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("125CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("126MON3", strMON3);
			lrArgData.setValue("127COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("128CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("129MON1", strMON1);
			lrArgData.setValue("130COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("131CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("132MON1", strMON1);
			lrArgData.setValue("133COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("134CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("135MON2", strMON2);
			lrArgData.setValue("136COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("137CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("138MON2", strMON2);
			lrArgData.setValue("139COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("140CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("141MON3", strMON3);
			lrArgData.setValue("142COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("143CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("144MON3", strMON3);
			lrArgData.setValue("145COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("146CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("147MON1", strMON1);
			lrArgData.setValue("148COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("149CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("150MON1", strMON1);
			lrArgData.setValue("151COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("152CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("153MON2", strMON2);
			lrArgData.setValue("154COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("155CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("156MON2", strMON2);
			lrArgData.setValue("157COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("158CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("159MON3", strMON3);
			lrArgData.setValue("160COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("161CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("162MON3", strMON3);
			try
			{
				lrReturnData = CITDatabase.selectQuery(strSql, lrArgData);
				


				
				lrDataset = CITCommon.toGauceDataSet(lrReturnData);
				GauceInfo.response.enableFirstRow(lrDataset);
				lrDataset.flush();
			}
			catch (Exception ex)
			{
				if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
				GauceInfo.response.writeException("USER", "900001","MAIN Select 오류-> "+ ex.getMessage());
			}
		}
		else if (strAct.equals("COPY"))
		{

			
			strSql  = " select '######' comp_code, \n";
			strSql += " 	   '######' clse_acc_id, \n";
			strSql += " 	   '######' dept_code, \n";
			strSql += " 	   '######' month, \n";
			strSql += " 	   '######' bungi, \n";
			strSql += " 	   '######' mon1, \n";
			strSql += " 	   '######' mon2, \n";
			strSql += " 	   '######' mon3, \n";
			strSql += " 	   '######' b_clse_acc_id, \n";
			strSql += " 	   '######' n_clse_acc_id, \n";
			strSql += " 	   '######' emp_no \n";
			strSql += " from dual ";
			

			try
			{
				lrReturnData = CITDatabase.selectQuery(strSql, lrArgData);
				


				
				lrDataset = CITCommon.toGauceDataSet(lrReturnData);
				GauceInfo.response.enableFirstRow(lrDataset);
				lrDataset.flush();
			}
			catch (Exception ex)
			{
				if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
				GauceInfo.response.writeException("USER", "900001","COPY Select 오류-> "+ ex.getMessage());
			}
		}
		
	}
	catch (Exception ex)
	{
		if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
		GauceInfo.response.writeException("SYS", "100001", "페이지 초기화 오류 -> " + ex.getMessage());
	}
	finally
	{
		try
		{
			CITCommon.finalServerPage(GauceInfo);
		}
		catch (Exception ex)
		{
			if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
			GauceInfo.response.writeException("SYS", "100002", "페이지 종료 오류 -> " + ex.getMessage());
		}
	}
%>