<%@ page import="com.cj.common.*, com.cj.database.*, com.cj.util.*, com.gauce.*, com.gauce.io.*, java.sql.*" errorPage="../common/Error.jsp" contentType="text/html;charset=euc-kr"%>
<%
/**************************************************************************/
/* 1. 프 로 그 램 id : 
/* 2. 유형(시나리오) : Select Page
/* 3. 기  능  정  의 : 
/* 4. 변  경  이  력 : 한재원 작성(2006-05-03)
/* 5. 관련  프로그램 : 
/* 6. 특  기  사  항 : 
/**************************************************************************/
 
	CITGauceInfo GauceInfo = null;
	
	CITData lrReturnData = null;
	GauceDataSet lrDataset = null;

	String	strSql = "";
	String	strAct = "";
	
	try
	{
		GauceInfo = CITCommon.initServerPage(request, response, session);
		
		CITData lrArgData = new CITData();
		
		strAct = CITCommon.toKOR(request.getParameter("ACT"));
		
		if (strAct.equals("MAIN"))
		{
			String strCOMP_CODE = CITCommon.toKOR(request.getParameter("COMP_CODE"));
			String strCLSE_ACC_ID = CITCommon.toKOR(request.getParameter("CLSE_ACC_ID"));
			
			strSql  = " select  div, \n";
			strSql += " 		a.p_no, \n";
			strSql += " 	    a.biz_plan_item_no, \n";
			strSql += " 	    lpad(' ', (level-1) *2 ) || a.biz_plan_item_name biz_plan_item_name, \n";
			strSql += " 	    b_y_exec_amt,     \n";
			strSql += " 	    b_y_exec_amt19,   \n";
			strSql += " 	    c_y_plan_amt19,   \n";
			strSql += " 	    c_y_exec_amt19,   \n";
			strSql += " 		c_plan_rate19,       \n";
			strSql += " 		b_rate19,         \n";
			strSql += " 		plan_amt10,       \n";
			strSql += " 		forecast_amt10,   \n";
			strSql += " 		plan_amt11,       \n";
			strSql += " 		forecast_amt11,   \n";
			strSql += " 		plan_amt12,       \n";
			strSql += " 		forecast_amt12,   \n";
			strSql += " 		c_y_plan_amt,     \n";
			strSql += " 		c_y_forecast_amt, \n";
			strSql += " 		c_plan_rate,      \n";
			strSql += " 		b_rate,           \n";
			strSql += " 		n_y_plan_amt, \n";
			strSql += " 		n_rate            \n";
			strSql += " from \n";
			strSql += " 	( \n";
			strSql += " 	select  '11' div, \n";
			strSql += " 			a.p_no, \n";
			strSql += " 			a.biz_plan_item_no, \n";
			strSql += " 			biz_plan_item_name, \n";
			strSql += " 		    sum(b_y_exec_amt)  	 b_y_exec_amt,   \n";
			strSql += " 			sum(b_y_exec_amt19)  b_y_exec_amt19,      \n";
			strSql += " 			sum(c_y_plan_amt19)  c_y_plan_amt19,      \n";
			strSql += " 			sum(c_y_exec_amt19)  c_y_exec_amt19,      \n";
			strSql += " 			sum(c_plan_rate19)   c_plan_rate19,      \n";
			strSql += " 			sum(b_rate19)        b_rate19,      \n";
			strSql += " 			sum(plan_amt10)      plan_amt10,      \n";
			strSql += " 			sum(forecast_amt10)  forecast_amt10,      \n";
			strSql += " 			sum(plan_amt11)      plan_amt11,      \n";
			strSql += " 			sum(forecast_amt11)  forecast_amt11,      \n";
			strSql += " 			sum(plan_amt12)      plan_amt12,      \n";
			strSql += " 			sum(forecast_amt12)  forecast_amt12,      \n";
			strSql += " 			sum(c_y_plan_amt)    c_y_plan_amt,      \n";
			strSql += " 			sum(c_y_forecast_amt) c_y_forecast_amt,   \n";
			strSql += " 			sum(c_plan_rate)	  c_plan_rate, \n";
			strSql += " 			sum(b_rate)	          b_rate, \n";
			strSql += " 			sum(n_y_plan_amt) n_y_plan_amt, \n";
			strSql += " 			sum(n_rate)	 		  n_rate	      \n";
			strSql += " 	from t_pl_item a, \n";
			strSql += " 		 (select  \n";
			strSql += " 				 b5.biz_plan_item_no, \n";
			strSql += " 				 decode(nvl(b_y_exec_amt,0), 0, 0, round(b_y_exec_amt/1000000,0))  b_y_exec_amt, \n";
			strSql += " 				 decode(nvl(b_y_exec_amt19,0),0, 0, round(b_y_exec_amt19/1000000,0)) b_y_exec_amt19, \n";
			strSql += " 				 decode(nvl(c_y_plan_amt19,0),0, 0, round(c_y_plan_amt19/1000000,0)) c_y_plan_amt19,  \n";
			strSql += " 		 		 decode(nvl(c_y_exec_amt19,0),0, 0, round(c_y_exec_amt19/1000000,0)) c_y_exec_amt19, \n";
			strSql += " 				 decode(nvl(c_y_plan_amt19,0),0, 0, round((nvl(c_y_exec_amt19,0)/nvl(c_y_plan_amt19,0))*100,1)) c_plan_rate19, \n";
			strSql += " 				 decode(nvl(b_y_exec_amt19,0), 0, 0, round((nvl(c_y_exec_amt19,0)/nvl(b_y_exec_amt19,0))*100,1)) b_rate19, \n";
			strSql += " 				 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10,  \n";
			strSql += " 				 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 				 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11,  \n";
			strSql += " 				 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 				 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 				 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12, \n";
			strSql += " 				 decode(nvl(c_y_plan_amt,0), 0, 0, round(c_y_plan_amt/1000000,0)) c_y_plan_amt, \n";
			strSql += " 				 decode(nvl(c_y_forecast_amt,0), 0, 0, round(c_y_forecast_amt/1000000,0)) c_y_forecast_amt, \n";
			strSql += " 				 decode(nvl(c_y_plan_amt,0),0, 0, round((nvl(c_y_forecast_amt,0)/nvl(c_y_plan_amt,0))*100,1)) c_plan_rate, \n";
			strSql += " 				 decode(nvl(b_y_exec_amt,0), 0, 0, round((nvl(c_y_forecast_amt,0)/nvl(b_y_exec_amt,0))*100,1)) b_rate, \n";
			strSql += " 				 decode(nvl(n_y_plan_amt,0),0, 0,  round(n_y_plan_amt,0)) n_y_plan_amt, \n";
			strSql += " 				 decode(nvl(n_y_plan_amt,0), 0, 0, round(((nvl(c_y_exec_amt19,0) + nvl(forecast_amt10,0) + nvl(forecast_amt11,0) + nvl(forecast_amt12,0))/nvl(n_y_plan_amt,0))*100,1)) n_rate \n";
			strSql += " 		  from  \n";
			strSql += " 				 (select comp_code, clse_acc_id + 1 clse_acc_id,  \n";
			strSql += " 			 		  biz_plan_item_no,  b_y_exec_amt \n";
			strSql += " 				  from  \n";
			strSql += " 					 (select comp_code, clse_acc_id,  biz_plan_item_no,  \n";
			strSql += " 					 		 sum(exec_amt) b_y_exec_amt \n";
			strSql += " 					  from t_pl_comp_plan_exec \n";
			strSql += " 					  where comp_code =  ?  \n";
			strSql += " 					  and	clse_acc_id =  ?  - 1 \n";
			strSql += " 					  group by comp_code, clse_acc_id, biz_plan_item_no) \n";
			strSql += " 				  ) b1, \n";
			strSql += " 				 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  b_y_exec_amt19 \n";
			strSql += " 				  from  \n";
			strSql += " 					  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 					 		  sum(exec_amt) b_y_exec_amt19 \n";
			strSql += " 					   from   t_pl_comp_plan_exec \n";
			strSql += " 					   where  comp_code   =  ?  \n";
			strSql += " 					   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 					   and    substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 					   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 				 ) b2, \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(plan_amt) c_y_plan_amt19,  \n";
			strSql += " 				 		 sum(exec_amt) c_y_exec_amt19 \n";
			strSql += " 				  from  t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  \n";
			strSql += " 				  and   substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 				 ) b3, \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no,  \n";
			strSql += " 				  		 sum(plan_amt10) plan_amt10, \n";
			strSql += " 						 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 						 sum(plan_amt11) plan_amt11, \n";
			strSql += " 						 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 						 sum(plan_amt12) plan_amt12,  \n";
			strSql += " 						 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 				  from( \n";
			strSql += " 					  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 					  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10,  \n";
			strSql += " 					  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 							 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 							 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 							 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 							 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 					  from   t_pl_comp_plan_exec \n";
			strSql += " 					  where  comp_code =  ?  \n";
			strSql += " 					  and	 clse_acc_id =  ?  \n";
			strSql += " 					  and    substr(work_ym, 5,6) in ('10', '11', '12') \n";
			strSql += " 					  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 					  		   substr(work_ym, 5,6)) \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 				  ) b4, \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no,  \n";
			strSql += " 				 		 sum(plan_amt) c_y_plan_amt, \n";
			strSql += " 						 sum(forecast_amt) c_y_forecast_amt \n";
			strSql += " 				  from t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 				  ) b5, \n";
			strSql += " 				  (select comp_code, clse_acc_id - 1 clse_acc_id,  biz_plan_item_no, n_y_plan_amt \n";
			strSql += " 				   from \n";
			strSql += " 					  (select comp_code, clse_acc_id,  biz_plan_item_no,  \n";
			strSql += " 					          sum(plan_amt) n_y_plan_amt \n";
			strSql += " 					   from   t_pl_comp_plan_exec \n";
			strSql += " 					   where  comp_code =  ?  \n";
			strSql += " 					   and	  clse_acc_id =  ?  + 1 \n";
			strSql += " 					   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 				  ) b6 \n";
			strSql += " 		  where   b5.comp_code = b1.comp_code(+) \n";
			strSql += " 		  and	  b5.comp_code = b2.comp_code(+) \n";
			strSql += " 		  and	  b5.comp_code = b3.comp_code(+) \n";
			strSql += " 		  and	  b5.comp_code = b4.comp_code(+) \n";
			strSql += " 		  and	  b5.comp_code = b6.comp_code(+) \n";
			strSql += " 		  and	  b5.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 		  and	  b5.clse_acc_id = b2.clse_acc_id(+)  \n";
			strSql += " 		  and	  b5.clse_acc_id = b3.clse_acc_id(+)  \n";
			strSql += " 		  and	  b5.clse_acc_id = b4.clse_acc_id(+) \n";
			strSql += " 		  and	  b5.clse_acc_id = b6.clse_acc_id(+) \n";
			strSql += " 		  and	  b5.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 		  and	  b5.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 		  and	  b5.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 		  and	  b5.biz_plan_item_no = b4.biz_plan_item_no(+) \n";
			strSql += " 		  and	  b5.biz_plan_item_no = b6.biz_plan_item_no(+) \n";
			strSql += " 		  ) b \n";
			strSql += " 	where a.biz_plan_item_no = b.biz_plan_item_no(+) \n";
			strSql += " 	group by grouping sets ((a.p_no, \n";
			strSql += " 			 		  	     a.biz_plan_item_no, \n";
			strSql += " 							 biz_plan_item_name), \n";
			strSql += " 							(a.p_no)) \n";
			strSql += " 							 \n";
			strSql += " 	union all \n";
			strSql += " 	 \n";
			strSql += " 	select \n";
			strSql += " 	  '12' div, \n";
			strSql += " 	  b1.p_no, \n";
			strSql += "       b1.biz_plan_item_no, \n";
			strSql += "       '(%)' biz_plan_item_name, \n";
			strSql += "       decode(a1.b_y_exec_amt, 0, 0, round((b1.b_y_exec_amt/a1.b_y_exec_amt)*100,1)) b_y_exec_amt, \n";
			strSql += " 	  decode(a1.b_y_exec_amt19, 0, 0, round((b1.b_y_exec_amt19/a1.b_y_exec_amt19)*100,1)) b_y_exec_amt19, \n";
			strSql += " 	  decode(a1.c_y_plan_amt19, 0, 0, round((b1.c_y_plan_amt19/a1.c_y_plan_amt19)*100,1)) c_y_plan_amt19, \n";
			strSql += " 	  decode(a1.c_y_exec_amt19, 0, 0, round((b1.c_y_exec_amt19/a1.c_y_exec_amt19)*100,1)) c_y_exec_amt19, \n";
			strSql += " 	  0 c_plan_rate19, \n";
			strSql += " 	  0 b_rate19, \n";
			strSql += " 	  decode(a1.plan_amt10, 0, 0, round((b1.plan_amt10/a1.plan_amt10)*100,1)) plan_amt10, \n";
			strSql += " 	  decode(a1.forecast_amt10, 0, 0, round((b1.forecast_amt10/a1.forecast_amt10)*100,1)) forecast_amt10, \n";
			strSql += " 	  decode(a1.plan_amt11, 0, 0, round((b1.plan_amt11/a1.plan_amt11)*100,1)) plan_amt11, \n";
			strSql += " 	  decode(a1.forecast_amt11, 0, 0, round((b1.forecast_amt11/a1.forecast_amt11)*100,1)) forecast_amt11, \n";
			strSql += " 	  decode(a1.plan_amt12, 0, 0, round((b1.plan_amt12/a1.plan_amt12)*100,1)) plan_amt12, \n";
			strSql += " 	  decode(a1.forecast_amt12, 0, 0, round((b1.forecast_amt12/a1.b_y_exec_amt)*100,1)) b_y_exec_amt, \n";
			strSql += " 	  decode(a1.c_y_plan_amt, 0, 0, round((b1.c_y_plan_amt/a1.c_y_plan_amt)*100,1)) c_y_plan_amt, \n";
			strSql += " 	  decode(a1.c_y_forecast_amt, 0, 0, round((b1.c_y_forecast_amt/a1.c_y_forecast_amt)*100,1)) c_y_forecast_amt, \n";
			strSql += " 	  0 c_plan_rate, \n";
			strSql += " 	  0 b_rate, \n";
			strSql += " 	  decode(a1.n_y_plan_amt, 0, 0, round((b1.n_y_plan_amt/a1.n_y_plan_amt)*100,1)) n_y_plan_amt, \n";
			strSql += " 	  0 n_rate \n";
			strSql += " from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b5.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round(b_y_exec_amt/1000000,0))  b_y_exec_amt, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0),0, 0, round(b_y_exec_amt19/1000000,0)) b_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round(c_y_plan_amt19/1000000,0)) c_y_plan_amt19, \n";
			strSql += " 	 		 decode(nvl(c_y_exec_amt19,0),0, 0, round(c_y_exec_amt19/1000000,0)) c_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round((nvl(c_y_exec_amt19,0)/nvl(c_y_plan_amt19,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0), 0, 0, round((nvl(c_y_exec_amt19,0)/nvl(b_y_exec_amt19,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10, \n";
			strSql += " 			 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 			 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11, \n";
			strSql += " 			 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 			 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 			 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0), 0, 0, round(c_y_plan_amt/1000000,0)) c_y_plan_amt, \n";
			strSql += " 			 decode(nvl(c_y_forecast_amt,0), 0, 0, round(c_y_forecast_amt/1000000,0)) c_y_forecast_amt, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0),0, 0, round((nvl(c_y_forecast_amt,0)/nvl(c_y_plan_amt,0))*100,1)) c_plan_rate, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round((nvl(c_y_forecast_amt,0)/nvl(b_y_exec_amt,0))*100,1)) b_rate, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0),0, 0,  round(n_y_plan_amt,0)) n_y_plan_amt, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0), 0, 0, round(((nvl(c_y_exec_amt19,0) + nvl(forecast_amt10,0) + nvl(forecast_amt11,0) + nvl(forecast_amt12,0))/nvl(n_y_plan_amt,0))*100,1)) n_rate \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id, \n";
			strSql += " 		 		  biz_plan_item_no,  b_y_exec_amt \n";
			strSql += " 			  from \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(exec_amt) b_y_exec_amt \n";
			strSql += " 				  from t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  - 1 \n";
			strSql += " 				  group by comp_code, clse_acc_id, biz_plan_item_no) \n";
			strSql += " 			  ) b1, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_amt19 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_amt19 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt19, \n";
			strSql += " 			 		 sum(exec_amt) c_y_exec_amt19 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and   substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			  		 sum(plan_amt10) plan_amt10, \n";
			strSql += " 					 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 					 sum(plan_amt11) plan_amt11, \n";
			strSql += " 					 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 					 sum(plan_amt12) plan_amt12, \n";
			strSql += " 					 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 			  from( \n";
			strSql += " 				  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 				  from   t_pl_comp_plan_exec \n";
			strSql += " 				  where  comp_code =  ?  \n";
			strSql += " 				  and	 clse_acc_id =  ?  \n";
			strSql += " 				  and    substr(work_ym, 5,6) in ('10', '11', '12') \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		   substr(work_ym, 5,6)) \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b4, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt, \n";
			strSql += " 					 sum(forecast_amt) c_y_forecast_amt \n";
			strSql += " 			  from t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b5, \n";
			strSql += " 			  (select comp_code, clse_acc_id - 1 clse_acc_id,  biz_plan_item_no, n_y_plan_amt \n";
			strSql += " 			   from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				          sum(plan_amt) n_y_plan_amt \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  + 1 \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			  ) b6, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b5.comp_code = b1.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b3.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b4.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b6.comp_code(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b3.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b4.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b6.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b4.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b6.biz_plan_item_no(+) \n";
			strSql += " 	  and     c.biz_plan_item_no = b5.biz_plan_item_no(+) \n";
			strSql += " 	  --and     c.biz_plan_item_name = '매출액' \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b5.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round(b_y_exec_amt/1000000,0))  b_y_exec_amt, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0),0, 0, round(b_y_exec_amt19/1000000,0)) b_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round(c_y_plan_amt19/1000000,0)) c_y_plan_amt19, \n";
			strSql += " 	 		 decode(nvl(c_y_exec_amt19,0),0, 0, round(c_y_exec_amt19/1000000,0)) c_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round((nvl(c_y_exec_amt19,0)/nvl(c_y_plan_amt19,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0), 0, 0, round((nvl(c_y_exec_amt19,0)/nvl(b_y_exec_amt19,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10, \n";
			strSql += " 			 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 			 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11, \n";
			strSql += " 			 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 			 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 			 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0), 0, 0, round(c_y_plan_amt/1000000,0)) c_y_plan_amt, \n";
			strSql += " 			 decode(nvl(c_y_forecast_amt,0), 0, 0, round(c_y_forecast_amt/1000000,0)) c_y_forecast_amt, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0),0, 0, round((nvl(c_y_forecast_amt,0)/nvl(c_y_plan_amt,0))*100,1)) c_plan_rate, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round((nvl(c_y_forecast_amt,0)/nvl(b_y_exec_amt,0))*100,1)) b_rate, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0),0, 0,  round(n_y_plan_amt,0)) n_y_plan_amt, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0), 0, 0, round(((nvl(c_y_exec_amt19,0) + nvl(forecast_amt10,0) + nvl(forecast_amt11,0) + nvl(forecast_amt12,0))/nvl(n_y_plan_amt,0))*100,1)) n_rate \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id, \n";
			strSql += " 		 		  biz_plan_item_no,  b_y_exec_amt \n";
			strSql += " 			  from \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(exec_amt) b_y_exec_amt \n";
			strSql += " 				  from t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  - 1 \n";
			strSql += " 				  group by comp_code, clse_acc_id, biz_plan_item_no) \n";
			strSql += " 			  ) b1, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_amt19 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_amt19 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt19, \n";
			strSql += " 			 		 sum(exec_amt) c_y_exec_amt19 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and   substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			  		 sum(plan_amt10) plan_amt10, \n";
			strSql += " 					 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 					 sum(plan_amt11) plan_amt11, \n";
			strSql += " 					 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 					 sum(plan_amt12) plan_amt12, \n";
			strSql += " 					 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 			  from( \n";
			strSql += " 				  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 				  from   t_pl_comp_plan_exec \n";
			strSql += " 				  where  comp_code =  ?  \n";
			strSql += " 				  and	 clse_acc_id =  ?  \n";
			strSql += " 				  and    substr(work_ym, 5,6) in ('10', '11', '12') \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		   substr(work_ym, 5,6)) \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b4, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt, \n";
			strSql += " 					 sum(forecast_amt) c_y_forecast_amt \n";
			strSql += " 			  from t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b5, \n";
			strSql += " 			  (select comp_code, clse_acc_id - 1 clse_acc_id,  biz_plan_item_no, n_y_plan_amt \n";
			strSql += " 			   from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				          sum(plan_amt) n_y_plan_amt \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  + 1 \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			  ) b6, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출이익') c \n";
			strSql += " 	  where   b5.comp_code = b1.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b3.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b4.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b6.comp_code(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b3.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b4.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b6.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b4.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b6.biz_plan_item_no(+) \n";
			strSql += " 	  and     c.biz_plan_item_no = b5.biz_plan_item_no(+) \n";
			strSql += " 	  --and     c.biz_plan_item_name = '매출이익' \n";
			strSql += " 	 ) b1 \n";
			strSql += "  \n";
			strSql += " 	 union all \n";
			strSql += "  \n";
			strSql += " 	 select \n";
			strSql += " 	  '12' div, \n";
			strSql += " 	  b1.p_no, \n";
			strSql += "       b1.biz_plan_item_no, \n";
			strSql += "       '(%)' biz_plan_item_name, \n";
			strSql += "       decode(a1.b_y_exec_amt, 0, 0, round((b1.b_y_exec_amt/a1.b_y_exec_amt)*100,1)) b_y_exec_amt, \n";
			strSql += " 	  decode(a1.b_y_exec_amt19, 0, 0, round((b1.b_y_exec_amt19/a1.b_y_exec_amt19)*100,1)) b_y_exec_amt19, \n";
			strSql += " 	  decode(a1.c_y_plan_amt19, 0, 0, round((b1.c_y_plan_amt19/a1.c_y_plan_amt19)*100,1)) c_y_plan_amt19, \n";
			strSql += " 	  decode(a1.c_y_exec_amt19, 0, 0, round((b1.c_y_exec_amt19/a1.c_y_exec_amt19)*100,1)) c_y_exec_amt19, \n";
			strSql += " 	  0 c_plan_rate19, \n";
			strSql += " 	  0 b_rate19, \n";
			strSql += " 	  decode(a1.plan_amt10, 0, 0, round((b1.plan_amt10/a1.plan_amt10)*100,1)) plan_amt10, \n";
			strSql += " 	  decode(a1.forecast_amt10, 0, 0, round((b1.forecast_amt10/a1.forecast_amt10)*100,1)) forecast_amt10, \n";
			strSql += " 	  decode(a1.plan_amt11, 0, 0, round((b1.plan_amt11/a1.plan_amt11)*100,1)) plan_amt11, \n";
			strSql += " 	  decode(a1.forecast_amt11, 0, 0, round((b1.forecast_amt11/a1.forecast_amt11)*100,1)) forecast_amt11, \n";
			strSql += " 	  decode(a1.plan_amt12, 0, 0, round((b1.plan_amt12/a1.plan_amt12)*100,1)) plan_amt12, \n";
			strSql += " 	  decode(a1.forecast_amt12, 0, 0, round((b1.forecast_amt12/a1.b_y_exec_amt)*100,1)) b_y_exec_amt, \n";
			strSql += " 	  decode(a1.c_y_plan_amt, 0, 0, round((b1.c_y_plan_amt/a1.c_y_plan_amt)*100,1)) c_y_plan_amt, \n";
			strSql += " 	  decode(a1.c_y_forecast_amt, 0, 0, round((b1.c_y_forecast_amt/a1.c_y_forecast_amt)*100,1)) c_y_forecast_amt, \n";
			strSql += " 	  0 c_plan_rate, \n";
			strSql += " 	  0 b_rate, \n";
			strSql += " 	  decode(a1.n_y_plan_amt, 0, 0, round((b1.n_y_plan_amt/a1.n_y_plan_amt)*100,1)) n_y_plan_amt, \n";
			strSql += " 	  0 n_rate \n";
			strSql += " from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b5.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round(b_y_exec_amt/1000000,0))  b_y_exec_amt, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0),0, 0, round(b_y_exec_amt19/1000000,0)) b_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round(c_y_plan_amt19/1000000,0)) c_y_plan_amt19, \n";
			strSql += " 	 		 decode(nvl(c_y_exec_amt19,0),0, 0, round(c_y_exec_amt19/1000000,0)) c_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round((nvl(c_y_exec_amt19,0)/nvl(c_y_plan_amt19,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0), 0, 0, round((nvl(c_y_exec_amt19,0)/nvl(b_y_exec_amt19,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10, \n";
			strSql += " 			 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 			 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11, \n";
			strSql += " 			 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 			 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 			 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0), 0, 0, round(c_y_plan_amt/1000000,0)) c_y_plan_amt, \n";
			strSql += " 			 decode(nvl(c_y_forecast_amt,0), 0, 0, round(c_y_forecast_amt/1000000,0)) c_y_forecast_amt, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0),0, 0, round((nvl(c_y_forecast_amt,0)/nvl(c_y_plan_amt,0))*100,1)) c_plan_rate, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round((nvl(c_y_forecast_amt,0)/nvl(b_y_exec_amt,0))*100,1)) b_rate, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0),0, 0,  round(n_y_plan_amt,0)) n_y_plan_amt, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0), 0, 0, round(((nvl(c_y_exec_amt19,0) + nvl(forecast_amt10,0) + nvl(forecast_amt11,0) + nvl(forecast_amt12,0))/nvl(n_y_plan_amt,0))*100,1)) n_rate \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id, \n";
			strSql += " 		 		  biz_plan_item_no,  b_y_exec_amt \n";
			strSql += " 			  from \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(exec_amt) b_y_exec_amt \n";
			strSql += " 				  from t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  - 1 \n";
			strSql += " 				  group by comp_code, clse_acc_id, biz_plan_item_no) \n";
			strSql += " 			  ) b1, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_amt19 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_amt19 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt19, \n";
			strSql += " 			 		 sum(exec_amt) c_y_exec_amt19 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and   substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			  		 sum(plan_amt10) plan_amt10, \n";
			strSql += " 					 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 					 sum(plan_amt11) plan_amt11, \n";
			strSql += " 					 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 					 sum(plan_amt12) plan_amt12, \n";
			strSql += " 					 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 			  from( \n";
			strSql += " 				  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 				  from   t_pl_comp_plan_exec \n";
			strSql += " 				  where  comp_code =  ?  \n";
			strSql += " 				  and	 clse_acc_id =  ?  \n";
			strSql += " 				  and    substr(work_ym, 5,6) in ('10', '11', '12') \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		   substr(work_ym, 5,6)) \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b4, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt, \n";
			strSql += " 					 sum(forecast_amt) c_y_forecast_amt \n";
			strSql += " 			  from t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b5, \n";
			strSql += " 			  (select comp_code, clse_acc_id - 1 clse_acc_id,  biz_plan_item_no, n_y_plan_amt \n";
			strSql += " 			   from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				          sum(plan_amt) n_y_plan_amt \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  + 1 \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			  ) b6, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b5.comp_code = b1.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b3.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b4.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b6.comp_code(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b3.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b4.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b6.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b4.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b6.biz_plan_item_no(+) \n";
			strSql += " 	  and     c.biz_plan_item_no = b5.biz_plan_item_no(+) \n";
			strSql += " 	  --and     c.biz_plan_item_name = '매출액' \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b5.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round(b_y_exec_amt/1000000,0))  b_y_exec_amt, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0),0, 0, round(b_y_exec_amt19/1000000,0)) b_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round(c_y_plan_amt19/1000000,0)) c_y_plan_amt19, \n";
			strSql += " 	 		 decode(nvl(c_y_exec_amt19,0),0, 0, round(c_y_exec_amt19/1000000,0)) c_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round((nvl(c_y_exec_amt19,0)/nvl(c_y_plan_amt19,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0), 0, 0, round((nvl(c_y_exec_amt19,0)/nvl(b_y_exec_amt19,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10, \n";
			strSql += " 			 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 			 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11, \n";
			strSql += " 			 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 			 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 			 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0), 0, 0, round(c_y_plan_amt/1000000,0)) c_y_plan_amt, \n";
			strSql += " 			 decode(nvl(c_y_forecast_amt,0), 0, 0, round(c_y_forecast_amt/1000000,0)) c_y_forecast_amt, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0),0, 0, round((nvl(c_y_forecast_amt,0)/nvl(c_y_plan_amt,0))*100,1)) c_plan_rate, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round((nvl(c_y_forecast_amt,0)/nvl(b_y_exec_amt,0))*100,1)) b_rate, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0),0, 0,  round(n_y_plan_amt,0)) n_y_plan_amt, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0), 0, 0, round(((nvl(c_y_exec_amt19,0) + nvl(forecast_amt10,0) + nvl(forecast_amt11,0) + nvl(forecast_amt12,0))/nvl(n_y_plan_amt,0))*100,1)) n_rate \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id, \n";
			strSql += " 		 		  biz_plan_item_no,  b_y_exec_amt \n";
			strSql += " 			  from \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(exec_amt) b_y_exec_amt \n";
			strSql += " 				  from t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  - 1 \n";
			strSql += " 				  group by comp_code, clse_acc_id, biz_plan_item_no) \n";
			strSql += " 			  ) b1, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_amt19 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_amt19 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt19, \n";
			strSql += " 			 		 sum(exec_amt) c_y_exec_amt19 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and   substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			  		 sum(plan_amt10) plan_amt10, \n";
			strSql += " 					 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 					 sum(plan_amt11) plan_amt11, \n";
			strSql += " 					 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 					 sum(plan_amt12) plan_amt12, \n";
			strSql += " 					 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 			  from( \n";
			strSql += " 				  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 				  from   t_pl_comp_plan_exec \n";
			strSql += " 				  where  comp_code =  ?  \n";
			strSql += " 				  and	 clse_acc_id =  ?  \n";
			strSql += " 				  and    substr(work_ym, 5,6) in ('10', '11', '12') \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		   substr(work_ym, 5,6)) \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b4, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt, \n";
			strSql += " 					 sum(forecast_amt) c_y_forecast_amt \n";
			strSql += " 			  from t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b5, \n";
			strSql += " 			  (select comp_code, clse_acc_id - 1 clse_acc_id,  biz_plan_item_no, n_y_plan_amt \n";
			strSql += " 			   from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				          sum(plan_amt) n_y_plan_amt \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  + 1 \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			  ) b6, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '영업이익') c \n";
			strSql += " 	  where   b5.comp_code = b1.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b3.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b4.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b6.comp_code(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b3.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b4.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b6.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b4.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b6.biz_plan_item_no(+) \n";
			strSql += " 	  and     c.biz_plan_item_no = b5.biz_plan_item_no(+) \n";
			strSql += " 	  --and     c.biz_plan_item_name = '영업이익' \n";
			strSql += " 	 ) b1 \n";
			strSql += "  \n";
			strSql += " 	 union all \n";
			strSql += "  \n";
			strSql += " 	 select \n";
			strSql += " 	  '12' div, \n";
			strSql += " 	  b1.p_no, \n";
			strSql += "       b1.biz_plan_item_no, \n";
			strSql += "       '(%)' biz_plan_item_name, \n";
			strSql += "       decode(a1.b_y_exec_amt, 0, 0, round((b1.b_y_exec_amt/a1.b_y_exec_amt)*100,1)) b_y_exec_amt, \n";
			strSql += " 	  decode(a1.b_y_exec_amt19, 0, 0, round((b1.b_y_exec_amt19/a1.b_y_exec_amt19)*100,1)) b_y_exec_amt19, \n";
			strSql += " 	  decode(a1.c_y_plan_amt19, 0, 0, round((b1.c_y_plan_amt19/a1.c_y_plan_amt19)*100,1)) c_y_plan_amt19, \n";
			strSql += " 	  decode(a1.c_y_exec_amt19, 0, 0, round((b1.c_y_exec_amt19/a1.c_y_exec_amt19)*100,1)) c_y_exec_amt19, \n";
			strSql += " 	  0 c_plan_rate19, \n";
			strSql += " 	  0 b_rate19, \n";
			strSql += " 	  decode(a1.plan_amt10, 0, 0, round((b1.plan_amt10/a1.plan_amt10)*100,1)) plan_amt10, \n";
			strSql += " 	  decode(a1.forecast_amt10, 0, 0, round((b1.forecast_amt10/a1.forecast_amt10)*100,1)) forecast_amt10, \n";
			strSql += " 	  decode(a1.plan_amt11, 0, 0, round((b1.plan_amt11/a1.plan_amt11)*100,1)) plan_amt11, \n";
			strSql += " 	  decode(a1.forecast_amt11, 0, 0, round((b1.forecast_amt11/a1.forecast_amt11)*100,1)) forecast_amt11, \n";
			strSql += " 	  decode(a1.plan_amt12, 0, 0, round((b1.plan_amt12/a1.plan_amt12)*100,1)) plan_amt12, \n";
			strSql += " 	  decode(a1.forecast_amt12, 0, 0, round((b1.forecast_amt12/a1.b_y_exec_amt)*100,1)) b_y_exec_amt, \n";
			strSql += " 	  decode(a1.c_y_plan_amt, 0, 0, round((b1.c_y_plan_amt/a1.c_y_plan_amt)*100,1)) c_y_plan_amt, \n";
			strSql += " 	  decode(a1.c_y_forecast_amt, 0, 0, round((b1.c_y_forecast_amt/a1.c_y_forecast_amt)*100,1)) c_y_forecast_amt, \n";
			strSql += " 	  0 c_plan_rate, \n";
			strSql += " 	  0 b_rate, \n";
			strSql += " 	  decode(a1.n_y_plan_amt, 0, 0, round((b1.n_y_plan_amt/a1.n_y_plan_amt)*100,1)) n_y_plan_amt, \n";
			strSql += " 	  0 n_rate \n";
			strSql += " from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b5.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round(b_y_exec_amt/1000000,0))  b_y_exec_amt, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0),0, 0, round(b_y_exec_amt19/1000000,0)) b_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round(c_y_plan_amt19/1000000,0)) c_y_plan_amt19, \n";
			strSql += " 	 		 decode(nvl(c_y_exec_amt19,0),0, 0, round(c_y_exec_amt19/1000000,0)) c_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round((nvl(c_y_exec_amt19,0)/nvl(c_y_plan_amt19,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0), 0, 0, round((nvl(c_y_exec_amt19,0)/nvl(b_y_exec_amt19,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10, \n";
			strSql += " 			 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 			 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11, \n";
			strSql += " 			 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 			 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 			 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0), 0, 0, round(c_y_plan_amt/1000000,0)) c_y_plan_amt, \n";
			strSql += " 			 decode(nvl(c_y_forecast_amt,0), 0, 0, round(c_y_forecast_amt/1000000,0)) c_y_forecast_amt, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0),0, 0, round((nvl(c_y_forecast_amt,0)/nvl(c_y_plan_amt,0))*100,1)) c_plan_rate, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round((nvl(c_y_forecast_amt,0)/nvl(b_y_exec_amt,0))*100,1)) b_rate, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0),0, 0,  round(n_y_plan_amt,0)) n_y_plan_amt, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0), 0, 0, round(((nvl(c_y_exec_amt19,0) + nvl(forecast_amt10,0) + nvl(forecast_amt11,0) + nvl(forecast_amt12,0))/nvl(n_y_plan_amt,0))*100,1)) n_rate \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id, \n";
			strSql += " 		 		  biz_plan_item_no,  b_y_exec_amt \n";
			strSql += " 			  from \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(exec_amt) b_y_exec_amt \n";
			strSql += " 				  from t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  - 1 \n";
			strSql += " 				  group by comp_code, clse_acc_id, biz_plan_item_no) \n";
			strSql += " 			  ) b1, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_amt19 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_amt19 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt19, \n";
			strSql += " 			 		 sum(exec_amt) c_y_exec_amt19 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and   substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			  		 sum(plan_amt10) plan_amt10, \n";
			strSql += " 					 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 					 sum(plan_amt11) plan_amt11, \n";
			strSql += " 					 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 					 sum(plan_amt12) plan_amt12, \n";
			strSql += " 					 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 			  from( \n";
			strSql += " 				  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 				  from   t_pl_comp_plan_exec \n";
			strSql += " 				  where  comp_code =  ?  \n";
			strSql += " 				  and	 clse_acc_id =  ?  \n";
			strSql += " 				  and    substr(work_ym, 5,6) in ('10', '11', '12') \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		   substr(work_ym, 5,6)) \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b4, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt, \n";
			strSql += " 					 sum(forecast_amt) c_y_forecast_amt \n";
			strSql += " 			  from t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b5, \n";
			strSql += " 			  (select comp_code, clse_acc_id - 1 clse_acc_id,  biz_plan_item_no, n_y_plan_amt \n";
			strSql += " 			   from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				          sum(plan_amt) n_y_plan_amt \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  + 1 \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			  ) b6, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b5.comp_code = b1.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b3.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b4.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b6.comp_code(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b3.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b4.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b6.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b4.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b6.biz_plan_item_no(+) \n";
			strSql += " 	  and     c.biz_plan_item_no = b5.biz_plan_item_no(+) \n";
			strSql += " 	  --and     c.biz_plan_item_name = '매출액' \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b5.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round(b_y_exec_amt/1000000,0))  b_y_exec_amt, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0),0, 0, round(b_y_exec_amt19/1000000,0)) b_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round(c_y_plan_amt19/1000000,0)) c_y_plan_amt19, \n";
			strSql += " 	 		 decode(nvl(c_y_exec_amt19,0),0, 0, round(c_y_exec_amt19/1000000,0)) c_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round((nvl(c_y_exec_amt19,0)/nvl(c_y_plan_amt19,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0), 0, 0, round((nvl(c_y_exec_amt19,0)/nvl(b_y_exec_amt19,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10, \n";
			strSql += " 			 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 			 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11, \n";
			strSql += " 			 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 			 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 			 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0), 0, 0, round(c_y_plan_amt/1000000,0)) c_y_plan_amt, \n";
			strSql += " 			 decode(nvl(c_y_forecast_amt,0), 0, 0, round(c_y_forecast_amt/1000000,0)) c_y_forecast_amt, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0),0, 0, round((nvl(c_y_forecast_amt,0)/nvl(c_y_plan_amt,0))*100,1)) c_plan_rate, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round((nvl(c_y_forecast_amt,0)/nvl(b_y_exec_amt,0))*100,1)) b_rate, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0),0, 0,  round(n_y_plan_amt,0)) n_y_plan_amt, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0), 0, 0, round(((nvl(c_y_exec_amt19,0) + nvl(forecast_amt10,0) + nvl(forecast_amt11,0) + nvl(forecast_amt12,0))/nvl(n_y_plan_amt,0))*100,1)) n_rate \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id, \n";
			strSql += " 		 		  biz_plan_item_no,  b_y_exec_amt \n";
			strSql += " 			  from \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(exec_amt) b_y_exec_amt \n";
			strSql += " 				  from t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  - 1 \n";
			strSql += " 				  group by comp_code, clse_acc_id, biz_plan_item_no) \n";
			strSql += " 			  ) b1, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_amt19 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_amt19 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt19, \n";
			strSql += " 			 		 sum(exec_amt) c_y_exec_amt19 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and   substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			  		 sum(plan_amt10) plan_amt10, \n";
			strSql += " 					 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 					 sum(plan_amt11) plan_amt11, \n";
			strSql += " 					 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 					 sum(plan_amt12) plan_amt12, \n";
			strSql += " 					 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 			  from( \n";
			strSql += " 				  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 				  from   t_pl_comp_plan_exec \n";
			strSql += " 				  where  comp_code =  ?  \n";
			strSql += " 				  and	 clse_acc_id =  ?  \n";
			strSql += " 				  and    substr(work_ym, 5,6) in ('10', '11', '12') \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		   substr(work_ym, 5,6)) \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b4, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt, \n";
			strSql += " 					 sum(forecast_amt) c_y_forecast_amt \n";
			strSql += " 			  from t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b5, \n";
			strSql += " 			  (select comp_code, clse_acc_id - 1 clse_acc_id,  biz_plan_item_no, n_y_plan_amt \n";
			strSql += " 			   from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				          sum(plan_amt) n_y_plan_amt \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  + 1 \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			  ) b6, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '경상이익') c \n";
			strSql += " 	  where   b5.comp_code = b1.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b3.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b4.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b6.comp_code(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b3.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b4.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b6.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b4.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b6.biz_plan_item_no(+) \n";
			strSql += " 	  and     c.biz_plan_item_no = b5.biz_plan_item_no(+) \n";
			strSql += " 	  --and     c.biz_plan_item_name = '경상이익' \n";
			strSql += " 	 ) b1 \n";
			strSql += "  \n";
			strSql += " 	 union all \n";
			strSql += "  \n";
			strSql += " 	 select \n";
			strSql += " 	  '12' div, \n";
			strSql += " 	  b1.p_no, \n";
			strSql += "       b1.biz_plan_item_no, \n";
			strSql += "       '(%)' biz_plan_item_name, \n";
			strSql += "       decode(a1.b_y_exec_amt, 0, 0, round((b1.b_y_exec_amt/a1.b_y_exec_amt)*100,1)) b_y_exec_amt, \n";
			strSql += " 	  decode(a1.b_y_exec_amt19, 0, 0, round((b1.b_y_exec_amt19/a1.b_y_exec_amt19)*100,1)) b_y_exec_amt19, \n";
			strSql += " 	  decode(a1.c_y_plan_amt19, 0, 0, round((b1.c_y_plan_amt19/a1.c_y_plan_amt19)*100,1)) c_y_plan_amt19, \n";
			strSql += " 	  decode(a1.c_y_exec_amt19, 0, 0, round((b1.c_y_exec_amt19/a1.c_y_exec_amt19)*100,1)) c_y_exec_amt19, \n";
			strSql += " 	  0 c_plan_rate19, \n";
			strSql += " 	  0 b_rate19, \n";
			strSql += " 	  decode(a1.plan_amt10, 0, 0, round((b1.plan_amt10/a1.plan_amt10)*100,1)) plan_amt10, \n";
			strSql += " 	  decode(a1.forecast_amt10, 0, 0, round((b1.forecast_amt10/a1.forecast_amt10)*100,1)) forecast_amt10, \n";
			strSql += " 	  decode(a1.plan_amt11, 0, 0, round((b1.plan_amt11/a1.plan_amt11)*100,1)) plan_amt11, \n";
			strSql += " 	  decode(a1.forecast_amt11, 0, 0, round((b1.forecast_amt11/a1.forecast_amt11)*100,1)) forecast_amt11, \n";
			strSql += " 	  decode(a1.plan_amt12, 0, 0, round((b1.plan_amt12/a1.plan_amt12)*100,1)) plan_amt12, \n";
			strSql += " 	  decode(a1.forecast_amt12, 0, 0, round((b1.forecast_amt12/a1.b_y_exec_amt)*100,1)) b_y_exec_amt, \n";
			strSql += " 	  decode(a1.c_y_plan_amt, 0, 0, round((b1.c_y_plan_amt/a1.c_y_plan_amt)*100,1)) c_y_plan_amt, \n";
			strSql += " 	  decode(a1.c_y_forecast_amt, 0, 0, round((b1.c_y_forecast_amt/a1.c_y_forecast_amt)*100,1)) c_y_forecast_amt, \n";
			strSql += " 	  0 c_plan_rate, \n";
			strSql += " 	  0 b_rate, \n";
			strSql += " 	  decode(a1.n_y_plan_amt, 0, 0, round((b1.n_y_plan_amt/a1.n_y_plan_amt)*100,1)) n_y_plan_amt, \n";
			strSql += " 	  0 n_rate \n";
			strSql += " from \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b5.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round(b_y_exec_amt/1000000,0))  b_y_exec_amt, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0),0, 0, round(b_y_exec_amt19/1000000,0)) b_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round(c_y_plan_amt19/1000000,0)) c_y_plan_amt19, \n";
			strSql += " 	 		 decode(nvl(c_y_exec_amt19,0),0, 0, round(c_y_exec_amt19/1000000,0)) c_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round((nvl(c_y_exec_amt19,0)/nvl(c_y_plan_amt19,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0), 0, 0, round((nvl(c_y_exec_amt19,0)/nvl(b_y_exec_amt19,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10, \n";
			strSql += " 			 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 			 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11, \n";
			strSql += " 			 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 			 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 			 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0), 0, 0, round(c_y_plan_amt/1000000,0)) c_y_plan_amt, \n";
			strSql += " 			 decode(nvl(c_y_forecast_amt,0), 0, 0, round(c_y_forecast_amt/1000000,0)) c_y_forecast_amt, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0),0, 0, round((nvl(c_y_forecast_amt,0)/nvl(c_y_plan_amt,0))*100,1)) c_plan_rate, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round((nvl(c_y_forecast_amt,0)/nvl(b_y_exec_amt,0))*100,1)) b_rate, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0),0, 0,  round(n_y_plan_amt,0)) n_y_plan_amt, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0), 0, 0, round(((nvl(c_y_exec_amt19,0) + nvl(forecast_amt10,0) + nvl(forecast_amt11,0) + nvl(forecast_amt12,0))/nvl(n_y_plan_amt,0))*100,1)) n_rate \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id, \n";
			strSql += " 		 		  biz_plan_item_no,  b_y_exec_amt \n";
			strSql += " 			  from \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(exec_amt) b_y_exec_amt \n";
			strSql += " 				  from t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  - 1 \n";
			strSql += " 				  group by comp_code, clse_acc_id, biz_plan_item_no) \n";
			strSql += " 			  ) b1, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_amt19 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_amt19 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt19, \n";
			strSql += " 			 		 sum(exec_amt) c_y_exec_amt19 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and   substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			  		 sum(plan_amt10) plan_amt10, \n";
			strSql += " 					 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 					 sum(plan_amt11) plan_amt11, \n";
			strSql += " 					 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 					 sum(plan_amt12) plan_amt12, \n";
			strSql += " 					 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 			  from( \n";
			strSql += " 				  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 				  from   t_pl_comp_plan_exec \n";
			strSql += " 				  where  comp_code =  ?  \n";
			strSql += " 				  and	 clse_acc_id =  ?  \n";
			strSql += " 				  and    substr(work_ym, 5,6) in ('10', '11', '12') \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		   substr(work_ym, 5,6)) \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b4, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt, \n";
			strSql += " 					 sum(forecast_amt) c_y_forecast_amt \n";
			strSql += " 			  from t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b5, \n";
			strSql += " 			  (select comp_code, clse_acc_id - 1 clse_acc_id,  biz_plan_item_no, n_y_plan_amt \n";
			strSql += " 			   from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				          sum(plan_amt) n_y_plan_amt \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  + 1 \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			  ) b6, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '매출액') c \n";
			strSql += " 	  where   b5.comp_code = b1.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b3.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b4.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b6.comp_code(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b3.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b4.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b6.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b4.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b6.biz_plan_item_no(+) \n";
			strSql += " 	  and     c.biz_plan_item_no = b5.biz_plan_item_no(+) \n";
			strSql += " 	  --and     c.biz_plan_item_name = '매출액' \n";
			strSql += " 	 ) a1, \n";
			strSql += " 	 ( \n";
			strSql += " 	   select \n";
			strSql += " 			 p_no, \n";
			strSql += " 			 b5.biz_plan_item_no, \n";
			strSql += " 			 biz_plan_item_name, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round(b_y_exec_amt/1000000,0))  b_y_exec_amt, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0),0, 0, round(b_y_exec_amt19/1000000,0)) b_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round(c_y_plan_amt19/1000000,0)) c_y_plan_amt19, \n";
			strSql += " 	 		 decode(nvl(c_y_exec_amt19,0),0, 0, round(c_y_exec_amt19/1000000,0)) c_y_exec_amt19, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt19,0),0, 0, round((nvl(c_y_exec_amt19,0)/nvl(c_y_plan_amt19,0))*100,1)) c_plan_rate19, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt19,0), 0, 0, round((nvl(c_y_exec_amt19,0)/nvl(b_y_exec_amt19,0))*100,1)) b_rate19, \n";
			strSql += " 			 decode(nvl(plan_amt10,0), 0, 0, round(plan_amt10/1000000,0)) plan_amt10, \n";
			strSql += " 			 decode(nvl(forecast_amt10,0), 0, 0, round(forecast_amt10/1000000,0)) forecast_amt10, \n";
			strSql += " 			 decode(nvl(plan_amt11,0), 0, 0, round(plan_amt11/1000000,0)) plan_amt11, \n";
			strSql += " 			 decode(nvl(forecast_amt11,0), 0, 0, round(forecast_amt11/1000000,0)) forecast_amt11, \n";
			strSql += " 			 decode(nvl(plan_amt12,0), 0, 0, round(plan_amt12/1000000,0)) plan_amt12, \n";
			strSql += " 			 decode(nvl(forecast_amt12,0), 0, 0, round(forecast_amt12/1000000,0)) forecast_amt12, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0), 0, 0, round(c_y_plan_amt/1000000,0)) c_y_plan_amt, \n";
			strSql += " 			 decode(nvl(c_y_forecast_amt,0), 0, 0, round(c_y_forecast_amt/1000000,0)) c_y_forecast_amt, \n";
			strSql += " 			 decode(nvl(c_y_plan_amt,0),0, 0, round((nvl(c_y_forecast_amt,0)/nvl(c_y_plan_amt,0))*100,1)) c_plan_rate, \n";
			strSql += " 			 decode(nvl(b_y_exec_amt,0), 0, 0, round((nvl(c_y_forecast_amt,0)/nvl(b_y_exec_amt,0))*100,1)) b_rate, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0),0, 0,  round(n_y_plan_amt,0)) n_y_plan_amt, \n";
			strSql += " 			 decode(nvl(n_y_plan_amt,0), 0, 0, round(((nvl(c_y_exec_amt19,0) + nvl(forecast_amt10,0) + nvl(forecast_amt11,0) + nvl(forecast_amt12,0))/nvl(n_y_plan_amt,0))*100,1)) n_rate \n";
			strSql += " 	  from \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id, \n";
			strSql += " 		 		  biz_plan_item_no,  b_y_exec_amt \n";
			strSql += " 			  from \n";
			strSql += " 				 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		 sum(exec_amt) b_y_exec_amt \n";
			strSql += " 				  from t_pl_comp_plan_exec \n";
			strSql += " 				  where comp_code =  ?  \n";
			strSql += " 				  and	clse_acc_id =  ?  - 1 \n";
			strSql += " 				  group by comp_code, clse_acc_id, biz_plan_item_no) \n";
			strSql += " 			  ) b1, \n";
			strSql += " 			 (select comp_code, clse_acc_id + 1 clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		  b_y_exec_amt19 \n";
			strSql += " 			  from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				 		  sum(exec_amt) b_y_exec_amt19 \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code   =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  - 1 \n";
			strSql += " 				   and    substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			 ) b2, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt19, \n";
			strSql += " 			 		 sum(exec_amt) c_y_exec_amt19 \n";
			strSql += " 			  from  t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  and   substr(work_ym, 5,6) in ('01', '02', '03','04','05','06','07','08','09') \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			 ) b3, \n";
			strSql += " 			  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			  		 sum(plan_amt10) plan_amt10, \n";
			strSql += " 					 sum(forecast_amt10) forecast_amt10, \n";
			strSql += " 					 sum(plan_amt11) plan_amt11, \n";
			strSql += " 					 sum(forecast_amt11) forecast_amt11, \n";
			strSql += " 					 sum(plan_amt12) plan_amt12, \n";
			strSql += " 					 sum(forecast_amt12) forecast_amt12 \n";
			strSql += " 			  from( \n";
			strSql += " 				  select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(plan_amt), '') 	   plan_amt10, \n";
			strSql += " 				  		 decode(substr(work_ym, 5,6) ,'10', sum(forecast_amt), '') forecast_amt10, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(plan_amt), '') 	   plan_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'11', sum(forecast_amt), '') forecast_amt11, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(plan_amt), '') 	   plan_amt12, \n";
			strSql += " 						 decode(substr(work_ym, 5,6) ,'12', sum(forecast_amt), '') forecast_amt12 \n";
			strSql += " 				  from   t_pl_comp_plan_exec \n";
			strSql += " 				  where  comp_code =  ?  \n";
			strSql += " 				  and	 clse_acc_id =  ?  \n";
			strSql += " 				  and    substr(work_ym, 5,6) in ('10', '11', '12') \n";
			strSql += " 				  group by comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				  		   substr(work_ym, 5,6)) \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b4, \n";
			strSql += " 			 (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 			 		 sum(plan_amt) c_y_plan_amt, \n";
			strSql += " 					 sum(forecast_amt) c_y_forecast_amt \n";
			strSql += " 			  from t_pl_comp_plan_exec \n";
			strSql += " 			  where comp_code =  ?  \n";
			strSql += " 			  and	clse_acc_id =  ?  \n";
			strSql += " 			  group by comp_code, clse_acc_id,  biz_plan_item_no \n";
			strSql += " 			  ) b5, \n";
			strSql += " 			  (select comp_code, clse_acc_id - 1 clse_acc_id,  biz_plan_item_no, n_y_plan_amt \n";
			strSql += " 			   from \n";
			strSql += " 				  (select comp_code, clse_acc_id,  biz_plan_item_no, \n";
			strSql += " 				          sum(plan_amt) n_y_plan_amt \n";
			strSql += " 				   from   t_pl_comp_plan_exec \n";
			strSql += " 				   where  comp_code =  ?  \n";
			strSql += " 				   and	  clse_acc_id =  ?  + 1 \n";
			strSql += " 				   group by comp_code, clse_acc_id,  biz_plan_item_no) \n";
			strSql += " 			  ) b6, \n";
			strSql += " 			  (select * \n";
			strSql += " 			   from t_pl_item \n";
			strSql += " 			   where biz_plan_item_name = '세전이익') c \n";
			strSql += " 	  where   b5.comp_code = b1.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b2.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b3.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b4.comp_code(+) \n";
			strSql += " 	  and	  b5.comp_code = b6.comp_code(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b1.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b2.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b3.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b4.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.clse_acc_id = b6.clse_acc_id(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b1.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b2.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b3.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b4.biz_plan_item_no(+) \n";
			strSql += " 	  and	  b5.biz_plan_item_no = b6.biz_plan_item_no(+) \n";
			strSql += " 	  and     c.biz_plan_item_no = b5.biz_plan_item_no(+) \n";
			strSql += " 	 ) b1 \n";
			strSql += " 	 \n";
			strSql += " 	)	a, \n";
			strSql += " 	(select * \n";
			strSql += " 	from t_pl_item \n";
			strSql += " 	where level_tag in ('1','2')) b \n";
			strSql += " where b.biz_plan_item_no = a.biz_plan_item_no(+)					 \n";
			strSql += " start with a.p_no = '0' \n";
			strSql += " connect by prior a.biz_plan_item_no = a.p_no \n";
			strSql += " order siblings by item_level_seq ";
			
			lrArgData.addColumn("1COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("2CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("3COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("4CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("5COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("6CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("7COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("8CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("9COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("10CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("11COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("12CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("13COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("14CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("15COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("16CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("17COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("18CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("19COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("20CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("21COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("22CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("23COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("24CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("25COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("26CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("27COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("28CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("29COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("30CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("31COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("32CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("33COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("34CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("35COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("36CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("37COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("38CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("39COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("40CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("41COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("42CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("43COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("44CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("45COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("46CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("47COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("48CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("49COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("50CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("51COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("52CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("53COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("54CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("55COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("56CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("57COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("58CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("59COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("60CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("61COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("62CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("63COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("64CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("65COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("66CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("67COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("68CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("69COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("70CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("71COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("72CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("73COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("74CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("75COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("76CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("77COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("78CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("79COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("80CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("81COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("82CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("83COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("84CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("85COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("86CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("87COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("88CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("89COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("90CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("91COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("92CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("93COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("94CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("95COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("96CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("97COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("98CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("99COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("100CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("101COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("102CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("103COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("104CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("105COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("106CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addColumn("107COMP_CODE", CITData.VARCHAR2);
			lrArgData.addColumn("108CLSE_ACC_ID", CITData.VARCHAR2);
			lrArgData.addRow();
			lrArgData.setValue("1COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("2CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("3COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("4CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("5COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("6CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("7COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("8CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("9COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("10CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("11COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("12CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("13COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("14CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("15COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("16CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("17COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("18CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("19COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("20CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("21COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("22CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("23COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("24CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("25COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("26CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("27COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("28CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("29COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("30CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("31COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("32CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("33COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("34CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("35COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("36CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("37COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("38CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("39COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("40CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("41COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("42CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("43COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("44CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("45COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("46CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("47COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("48CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("49COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("50CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("51COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("52CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("53COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("54CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("55COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("56CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("57COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("58CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("59COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("60CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("61COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("62CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("63COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("64CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("65COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("66CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("67COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("68CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("69COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("70CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("71COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("72CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("73COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("74CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("75COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("76CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("77COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("78CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("79COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("80CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("81COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("82CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("83COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("84CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("85COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("86CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("87COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("88CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("89COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("90CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("91COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("92CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("93COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("94CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("95COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("96CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("97COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("98CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("99COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("100CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("101COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("102CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("103COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("104CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("105COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("106CLSE_ACC_ID", strCLSE_ACC_ID);
			lrArgData.setValue("107COMP_CODE", strCOMP_CODE);
			lrArgData.setValue("108CLSE_ACC_ID", strCLSE_ACC_ID);
			try
			{
				lrReturnData = CITDatabase.selectQuery(strSql, lrArgData);
				


				
				lrDataset = CITCommon.toGauceDataSet(lrReturnData);
				GauceInfo.response.enableFirstRow(lrDataset);
				lrDataset.flush();
			}
			catch (Exception ex)
			{
				if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
				GauceInfo.response.writeException("USER", "900001","MAIN Select 오류-> "+ ex.getMessage());
			}
		}
		else if (strAct.equals("COPY"))
		{

			
			strSql  = " select '######' comp_code, \n";
			strSql += " 	   '######' clse_acc_id, \n";
			strSql += " 	   '######' dept_code, \n";
			strSql += " 	   '######' month, \n";
			strSql += " 	   '######' b_clse_acc_id, \n";
			strSql += " 	   '######' n_clse_acc_id, \n";
			strSql += " 	   '######' emp_no \n";
			strSql += " from dual ";
			

			try
			{
				lrReturnData = CITDatabase.selectQuery(strSql, lrArgData);
				


				
				lrDataset = CITCommon.toGauceDataSet(lrReturnData);
				GauceInfo.response.enableFirstRow(lrDataset);
				lrDataset.flush();
			}
			catch (Exception ex)
			{
				if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
				GauceInfo.response.writeException("USER", "900001","COPY Select 오류-> "+ ex.getMessage());
			}
		}
		
	}
	catch (Exception ex)
	{
		if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
		GauceInfo.response.writeException("SYS", "100001", "페이지 초기화 오류 -> " + ex.getMessage());
	}
	finally
	{
		try
		{
			CITCommon.finalServerPage(GauceInfo);
		}
		catch (Exception ex)
		{
			if (GauceInfo == null) GauceInfo = new CITGauceInfo(request, response);
			GauceInfo.response.writeException("SYS", "100002", "페이지 종료 오류 -> " + ex.getMessage());
		}
	}
%>