--»ðÀÔSQL
insert into t_income_list
(
	CUSTCODE,
	SEQ,
	SPECIALTAG,
	COUNTS,
	TIMES,
	PROJ_CODE,
	HOUSETAG,
	CRTUSERNO,
	CRTDATE,
	MODUSERNO,
	MODDATE,
	DEPOSITNO,
	RECEIPTDATE,
	RECEIPTAMT,
	RECEIPTLANDAMT,
	RECEIPTBUILDAMT,
	RECEIPTVATAMT,
	DELAYDAYS,
	DELAYAMT,
	PAYTAG,
	DISCNTDAYS,
	DISCNTAMT,
	REFUNDMENTAMT,
	PENALTYAMT,
	BANKNAME,
	INCOMETAG,
	SLIP_ID,
	PAYMENTDATE,
	PAYMENTSEQ
)
Select
	a.CUSTCODE CUSTCODE,
	a.SEQ SEQ,
	'1' SPECIALTAG,
	a.COUNTS COUNTS,
	a.TIMES TIMES,
	a.PROJ_CODE PROJ_CODE,
	'1' HOUSETAG,
	0 CRTUSERNO,
	Sysdate CRTDATE,
	Null MODUSERNO,
	Null MODDATE,
	c.DEPOSITNO DEPOSITNO,
	a.INCOMEDATE RECEIPTDATE,
	a.INCOMEAMT RECEIPTAMT,
	Nvl(a.INCOMEAMT * (b.LANDAMT/nullif(nvl(b.LANDAMT,0) + nvl(b.BUILDAMT,0) + nvl(b.VATAMT,0),0)   ),0) RECEIPTLANDAMT,
	Nvl(a.INCOMEAMT * (b.LANDAMT/nullif(nvl(b.BUILDAMT,0) + nvl(b.BUILDAMT,0) + nvl(b.VATAMT,0),0)   ),0) RECEIPTBUILDAMT,
	Nvl(a.INCOMEAMT * (b.LANDAMT/nullif(nvl(b.VATAMT,0) + nvl(b.BUILDAMT,0) + nvl(b.VATAMT,0),0)   ),0) RECEIPTVATAMT,
	a.DELAYDAY DELAYDAYS,
	a.DELAYAMT DELAYAMT,
	'1' PAYTAG,
	a.DISDAY DISCNTDAYS,
	a.DISAMT DISCNTAMT,
	0 REFUNDMENTAMT,
	0 PENALTYAMT,
	c.BANKNAME BANKNAME,
	null INCOMETAG,
	Null SLIP_ID,
	c.PAYMENTDATE PAYMENTDATE,
	c.PAYMENTSEQ PAYMENTSEQ
From	t_income a,
		THS_HOUS_SELLDETAIL b,
		t_income_src c
Where	a.CUSTCODE = b.CUSTCODE
And		a.SEQ = b.SEQ
And		a.COUNTS = b.COUNTS
And		b.SPECIALTAG = '1'
And		a.INCOMEDATE = c.PAYMENTDATE
And		a.PAYMENTSEQ = c.PAYMENTSEQ