CREATE OR REPLACE VIEW T_LOG_ACC_SLIP_VIEW
(LOG_ID, UPDATE_CLS, LOG_CRTUSERNO, LOG_CRTDATE, SLIP_ID, 
 MODUSERNO, MODUSER_NAME, SLIP_IDSEQ, MAKE_SLIPLINE, MAKE_SLIPCLS, 
 MAKE_SLIPCLS_NAME, MAKE_SLIPNO, MAKE_COMP_CODE, MAKE_COMP_NAME, MAKE_DEPT_CODE, 
 MAKE_DEPT_NAME, MAKE_DT, MAKE_DT_TRANS, MAKE_SEQ, INOUT_DEPT_CODE, 
 INOUT_DEPT_NAME, MAKE_PERS, MAKE_NAME, GROUPWARE_SLIPSTATUS, KEEP_CLS, 
 KEEP_SLIPNO, KEEP_DT, KEEP_DT_TRANS, KEEP_SEQ, KEEP_DEPT_CODE, 
 KEEP_DEPT_NAME, KEEP_KEEPER, WORK_CODE, WORK_NAME, CHARGE_PERS, 
 CHARGE_PERS_NAME, SLIP_KIND_TAG, SLIP_KIND_NAME, TRANSFER_TAG, IGNORE_SET_RESET_TAG, 
 SLIP_UPDATE_CLS, ACC_CODE, ACC_NAME, ACC_REMAIN_POSITION, DB_AMT, 
 CR_AMT, SUMMARY_CODE, TAX_COMP_CODE, TAX_COMP_NAME, COMP_CODE, 
 COMP_NAME, DEPT_CODE, DEPT_NAME, CLASS_CODE, CLASS_CODE_NAME, 
 VAT_CODE, VAT_NAME, VAT_DT, SUPAMT, VATAMT, 
 CUST_SEQ, CUST_CODE, CUST_NAME, BANK_CODE, BANK_NAME, 
 ACCNO, RESET_SLIP_ID, RESET_SLIP_IDSEQ, SUMMARY1, SUMMARY2, 
 CHK_NO, BILL_NO, REC_BILL_NO, CP_NO, SECU_NO, 
 LOAN_NO, LOAN_REFUND_NO, LOAN_REFUND_SEQ, DEPOSIT_ACCNO, PAYMENT_SEQ, 
 PAY_CON_CASH, PAY_CON_BILL, PAY_CON_BILL_DT, PAY_CON_BILL_DAYS, EMP_NO, 
 EMP_NAME, ANTICIPATION_DT, MNG_ITEM_CHAR1, MNG_ITEM_CHAR2, MNG_ITEM_CHAR3, 
 MNG_ITEM_CHAR4, MNG_ITEM_NUM1, MNG_ITEM_NUM2, MNG_ITEM_NUM3, MNG_ITEM_NUM4, 
 MNG_ITEM_DT1, MNG_ITEM_DT2, MNG_ITEM_DT3, MNG_ITEM_DT4)
AS 
SELECT
	A.LOG_ID,
	A.UPDATE_CLS,
	A.LOG_CRTUSERNO,
	A.LOG_CRTDATE,
	A.SLIP_ID ,
	A.MODUSERNO,
	H01.NAME MODUSER_NAME ,
	bb1.SLIP_IDSEQ ,
	bb1.MAKE_SLIPLINE ,
	A.MAKE_SLIPCLS ,
	J.CODE_LIST_NAME MAKE_SLIPCLS_NAME,
	A.MAKE_SLIPNO ,
	A.MAKE_COMP_CODE ,
	C.COMPANY_NAME MAKE_COMP_NAME,
	A.MAKE_DEPT_CODE ,
	D.DEPT_NAME MAKE_DEPT_NAME ,
	A.MAKE_DT ,
	A.MAKE_DT_TRANS ,
	A.MAKE_SEQ ,
	A.INOUT_DEPT_CODE ,
	E.DEPT_NAME  INOUT_DEPT_NAME ,
	A.MAKE_PERS ,
	A.MAKE_NAME ,
	A.GROUPWARE_SLIPSTATUS ,
	DECODE(A.KEEP_SLIPNO, NULL, 'F', 'T') KEEP_CLS,
	A.KEEP_SLIPNO ,
	A.KEEP_DT ,
	A.KEEP_DT_TRANS ,
	A.KEEP_SEQ ,
	A.KEEP_DEPT_CODE ,
	F.DEPT_NAME KEEP_DEPT_NAME ,
	A.KEEP_KEEPER ,
	A.WORK_CODE ,
	G.WORK_NAME ,
	A.CHARGE_PERS ,
	H.NAME CHARGE_PERS_NAME ,
	A.SLIP_KIND_TAG ,
	I.CODE_LIST_NAME SLIP_KIND_NAME,
	NVL(A.TRANSFER_TAG, 'F') TRANSFER_TAG,
	NVL(A.IGNORE_SET_RESET_TAG, 'F') IGNORE_SET_RESET_TAG,
	NVL(G.SLIP_UPDATE_CLS, 'T') SLIP_UPDATE_CLS,
	bb1.ACC_CODE ,
	b1.ACC_name ,
	b1.ACC_REMAIN_POSITION,
	bb1.DB_AMT ,
	bb1.CR_AMT ,
	bb1.SUMMARY_CODE ,
	bb1.TAX_COMP_CODE ,
	b8.COMPANY_NAME TAX_COMP_NAME,
	bb1.COMP_CODE ,
	b2.COMPANY_NAME COMP_NAME,
	bb1.DEPT_CODE ,
	b3.DEPT_NAME,
	bb1.CLASS_CODE ,
	b4.CLASS_CODE_NAME,
	bb1.VAT_CODE ,
	b5.VAT_NAME,
	bb1.VAT_DT ,
	bb1.SUPAMT ,
	bb1.VATAMT ,
	bb1.CUST_SEQ ,
	F_T_Cust_Mask(b7.CUST_CODE) CUST_CODE,
	bb1.CUST_NAME ,
	bb1.BANK_CODE ,
	b6.BANK_NAME,
	bb1.ACCNO ,
	bb1.RESET_SLIP_ID ,
	bb1.RESET_SLIP_IDSEQ,
	bb2.SUMMARY1 ,
	bb2.SUMMARY2 ,
	bb2.CHK_NO ,
	bb2.BILL_NO ,
	bb2.REC_BILL_NO ,
	bb2.CP_NO ,
	bb2.SECU_NO ,
	bb2.LOAN_NO ,
	bb2.LOAN_REFUND_NO ,
	bb2.LOAN_REFUND_SEQ ,
	bb2.DEPOSIT_ACCNO ,
	bb2.PAYMENT_SEQ ,
	bb2.PAY_CON_CASH ,
	bb2.PAY_CON_BILL ,
	bb2.PAY_CON_BILL_DT ,
	bb2.PAY_CON_BILL_DAYS ,
	bb2.EMP_NO ,
	b9.NAME EMP_NAME ,
	bb2.ANTICIPATION_DT ,
	bb2.MNG_ITEM_CHAR1 ,
	bb2.MNG_ITEM_CHAR2 ,
	bb2.MNG_ITEM_CHAR3 ,
	bb2.MNG_ITEM_CHAR4 ,
	bb2.MNG_ITEM_NUM1 ,
	bb2.MNG_ITEM_NUM2 ,
	bb2.MNG_ITEM_NUM3 ,
	bb2.MNG_ITEM_NUM4 ,
	bb2.MNG_ITEM_DT1 ,
	bb2.MNG_ITEM_DT2 ,
	bb2.MNG_ITEM_DT3 ,
	bb2.MNG_ITEM_DT4
FROM
	T_LOG_ACC_SLIP_HEAD A,
	T_LOG_ACC_SLIP_BODY1 bb1,
	T_LOG_ACC_SLIP_BODY2 bb2,
	T_COMPANY C,
	T_DEPT_CODE D,
	T_DEPT_CODE E,
	T_DEPT_CODE F,
	T_WORK_CODE G,
	Z_AUTHORITY_USER H,
	Z_AUTHORITY_USER H01,
	(
		SELECT
			CODE_LIST_ID,
			CODE_LIST_NAME
		FROM
			V_T_CODE_LIST
		WHERE
			CODE_GROUP_ID = 'SLIP_KIND_TAG'
	) I,
	(
		SELECT
			CODE_LIST_ID,
			CODE_LIST_NAME
		FROM
			V_T_CODE_LIST
		WHERE
			CODE_GROUP_ID = 'MAKE_SLIPCLS'
	) J,
	T_ACC_CODE b1,
  	T_COMPANY b2,
  	T_DEPT_CODE b3,
  	T_CLASS_CODE b4,
  	T_ACC_VAT_CODE b5,
  	T_BANK_CODE b6,
  	T_CUST_CODE b7,
  	T_COMPANY b8,
	Z_AUTHORITY_USER b9
WHERE
	A.LOG_ID = bb1.LOG_ID
	AND	A.UPDATE_CLS = bb1.UPDATE_CLS
	AND	A.SLIP_ID = bb1.SLIP_ID
	AND	bb1.LOG_ID = bb2.LOG_ID
	AND	bb1.UPDATE_CLS = bb2.UPDATE_CLS
	AND	bb1.SLIP_ID = bb2.SLIP_ID
	AND	bb1.SLIP_IDSEQ = bb2.SLIP_IDSEQ
	AND	A.MAKE_COMP_CODE = C.COMP_CODE
	AND	A.MAKE_DEPT_CODE = D.DEPT_CODE
	AND	A.INOUT_DEPT_CODE = E.DEPT_CODE(+)
	AND	A.KEEP_DEPT_CODE = F.DEPT_CODE(+)
	AND	A.WORK_CODE = G.WORK_CODE(+)
	AND	A.CHARGE_PERS = H.EMPNO(+)
	AND	A. MODUSERNO = H01.EMPNO(+)
	AND	A.SLIP_KIND_TAG = I.CODE_LIST_ID(+)
	AND	A.MAKE_SLIPCLS = J.CODE_LIST_ID(+)
	AND	bb1.ACC_CODE = b1.ACC_CODE
	AND	bb1.COMP_CODE = b2.COMP_CODE
	AND	bb1.DEPT_CODE = b3.DEPT_CODE
	AND	bb1.CLASS_CODE = b4.CLASS_CODE(+)
	AND	bb1.VAT_CODE = b5.VAT_CODE(+)
	AND	bb1.BANK_CODE = b6.BANK_CODE(+)
	AND	bb1.CUST_SEQ = b7.CUST_SEQ(+)
	AND	bb1.TAX_COMP_CODE = b8.COMP_CODE(+)
	AND	bb2.EMP_NO = b9.EMPNO(+)
ORDER BY
	a.MAKE_SLIPNO,
	bb1.MAKE_SLIPLINE;


