CREATE OR REPLACE VIEW T_ACC_SLIP_S_VIEW
AS 
SELECT 
  A.SLIP_ID,
  --A.MAKE_SLIPCLS,
  A.MAKE_SLIPNO,
  A.MAKE_COMP_CODE,
  A.MAKE_DEPT_CODE,
  A.MAKE_DT,
  A.MAKE_DT_TRANS,
  A.MAKE_SEQ,
  A.KEEP_DT,
  A.KEEP_DT_TRANS,
  A.SLIP_KIND_TAG,
  A.TRANSFER_TAG,
  B.SLIP_IDSEQ,
  B.MAKE_SLIPLINE,
  C.ACC_GRP,
  C.ACC_REMAIN_POSITION,
  B.ACC_CODE,
  C.ACC_NAME,
  B.DB_AMT,
  B.CR_AMT,
  B.COMP_CODE,
  B.DEPT_CODE,
  E.DEPT_NAME,
  B.CUST_SEQ,
  D.CUST_CODE,
  B.CUST_NAME
FROM 
	T_ACC_SLIP_HEAD A, 
	T_ACC_SLIP_BODY1 B,
	T_ACC_CODE C,
	T_CUST_CODE D,
	T_DEPT_CODE E
WHERE 
	A.SLIP_ID = B.SLIP_ID
	AND B.ACC_CODE=C.ACC_CODE
	AND B.CUST_SEQ=D.CUST_SEQ(+)
	AND B.DEPT_CODE=E.DEPT_CODE
ORDER BY 
	a.MAKE_SLIPNO, 
	b.MAKE_SLIPLINE;