CREATE OR REPLACE VIEW T_ACC_CODE_VIEW
AS 
SELECT
	A.*,
	B.SALEBUY_CLS,
	B.RCPTBILL_CLS,
	B.SUBTR_CLS,
	B.VATOCCUR_CLS,
	B.SLIP_DETAIL_LIST,
	B.REMARK
FROM
	T_ACC_CODE A,
	T_ACC_CODE_EXT01 B
WHERE
	 A.ACC_CODE = B.ACC_CODE(+);
