/*
이 뷰는 본지사 처리를 위한 뷰입니다
일종의 wrapper입니다.
만약 본지사 처리가 필요 없어진다면 이 뷰를 T_ACC_SLIP_BODY에 대한 시노님으로 재 생성하십시오.
ex) Create Synonym T_ACC_SLIP_BODY_INS for T_ACC_SLIP_BODY;
전표의  입력 프로그램만 이 뷰를 사용합니다.
*/
CREATE OR REPLACE VIEW T_ACC_SLIP_BODY_INS
AS 
SELECT
	a.SLIP_ID ,
	a.SLIP_IDSEQ ,
	a.MAKE_SLIPLINE ,
	a.ACC_CODE ,
	a.DB_AMT ,
	a.CR_AMT ,
	a.SUMMARY_CODE ,
	a.TAX_COMP_CODE ,
	a.COMP_CODE ,
	a.DEPT_CODE ,
	a.CLASS_CODE ,
	a.VAT_CODE ,
	a.VAT_DT ,
	a.SUPAMT ,
	a.VATAMT ,
	a.CUST_SEQ ,
	a.CUST_NAME ,
	a.BANK_CODE ,
	a.ACCNO ,
	a.RESET_SLIP_ID ,
	a.RESET_SLIP_IDSEQ ,
	a.MAKE_COMP_CODE ,
	a.MAKE_DEPT_CODE ,
	a.MAKE_DT ,
	a.KEEP_DT ,
	a.ORG_SLIP_ID,
	a.ORG_SLIP_IDSEQ,
	a.BRAIN_GRP_SEQ,
	a.BRAIN_SLIP_SEQ1,
	a.BRAIN_SLIP_SEQ2 ,
	a.BRAIN_SLIP_LINE,
	a.BRAIN_SORT_SEQ,
	a.BRAIN_ACC_POSITION,
	a.SLIP_KIND_TAG ,
	a.TRANSFER_TAG ,
	a.IGNORE_SET_RESET_TAG ,
	a.CRTUSERNO ,
	a.CRTDATE ,
	a.MODUSERNO ,
	a.MODDATE ,
	a.SUMMARY1 ,
	a.SUMMARY2 ,
	a.CARD_SEQ,
	a.CHK_NO ,
	a.BILL_NO ,
	a.REC_BILL_NO ,
	a.CP_NO ,
	a.SECU_NO ,
	a.LOAN_NO ,
	a.LOAN_REFUND_NO ,
	a.LOAN_REFUND_SEQ ,
	a.DEPOSIT_ACCNO ,
	a.PAYMENT_SEQ ,
	a.PAY_CON_CASH ,
	a.PAY_CON_BILL ,
	a.PAY_CON_BILL_DT ,
	a.PAY_CON_BILL_DAYS ,
	a.EMP_NO ,
	a.ANTICIPATION_DT ,
	a.MNG_ITEM_CHAR1 ,
	a.MNG_ITEM_CHAR2 ,
	a.MNG_ITEM_CHAR3 ,
	a.MNG_ITEM_CHAR4 ,
	a.MNG_ITEM_NUM1 ,
	a.MNG_ITEM_NUM2 ,
	a.MNG_ITEM_NUM3 ,
	a.MNG_ITEM_NUM4 ,
	a.MNG_ITEM_DT1 ,
	a.MNG_ITEM_DT2 ,
	a.MNG_ITEM_DT3 ,
	a.MNG_ITEM_DT4 ,
	a.FIX_ASSET_SEQ
FROM	T_ACC_SLIP_BODY a
WHERE	NOT EXISTS
		(
			SELECT
				b.SLIP_ID ,
				b.SLIP_IDSEQ
			FROM	T_ACC_B_C_SLIP_INFO b
			WHERE	b.BC_TAG = 'C'
			AND		a.SLIP_ID = b.SLIP_ID
			AND		a.SLIP_IDSEQ = b.SLIP_IDSEQ
		)
UNION ALL
SELECT
	a.SLIP_ID ,
	a.SLIP_IDSEQ,
	a.MAKE_SLIPLINE,
	c.ACC_CODE ,
	c.DB_AMT ,
	c.CR_AMT ,
	c.SUMMARY_CODE ,
	c.TAX_COMP_CODE ,
	c.COMP_CODE ,
	c.DEPT_CODE ,
	c.CLASS_CODE ,
	c.VAT_CODE ,
	c.VAT_DT ,
	c.SUPAMT ,
	c.VATAMT ,
	c.CUST_SEQ ,
	c.CUST_NAME ,
	c.BANK_CODE ,
	c.ACCNO ,
	c.RESET_SLIP_ID ,
	c.RESET_SLIP_IDSEQ ,
	c.MAKE_COMP_CODE ,
	c.MAKE_DEPT_CODE ,
	c.MAKE_DT ,
	c.KEEP_DT ,
	c.ORG_SLIP_ID,
	c.ORG_SLIP_IDSEQ,
	c.BRAIN_GRP_SEQ,
	c.BRAIN_SLIP_SEQ1,
	c.BRAIN_SLIP_SEQ2 ,
	c.BRAIN_SLIP_LINE,
	c.BRAIN_SORT_SEQ,
	c.BRAIN_ACC_POSITION,
	c.SLIP_KIND_TAG ,
	c.TRANSFER_TAG ,
	c.IGNORE_SET_RESET_TAG ,
	c.CRTUSERNO ,
	c.CRTDATE ,
	c.MODUSERNO ,
	c.MODDATE ,
	c.SUMMARY1 ,
	c.SUMMARY2 ,
	c.CARD_SEQ,
	c.CHK_NO ,
	c.BILL_NO ,
	c.REC_BILL_NO ,
	c.CP_NO ,
	c.SECU_NO ,
	c.LOAN_NO ,
	c.LOAN_REFUND_NO ,
	c.LOAN_REFUND_SEQ ,
	c.DEPOSIT_ACCNO ,
	c.PAYMENT_SEQ ,
	c.PAY_CON_CASH ,
	c.PAY_CON_BILL ,
	c.PAY_CON_BILL_DT ,
	c.PAY_CON_BILL_DAYS ,
	c.EMP_NO ,
	c.ANTICIPATION_DT ,
	c.MNG_ITEM_CHAR1 ,
	c.MNG_ITEM_CHAR2 ,
	c.MNG_ITEM_CHAR3 ,
	c.MNG_ITEM_CHAR4 ,
	c.MNG_ITEM_NUM1 ,
	c.MNG_ITEM_NUM2 ,
	c.MNG_ITEM_NUM3 ,
	c.MNG_ITEM_NUM4 ,
	c.MNG_ITEM_DT1 ,
	c.MNG_ITEM_DT2 ,
	c.MNG_ITEM_DT3 ,
	c.MNG_ITEM_DT4 ,
	c.FIX_ASSET_SEQ
FROM	T_ACC_SLIP_BODY a,
		T_ACC_B_C_SLIP_INFO b,
		T_ACC_SLIP_BODY c
WHERE	a.SLIP_ID = b.SLIP_ID
AND		a.SLIP_IDSEQ = b.SLIP_IDSEQ
AND		b.C_SLIP_ID = c.SLIP_ID
AND		b.C_SLIP_IDSEQ = c.SLIP_IDSEQ
AND		b.BC_TAG = 'C';

CREATE OR REPLACE PACKAGE PKG_T_ACC_SLIP_BODY_INS
IS
	FUNCTION	Get_Parent_Company
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE
	)
	RETURN T_ACC_SLIP_HEAD.MAKE_COMP_CODE%TYPE;
	FUNCTION	Is_Child_Company_Slip
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Slip_IdSeq	T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE
	)
	RETURN BOOLEAN;
	FUNCTION	Is_Parent_Company_Slip
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Slip_IdSeq	T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE
	)
	RETURN BOOLEAN;
	PROCEDURE	Del_Child_Company_Slip
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Slip_IdSeq	T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE
	);
	PROCEDURE	Del_Child_Company_Slip_Info
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Slip_IdSeq	T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE
	);
	PROCEDURE	Del_Slip
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Slip_IdSeq	T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE
	);
	PROCEDURE	Ins_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE
	);
	PROCEDURE	Upd_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE
	);
	PROCEDURE	Ins_Child_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE,
		Ar_PARENT_COMP_CODE			T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE
	);
	PROCEDURE	Upd_Child_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE,
		Ar_PARENT_COMP_CODE			T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE
	);
	PROCEDURE	Upd_Parent_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE,
		Ar_PARENT_COMP_CODE			T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE
	);
	PROCEDURE	Ins_Parent_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE,
		Ar_PARENT_COMP_CODE			T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE
	);
END;
/
CREATE OR REPLACE PACKAGE BODY PKG_T_ACC_SLIP_BODY_INS
IS
	PROCEDURE	Insert_Head
	(
		Ar_Head						T_ACC_SLIP_HEAD%ROWTYPE
	)
	IS
	BEGIN
		INSERT INTO T_ACC_SLIP_HEAD VALUES Ar_Head;
	END;
	FUNCTION	New_Head
	(
		Ar_Slip_Id					T_Acc_Slip_Head.Slip_Id%TYPE,				--본사쪽 전표 ID
		Ar_Make_Comp_Code			T_Acc_Slip_Head.Make_Comp_Code%TYPE,		--작성 사업장
		Ar_Make_Dept_Code			T_Acc_Slip_Head.Make_Dept_Code%TYPE			--작성 부서
	)
	RETURN T_ACC_SLIP_HEAD%ROWTYPE
	IS
		lrRet						T_ACC_SLIP_HEAD%ROWTYPE;
	BEGIN
		SELECT
			*
		INTO
			lrRet
		FROM	T_ACC_SLIP_HEAD
		WHERE	SLIP_ID = Ar_Slip_Id;

		lrRet.CRTDATE := SYSDATE;
		lrRet.MAKE_COMP_CODE := Ar_Make_Comp_Code;
		lrRet.MAKE_DEPT_CODE := Ar_Make_Dept_Code;
		BEGIN
			SELECT
				DEPT_CODE
			INTO
				lrRet.INOUT_DEPT_CODE
			FROM	T_COMPANY_ORG
			WHERE	COMP_CODE = Ar_Make_Comp_Code;
		EXCEPTION WHEN NO_DATA_FOUND THEN
			RAISE_APPLICATION_ERROR(-20009,'작성 사업장을 찾을 수 없습니다.');
		END;
		IF lrRet.INOUT_DEPT_CODE IS NULL THEN
			RAISE_APPLICATION_ERROR(-20009,'사업장 정보에 출납부서의 설정이 되어 있지 않습니다.');
		END IF;
		lrRet.MAKE_SEQ := F_T_Get_New_Make_Seq(lrRet.MAKE_COMP_CODE,lrRet.MAKE_DT_TRANS);
		lrRet.MAKE_SLIPNO := F_T_GEN_MAKE_SLIP_NO(lrRet.MAKE_COMP_CODE,lrRet.MAKE_DT_TRANS,'S',lrRet.MAKE_SEQ);
		SELECT
			SQ_T_SLIP_ID.NEXTVAL
		INTO
			lrRet.SLIP_ID
		FROM	Dual;
		RETURN lrRet;
	END;
	FUNCTION	Make_Child_Slip_Id
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Comp_Code	T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_Dept_Code	T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE
	)
	RETURN T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE
	IS
		lrRet						T_ACC_SLIP_HEAD%ROWTYPE;
	BEGIN
		lrRet := New_Head(Ar_Slip_Id,Ar_Comp_Code,Ar_Dept_Code);
		Insert_Head(lrRet);
		RETURN lrRet.SLIP_ID;
	END;
	FUNCTION	Get_Parent_Company
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE
	)
	RETURN T_ACC_SLIP_HEAD.MAKE_COMP_CODE%TYPE
	IS
		lsRet				T_ACC_SLIP_HEAD.MAKE_COMP_CODE%TYPE;
	BEGIN
		SELECT
			MAKE_COMP_CODE
		INTO
			lsRet
		FROM	T_ACC_SLIP_HEAD
		WHERE	SLIP_ID = Ar_Slip_Id;
		RETURN lsRet;
	END;
	FUNCTION	Get_Parent_Dept
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE
	)
	RETURN T_ACC_SLIP_HEAD.MAKE_DEPT_CODE%TYPE
	IS
		lsRet				T_ACC_SLIP_HEAD.MAKE_DEPT_CODE%TYPE;
	BEGIN
		SELECT
			MAKE_DEPT_CODE
		INTO
			lsRet
		FROM	T_ACC_SLIP_HEAD
		WHERE	SLIP_ID = Ar_SLIP_ID;
		RETURN lsRet;
	END;
	FUNCTION	Get_Company_Acc_Code
	(
		Ar_Comp_Code		T_COMPANY.COMP_CODE%TYPE
	)
	RETURN T_ACC_CODE.ACC_CODE%TYPE
	IS
		lsRet				T_ACC_CODE.ACC_CODE%TYPE;
	BEGIN
		SELECT
			COMPANY_ACC_CODE
		INTO
			lsRet
		FROM	T_COMPANY_ORG
		WHERE	COMP_CODE = Ar_Comp_Code;
		IF lsRet IS NULL THEN
			RAISE_APPLICATION_ERROR(-20009,'사업장의 본지사 계정을 찾을 수 없습니다.');
		END IF;
		RETURN lsRet;
	EXCEPTION WHEN NO_DATA_FOUND THEN
		RAISE_APPLICATION_ERROR(-20009,'사업장을 찾을 수 없습니다.');
	END;
	FUNCTION	Is_Child_Company_Slip
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Slip_IdSeq	T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE
	)
	RETURN BOOLEAN
	IS
		lnCnt			NUMBER;
	BEGIN
		SELECT	/*+FIRST_ROWS*/
			COUNT(*)
		INTO
			lnCnt
		FROM	T_ACC_B_C_SLIP_INFO a
		WHERE	SLIP_ID = Ar_Slip_Id
		AND		BC_TAG IN ('B','D')
		AND		ROWNUM < 2;
		RETURN lnCnt > 0;
	END;
	FUNCTION	Is_Parent_Company_Slip
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Slip_IdSeq	T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE
	)
	RETURN BOOLEAN
	IS
		lnCnt			NUMBER;
	BEGIN
		SELECT	/*+FIRST_ROWS*/
			COUNT(*)
		INTO
			lnCnt
		FROM	T_ACC_B_C_SLIP_INFO a
		WHERE	SLIP_ID = Ar_Slip_Id
		AND		SLIP_IDSEQ = Ar_Slip_IdSeq
		AND		BC_TAG = 'C'
		AND		ROWNUM < 2;
		RETURN lnCnt > 0;
	END;
	FUNCTION	Make_Or_Get_Child_Slip_Id
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Comp_Code	T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_Dept_Code	T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE
	)
	RETURN T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE
	IS
		lnSlipId				T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE;
	BEGIN
		--먼저 동일 전표에 기존에 만들어진 지사전표가 있다면 이놈을 그대로 사용하고 아니면 하나 만든다...
		--같은 전표 마스터 밑에 있는 것 중 동일한 귀속 사업장인 것을 찾는다.
		BEGIN
			SELECT
				MIN(b.C_SLIP_ID)
			INTO
				lnSlipId
			FROM	T_ACC_SLIP_BODY_INS a,
					T_ACC_B_C_SLIP_INFO b
			WHERE	a.SLIP_ID = b.SLIP_ID
			AND		a.SLIP_IDSEQ = b.SLIP_IDSEQ
			AND		b.BC_TAG = 'C'
			AND		a.COMP_CODE = Ar_Comp_Code
			AND		a.SLIP_ID = Ar_Slip_Id;
		EXCEPTION WHEN NO_DATA_FOUND THEN
			lnSlipId := NULL;
		END;
		IF lnSlipId IS NULL THEN
			lnSlipId := Make_Child_Slip_Id(Ar_Slip_Id,Ar_Comp_Code,Ar_Dept_Code);
		END IF;
		RETURN lnSlipId;
	END;
	PROCEDURE	Del_Child_Company_Slip
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Slip_IdSeq	T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE
	)
	IS
	BEGIN
		--전표라인 삭제
		DELETE	T_ACC_SLIP_BODY a
		WHERE	(a.SLIP_ID,a.SLIP_IDSEQ) IN
		(
			SELECT
				b.SLIP_ID,b.SLIP_IDSEQ
			FROM	T_ACC_B_C_SLIP_INFO b
			WHERE	b.C_SLIP_ID = Ar_Slip_Id
			AND		b.C_SLIP_IDSEQ = Ar_Slip_IdSeq
		);
		--만약 전표라인이 없다면 전표 마스터 삭제
		DELETE	T_ACC_SLIP_HEAD a
		WHERE	a.SLIP_ID = Ar_Slip_Id
		AND		NOT EXISTS
		(
			SELECT
				NULL
			FROM	T_ACC_SLIP_BODY1 b
			WHERE	a.SLIP_ID = b.SLIP_ID
		);
		--만약 전표마스터가 삭제된 것이 아니라면
		--좌수를 자동 조정한다
		IF SQL%RowCount < 1 THEN
			Merge INTO T_ACC_SLIP_BODY1 t
			USING
			(
				SELECT
					SLIP_ID,
					SLIP_IDSEQ,
					Row_Number() Over ( ORDER BY MAKE_SLIPLINE) MAKE_SLIPLINE
				FROM	T_ACC_SLIP_BODY1
				WHERE	SLIP_ID = Ar_Slip_Id
			) s
			ON
			(
				s.SLIP_ID = t.SLIP_ID
			AND	s.SLIP_IDSEQ = t.SLIP_IDSEQ
			)
			WHEN Matched THEN
			UPDATE
			SET	t.MAKE_SLIPLINE = s.MAKE_SLIPLINE
			WHEN NOT Matched THEN
			INSERT
			(SLIP_ID,SLIP_IDSEQ)
			VALUES
			(s.SLIP_ID,s.SLIP_IDSEQ);
		END IF;
	END;
	PROCEDURE	Del_Child_Company_Slip_Info
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Slip_IdSeq	T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE
	)
	IS
	BEGIN
		DELETE	T_ACC_B_C_SLIP_INFO
		WHERE	SLIP_ID = Ar_Slip_Id
		AND		SLIP_IDSEQ = Ar_Slip_IdSeq;
	END;
	PROCEDURE	Del_Slip
	(
		Ar_Slip_Id		T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_Slip_IdSeq	T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE
	)
	IS
	BEGIN
		DELETE	T_ACC_SLIP_BODY
		WHERE	SLIP_ID = Ar_Slip_Id
		AND		SLIP_IDSEQ = Ar_Slip_IdSeq;
	END;
	PROCEDURE	Ins_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE
	)
	IS
	BEGIN
		INSERT INTO T_ACC_SLIP_BODY
		(
			SLIP_ID,
			SLIP_IDSEQ,
			MAKE_SLIPLINE,
			ACC_CODE,
			DB_AMT,
			CR_AMT,
			SUMMARY_CODE,
			TAX_COMP_CODE,
			COMP_CODE,
			DEPT_CODE,
			CLASS_CODE,
			VAT_CODE,
			VAT_DT,
			SUPAMT,
			VATAMT,
			CUST_SEQ,
			CUST_NAME,
			BANK_CODE,
			ACCNO,
			RESET_SLIP_ID,
			RESET_SLIP_IDSEQ,
			ORG_SLIP_ID,
			ORG_SLIP_IDSEQ,
			BRAIN_GRP_SEQ,
			BRAIN_SLIP_SEQ1,
			BRAIN_SLIP_SEQ2,
			BRAIN_SLIP_LINE,
			BRAIN_SORT_SEQ,
			BRAIN_ACC_POSITION,
			CRTUSERNO,
			CRTDATE,
			MODUSERNO,
			MODDATE,
			SUMMARY1,
			SUMMARY2,
			CARD_SEQ,
			CHK_NO,
			BILL_NO,
			REC_BILL_NO,
			CP_NO,
			SECU_NO,
			LOAN_NO,
			LOAN_REFUND_NO,
			LOAN_REFUND_SEQ,
			DEPOSIT_ACCNO,
			PAYMENT_SEQ,
			PAY_CON_CASH,
			PAY_CON_BILL,
			PAY_CON_BILL_DT,
			PAY_CON_BILL_DAYS,
			EMP_NO,
			ANTICIPATION_DT,
			MNG_ITEM_CHAR1,
			MNG_ITEM_CHAR2,
			MNG_ITEM_CHAR3,
			MNG_ITEM_CHAR4,
			MNG_ITEM_NUM1,
			MNG_ITEM_NUM2,
			MNG_ITEM_NUM3,
			MNG_ITEM_NUM4,
			MNG_ITEM_DT1,
			MNG_ITEM_DT2,
			MNG_ITEM_DT3,
			MNG_ITEM_DT4,
			FIX_ASSET_SEQ
		)
		VALUES
		(
			Ar_SLIP_ID,
			Ar_SLIP_IDSEQ,
			Ar_MAKE_SLIPLINE,
			Ar_ACC_CODE,
			Ar_DB_AMT,
			Ar_CR_AMT,
			Ar_SUMMARY_CODE,
			Ar_TAX_COMP_CODE,
			Ar_COMP_CODE,
			Ar_DEPT_CODE,
			Ar_CLASS_CODE,
			Ar_VAT_CODE,
			Ar_VAT_DT,
			Ar_SUPAMT,
			Ar_VATAMT,
			Ar_CUST_SEQ,
			Ar_CUST_NAME,
			Ar_BANK_CODE,
			Ar_ACCNO,
			Ar_RESET_SLIP_ID,
			Ar_RESET_SLIP_IDSEQ,
			Ar_ORG_SLIP_ID,
			Ar_ORG_SLIP_IDSEQ,
			Ar_BRAIN_GRP_SEQ,
			Ar_BRAIN_SLIP_SEQ1,
			Ar_BRAIN_SLIP_SEQ2,
			Ar_BRAIN_SLIP_LINE,
			Ar_BRAIN_SORT_SEQ,
			Ar_BRAIN_ACC_POSITION,
			Ar_CRTUSERNO,
			Ar_CRTDATE,
			Ar_MODUSERNO,
			Ar_MODDATE,
			Ar_SUMMARY1,
			Ar_SUMMARY2,
			Ar_CARD_SEQ,
			Ar_CHK_NO,
			Ar_BILL_NO,
			Ar_REC_BILL_NO,
			Ar_CP_NO,
			Ar_SECU_NO,
			Ar_LOAN_NO,
			Ar_LOAN_REFUND_NO,
			Ar_LOAN_REFUND_SEQ,
			Ar_DEPOSIT_ACCNO,
			Ar_PAYMENT_SEQ,
			Ar_PAY_CON_CASH,
			Ar_PAY_CON_BILL,
			Ar_PAY_CON_BILL_DT,
			Ar_PAY_CON_BILL_DAYS,
			Ar_EMP_NO,
			Ar_ANTICIPATION_DT,
			Ar_MNG_ITEM_CHAR1,
			Ar_MNG_ITEM_CHAR2,
			Ar_MNG_ITEM_CHAR3,
			Ar_MNG_ITEM_CHAR4,
			Ar_MNG_ITEM_NUM1,
			Ar_MNG_ITEM_NUM2,
			Ar_MNG_ITEM_NUM3,
			Ar_MNG_ITEM_NUM4,
			Ar_MNG_ITEM_DT1,
			Ar_MNG_ITEM_DT2,
			Ar_MNG_ITEM_DT3,
			Ar_MNG_ITEM_DT4,
			Ar_FIX_ASSET_SEQ
		);
	END;
	PROCEDURE	Upd_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE
	)
	IS
	BEGIN
		UPDATE	T_ACC_SLIP_BODY
		SET
			MAKE_SLIPLINE			=	Ar_MAKE_SLIPLINE,
			ACC_CODE				=	Ar_ACC_CODE,
			DB_AMT					=	Ar_DB_AMT,
			CR_AMT					=	Ar_CR_AMT,
			SUMMARY_CODE			=	Ar_SUMMARY_CODE,
			TAX_COMP_CODE			=	Ar_TAX_COMP_CODE,
			COMP_CODE				=	Ar_COMP_CODE,
			DEPT_CODE				=	Ar_DEPT_CODE,
			CLASS_CODE				=	Ar_CLASS_CODE,
			VAT_CODE				=	Ar_VAT_CODE,
			VAT_DT					=	Ar_VAT_DT,
			SUPAMT					=	Ar_SUPAMT,
			VATAMT					=	Ar_VATAMT,
			CUST_SEQ				=	Ar_CUST_SEQ,
			CUST_NAME				=	Ar_CUST_NAME,
			BANK_CODE				=	Ar_BANK_CODE,
			ACCNO					=	Ar_ACCNO,
			RESET_SLIP_ID			=	Ar_RESET_SLIP_ID,
			RESET_SLIP_IDSEQ		=	Ar_RESET_SLIP_IDSEQ,
			ORG_SLIP_ID				=	Ar_ORG_SLIP_ID,
			ORG_SLIP_IDSEQ			=	Ar_ORG_SLIP_IDSEQ,
			BRAIN_GRP_SEQ			=	Ar_BRAIN_GRP_SEQ,
			BRAIN_SLIP_SEQ1			=	Ar_BRAIN_SLIP_SEQ1,
			BRAIN_SLIP_SEQ2			=	Ar_BRAIN_SLIP_SEQ2,
			BRAIN_SLIP_LINE			=	Ar_BRAIN_SLIP_LINE,
			BRAIN_SORT_SEQ			=	Ar_BRAIN_SORT_SEQ,
			BRAIN_ACC_POSITION		=	Ar_BRAIN_ACC_POSITION,
			MODUSERNO				=	Ar_MODUSERNO,
			MODDATE					=	Ar_MODDATE,
			SUMMARY1				=	Ar_SUMMARY1,
			SUMMARY2				=	Ar_SUMMARY2,
			CARD_SEQ				=	Ar_CARD_SEQ,
			CHK_NO					=	Ar_CHK_NO,
			BILL_NO					=	Ar_BILL_NO,
			REC_BILL_NO				=	Ar_REC_BILL_NO,
			CP_NO					=	Ar_CP_NO,
			SECU_NO					=	Ar_SECU_NO,
			LOAN_NO					=	Ar_LOAN_NO,
			LOAN_REFUND_NO			=	Ar_LOAN_REFUND_NO,
			LOAN_REFUND_SEQ			=	Ar_LOAN_REFUND_SEQ,
			DEPOSIT_ACCNO			=	Ar_DEPOSIT_ACCNO,
			PAYMENT_SEQ				=	Ar_PAYMENT_SEQ,
			PAY_CON_CASH			=	Ar_PAY_CON_CASH,
			PAY_CON_BILL			=	Ar_PAY_CON_BILL,
			PAY_CON_BILL_DT			=	Ar_PAY_CON_BILL_DT,
			PAY_CON_BILL_DAYS		=	Ar_PAY_CON_BILL_DAYS,
			EMP_NO					=	Ar_EMP_NO,
			ANTICIPATION_DT			=	Ar_ANTICIPATION_DT,
			MNG_ITEM_CHAR1			=	Ar_MNG_ITEM_CHAR1,
			MNG_ITEM_CHAR2			=	Ar_MNG_ITEM_CHAR2,
			MNG_ITEM_CHAR3			=	Ar_MNG_ITEM_CHAR3,
			MNG_ITEM_CHAR4			=	Ar_MNG_ITEM_CHAR4,
			MNG_ITEM_NUM1			=	Ar_MNG_ITEM_NUM1,
			MNG_ITEM_NUM2			=	Ar_MNG_ITEM_NUM2,
			MNG_ITEM_NUM3			=	Ar_MNG_ITEM_NUM3,
			MNG_ITEM_NUM4			=	Ar_MNG_ITEM_NUM4,
			MNG_ITEM_DT1			=	Ar_MNG_ITEM_DT1,
			MNG_ITEM_DT2			=	Ar_MNG_ITEM_DT2,
			MNG_ITEM_DT3			=	Ar_MNG_ITEM_DT3,
			MNG_ITEM_DT4			=	Ar_MNG_ITEM_DT4,
			FIX_ASSET_SEQ			=	Ar_FIX_ASSET_SEQ
		WHERE	SLIP_ID = Ar_SLIP_ID
		AND		SLIP_IDSEQ = Ar_SLIP_IDSEQ;
	END;
	PROCEDURE	Ins_Child_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE,
		Ar_PARENT_COMP_CODE			T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE
	)
	IS
		ln_C_Slip_Id				T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE;
		ln_C_Slip_IdSeq				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE;
		ln_D_Slip_Id				T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE;
		ln_D_Slip_IdSeq				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE;
		ls_MakeDeptCode				T_ACC_SLIP_HEAD.MAKE_DEPT_CODE%TYPE;
		lsAccCode					T_ACC_CODE.ACC_CODE%TYPE;
	BEGIN
		ls_MakeDeptCode := Get_Parent_Dept(Ar_Slip_Id);
		ln_C_Slip_Id := PKG_T_ACC_SLIP_BODY_INS.Make_Or_Get_Child_Slip_Id(Ar_SLIP_ID,Ar_COMP_CODE,Ar_DEPT_CODE);
		IF ln_C_Slip_Id IS NULL THEN
			RAISE_APPLICATION_ERROR(-20009,'본지사 전표 발행 시 에러 전표번호를 얻지 못했습니다.');
		END IF;
		ln_D_Slip_Id := ln_C_Slip_Id;
		SELECT
			SQ_T_SLIP_IDSEQ.NEXTVAL
		INTO
			ln_C_Slip_IdSeq
		FROM	Dual;
		SELECT
			SQ_T_SLIP_IDSEQ.NEXTVAL
		INTO
			ln_D_Slip_IdSeq
		FROM	Dual;
		INSERT INTO T_ACC_SLIP_BODY
		(
			SLIP_ID,
			SLIP_IDSEQ,
			MAKE_SLIPLINE,
			ACC_CODE,
			DB_AMT,
			CR_AMT,
			SUMMARY_CODE,
			TAX_COMP_CODE,
			COMP_CODE,
			DEPT_CODE,
			CLASS_CODE,
			VAT_CODE,
			VAT_DT,
			SUPAMT,
			VATAMT,
			CUST_SEQ,
			CUST_NAME,
			BANK_CODE,
			ACCNO,
			RESET_SLIP_ID,
			RESET_SLIP_IDSEQ,
			ORG_SLIP_ID,
			ORG_SLIP_IDSEQ,
			BRAIN_GRP_SEQ,
			BRAIN_SLIP_SEQ1,
			BRAIN_SLIP_SEQ2,
			BRAIN_SLIP_LINE,
			BRAIN_SORT_SEQ,
			BRAIN_ACC_POSITION,
			CRTUSERNO,
			CRTDATE,
			SUMMARY1,
			SUMMARY2,
			CARD_SEQ,
			CHK_NO,
			BILL_NO,
			REC_BILL_NO,
			CP_NO,
			SECU_NO,
			LOAN_NO,
			LOAN_REFUND_NO,
			LOAN_REFUND_SEQ,
			DEPOSIT_ACCNO,
			PAYMENT_SEQ,
			PAY_CON_CASH,
			PAY_CON_BILL,
			PAY_CON_BILL_DT,
			PAY_CON_BILL_DAYS,
			EMP_NO,
			ANTICIPATION_DT,
			MNG_ITEM_CHAR1,
			MNG_ITEM_CHAR2,
			MNG_ITEM_CHAR3,
			MNG_ITEM_CHAR4,
			MNG_ITEM_NUM1,
			MNG_ITEM_NUM2,
			MNG_ITEM_NUM3,
			MNG_ITEM_NUM4,
			MNG_ITEM_DT1,
			MNG_ITEM_DT2,
			MNG_ITEM_DT3,
			MNG_ITEM_DT4,
			FIX_ASSET_SEQ
		)
		VALUES
		(
			ln_C_Slip_Id,
			ln_C_Slip_IdSeq,
			(SELECT NVL(MAX(MAKE_SLIPLINE),0) + 1 FROM T_ACC_SLIP_BODY1 WHERE SLIP_ID = ln_C_Slip_Id),
			Ar_ACC_CODE,
			Ar_DB_AMT,
			Ar_CR_AMT,
			Ar_SUMMARY_CODE,
			Ar_TAX_COMP_CODE,
			Ar_COMP_CODE,
			Ar_DEPT_CODE,
			Ar_CLASS_CODE,
			Ar_VAT_CODE,
			Ar_VAT_DT,
			Ar_SUPAMT,
			Ar_VATAMT,
			Ar_CUST_SEQ,
			Ar_CUST_NAME,
			Ar_BANK_CODE,
			Ar_ACCNO,
			Decode(Ar_RESET_SLIP_ID,Ar_SLIP_ID,ln_C_Slip_Id,Ar_RESET_SLIP_ID),
			Decode(Ar_RESET_SLIP_IDSEQ,Ar_SLIP_IDSEQ,ln_C_Slip_IdSeq,Ar_RESET_SLIP_IDSEQ),
			Ar_ORG_SLIP_ID,
			Ar_ORG_SLIP_IDSEQ,
			Ar_BRAIN_GRP_SEQ,
			Ar_BRAIN_SLIP_SEQ1,
			Ar_BRAIN_SLIP_SEQ2,
			Ar_BRAIN_SLIP_LINE,
			Ar_BRAIN_SORT_SEQ,
			Ar_BRAIN_ACC_POSITION,
			Ar_CRTUSERNO,
			Ar_CRTDATE,
			Ar_SUMMARY1,
			Ar_SUMMARY2,
			Ar_CARD_SEQ,
			Ar_CHK_NO,
			Ar_BILL_NO,
			Ar_REC_BILL_NO,
			Ar_CP_NO,
			Ar_SECU_NO,
			Ar_LOAN_NO,
			Ar_LOAN_REFUND_NO,
			Ar_LOAN_REFUND_SEQ,
			Ar_DEPOSIT_ACCNO,
			Ar_PAYMENT_SEQ,
			Ar_PAY_CON_CASH,
			Ar_PAY_CON_BILL,
			Ar_PAY_CON_BILL_DT,
			Ar_PAY_CON_BILL_DAYS,
			Ar_EMP_NO,
			Ar_ANTICIPATION_DT,
			Ar_MNG_ITEM_CHAR1,
			Ar_MNG_ITEM_CHAR2,
			Ar_MNG_ITEM_CHAR3,
			Ar_MNG_ITEM_CHAR4,
			Ar_MNG_ITEM_NUM1,
			Ar_MNG_ITEM_NUM2,
			Ar_MNG_ITEM_NUM3,
			Ar_MNG_ITEM_NUM4,
			Ar_MNG_ITEM_DT1,
			Ar_MNG_ITEM_DT2,
			Ar_MNG_ITEM_DT3,
			Ar_MNG_ITEM_DT4,
			Ar_FIX_ASSET_SEQ
		);

		lsAccCode := Get_Company_Acc_Code(Ar_PARENT_COMP_CODE);		--본사의 사업장 계정코드
		INSERT INTO T_ACC_SLIP_BODY
		(
			SLIP_ID,
			SLIP_IDSEQ,
			MAKE_SLIPLINE,
			ACC_CODE,
			DB_AMT,
			CR_AMT,
			SUMMARY_CODE,
			TAX_COMP_CODE,
			COMP_CODE,
			DEPT_CODE,
			CLASS_CODE,
			CRTUSERNO,
			CRTDATE,
			SUMMARY1,
			SUMMARY2
		)
		VALUES
		(
			ln_D_Slip_Id,
			ln_D_Slip_IdSeq,
			(SELECT NVL(MAX(MAKE_SLIPLINE),0) + 1 FROM T_ACC_SLIP_BODY1 WHERE SLIP_ID = ln_C_Slip_Id),
			lsAccCode,
			Ar_CR_AMT,										--차대 반대
			Ar_DB_AMT,										--차대 반대
			Ar_SUMMARY_CODE,
			Ar_TAX_COMP_CODE,
			Ar_COMP_CODE,
			Ar_DEPT_CODE,
			Ar_CLASS_CODE,
			Ar_MODUSERNO,
			Ar_MODDATE,
			Ar_SUMMARY1,
			Ar_SUMMARY2
		);
		Merge INTO T_ACC_B_C_SLIP_INFO t
		USING
		(
			SELECT
				Ar_Slip_Id SLIP_ID,
				Ar_Slip_IdSeq SLIP_IDSEQ,
				'C' BC_TAG,
				ln_C_Slip_Id C_SLIP_ID,
				ln_C_Slip_IdSeq C_SLIP_IDSEQ
			FROM	Dual
			UNION ALL
			SELECT
				ln_C_Slip_Id SLIP_ID,
				ln_C_Slip_IdSeq SLIP_IDSEQ,
				'B' BC_TAG,
				Ar_Slip_Id C_SLIP_ID,
				Ar_Slip_IdSeq C_SLIP_IDSEQ
			FROM	Dual
			UNION ALL
			SELECT
				ln_D_Slip_Id SLIP_ID,
				ln_D_Slip_IdSeq SLIP_IDSEQ,
				'D' BC_TAG,
				Ar_Slip_Id C_SLIP_ID,
				Ar_Slip_IdSeq C_SLIP_IDSEQ
			FROM	Dual
		) s
		ON
		(
			s.SLIP_ID = t.SLIP_ID
		AND	s.SLIP_IDSEQ = t.SLIP_IDSEQ
		)
		WHEN Matched THEN
		UPDATE
		SET		t.BC_TAG = s.BC_TAG,
				t.C_SLIP_ID = s.C_SLIP_ID,
				t.C_SLIP_IDSEQ = s.C_SLIP_IDSEQ
		WHEN NOT Matched THEN
		INSERT
		(
			SLIP_ID,
			SLIP_IDSEQ,
			BC_TAG,
			C_SLIP_ID,
			C_SLIP_IDSEQ
		)
		VALUES
		(
			s.SLIP_ID,
			s.SLIP_IDSEQ,
			s.BC_TAG,
			s.C_SLIP_ID,
			s.C_SLIP_IDSEQ
		);
	END;
	PROCEDURE	Upd_Child_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE,
		Ar_PARENT_COMP_CODE			T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE
	)
	IS
		ln_C_Slip_Id				T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE;
		ln_C_Slip_IdSeq				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE;
		ln_D_Slip_Id				T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE;
		ln_D_Slip_IdSeq				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE;
		ls_MakeDeptCode				T_ACC_SLIP_HEAD.MAKE_DEPT_CODE%TYPE;
		lsAccCode					T_ACC_CODE.ACC_CODE%TYPE;
	BEGIN
		BEGIN
			SELECT
				MAX(DECODE(BC_TAG,'B',SLIP_ID)),
				MAX(DECODE(BC_TAG,'B',SLIP_IDSEQ)),
				MAX(DECODE(BC_TAG,'D',SLIP_ID)),
				MAX(DECODE(BC_TAG,'D',SLIP_IDSEQ))
			INTO
				ln_C_Slip_Id,
				ln_C_Slip_IdSeq,
				ln_D_Slip_Id,
				ln_D_Slip_IdSeq
			FROM	T_ACC_B_C_SLIP_INFO
			WHERE	C_SLIP_ID = Ar_Slip_Id
			AND		C_SLIP_IDSEQ = Ar_Slip_IdSeq;
		EXCEPTION WHEN NO_DATA_FOUND THEN
			RAISE_APPLICATION_ERROR(-20009,'지사 전표 정보를 찾을 수 없습니다.');
		END;
		IF ln_C_Slip_Id IS NULL OR ln_D_Slip_Id IS NULL THEN
			RAISE_APPLICATION_ERROR(-20009,'지사 전표 정보를 찾을 수 없습니다.');
		END IF;
		ls_MakeDeptCode := Get_Parent_Dept(Ar_Slip_Id);
		UPDATE	T_ACC_SLIP_BODY
		SET
			ACC_CODE				=	Ar_ACC_CODE,
			DB_AMT					=	Ar_DB_AMT,
			CR_AMT					=	Ar_CR_AMT,
			SUMMARY_CODE			=	Ar_SUMMARY_CODE,
			TAX_COMP_CODE			=	Ar_TAX_COMP_CODE,
			COMP_CODE				=	Ar_COMP_CODE,
			DEPT_CODE				=	Ar_DEPT_CODE,
			CLASS_CODE				=	Ar_CLASS_CODE,
			VAT_CODE				=	Ar_VAT_CODE,
			VAT_DT					=	Ar_VAT_DT,
			SUPAMT					=	Ar_SUPAMT,
			VATAMT					=	Ar_VATAMT,
			CUST_SEQ				=	Ar_CUST_SEQ,
			CUST_NAME				=	Ar_CUST_NAME,
			BANK_CODE				=	Ar_BANK_CODE,
			ACCNO					=	Ar_ACCNO,
			RESET_SLIP_ID			=	Ar_RESET_SLIP_ID,
			RESET_SLIP_IDSEQ		=	Ar_RESET_SLIP_IDSEQ,
			ORG_SLIP_ID				=	Ar_ORG_SLIP_ID,
			ORG_SLIP_IDSEQ			=	Ar_ORG_SLIP_IDSEQ,
			BRAIN_GRP_SEQ			=	Ar_BRAIN_GRP_SEQ,
			BRAIN_SLIP_SEQ1			=	Ar_BRAIN_SLIP_SEQ1,
			BRAIN_SLIP_SEQ2			=	Ar_BRAIN_SLIP_SEQ2,
			BRAIN_SLIP_LINE			=	Ar_BRAIN_SLIP_LINE,
			BRAIN_SORT_SEQ			=	Ar_BRAIN_SORT_SEQ,
			BRAIN_ACC_POSITION		=	Ar_BRAIN_ACC_POSITION,
			MODUSERNO				=	Ar_MODUSERNO,
			MODDATE					=	Ar_MODDATE,
			SUMMARY1				=	Ar_SUMMARY1,
			SUMMARY2				=	Ar_SUMMARY2,
			CARD_SEQ				=	Ar_CARD_SEQ,
			CHK_NO					=	Ar_CHK_NO,
			BILL_NO					=	Ar_BILL_NO,
			REC_BILL_NO				=	Ar_REC_BILL_NO,
			CP_NO					=	Ar_CP_NO,
			SECU_NO					=	Ar_SECU_NO,
			LOAN_NO					=	Ar_LOAN_NO,
			LOAN_REFUND_NO			=	Ar_LOAN_REFUND_NO,
			LOAN_REFUND_SEQ			=	Ar_LOAN_REFUND_SEQ,
			DEPOSIT_ACCNO			=	Ar_DEPOSIT_ACCNO,
			PAYMENT_SEQ				=	Ar_PAYMENT_SEQ,
			PAY_CON_CASH			=	Ar_PAY_CON_CASH,
			PAY_CON_BILL			=	Ar_PAY_CON_BILL,
			PAY_CON_BILL_DT			=	Ar_PAY_CON_BILL_DT,
			PAY_CON_BILL_DAYS		=	Ar_PAY_CON_BILL_DAYS,
			EMP_NO					=	Ar_EMP_NO,
			ANTICIPATION_DT			=	Ar_ANTICIPATION_DT,
			MNG_ITEM_CHAR1			=	Ar_MNG_ITEM_CHAR1,
			MNG_ITEM_CHAR2			=	Ar_MNG_ITEM_CHAR2,
			MNG_ITEM_CHAR3			=	Ar_MNG_ITEM_CHAR3,
			MNG_ITEM_CHAR4			=	Ar_MNG_ITEM_CHAR4,
			MNG_ITEM_NUM1			=	Ar_MNG_ITEM_NUM1,
			MNG_ITEM_NUM2			=	Ar_MNG_ITEM_NUM2,
			MNG_ITEM_NUM3			=	Ar_MNG_ITEM_NUM3,
			MNG_ITEM_NUM4			=	Ar_MNG_ITEM_NUM4,
			MNG_ITEM_DT1			=	Ar_MNG_ITEM_DT1,
			MNG_ITEM_DT2			=	Ar_MNG_ITEM_DT2,
			MNG_ITEM_DT3			=	Ar_MNG_ITEM_DT3,
			MNG_ITEM_DT4			=	Ar_MNG_ITEM_DT4,
			FIX_ASSET_SEQ			=	Ar_FIX_ASSET_SEQ
		WHERE	SLIP_ID = ln_C_Slip_Id
		AND		SLIP_IDSEQ = ln_C_Slip_IdSeq;
		lsAccCode := Get_Company_Acc_Code(Ar_PARENT_COMP_CODE);		--본사의 사업장 계정코드
		UPDATE	T_ACC_SLIP_BODY
		SET
			ACC_CODE				=	lsAccCode,
			DB_AMT					=	Ar_CR_AMT,										--차대 반대
			CR_AMT					=	Ar_DB_AMT,										--차대 반대
			SUMMARY_CODE			=	Ar_SUMMARY_CODE,
			TAX_COMP_CODE			=	Ar_TAX_COMP_CODE,
			COMP_CODE				=	Ar_COMP_CODE,
			DEPT_CODE				=	Ar_DEPT_CODE,
			CLASS_CODE				=	Ar_CLASS_CODE,
			MODUSERNO				=	Ar_MODUSERNO,
			MODDATE					=	Ar_MODDATE,
			SUMMARY1				=	Ar_SUMMARY1,
			SUMMARY2				=	Ar_SUMMARY2
		WHERE	SLIP_ID = ln_D_Slip_Id
		AND		SLIP_IDSEQ = ln_D_Slip_IdSeq;
	END;
	PROCEDURE	Upd_Parent_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE,
		Ar_PARENT_COMP_CODE			T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE
	)
	IS
		ls_MakeDeptCode				T_ACC_SLIP_HEAD.MAKE_DEPT_CODE%TYPE;
		lsAccCode					T_ACC_CODE.ACC_CODE%TYPE;
	BEGIN
		ls_MakeDeptCode := Get_Parent_Dept(Ar_Slip_Id);
		lsAccCode := Get_Company_Acc_Code(Ar_COMP_CODE);		--지사의 사업장 계정코드
		UPDATE	T_ACC_SLIP_BODY
		SET
			MAKE_SLIPLINE			=	Ar_MAKE_SLIPLINE,
			ACC_CODE				=	lsAccCode,
			DB_AMT					=	Ar_DB_AMT,
			CR_AMT					=	Ar_CR_AMT,
			SUMMARY_CODE			=	Ar_SUMMARY_CODE,
			TAX_COMP_CODE			=	Ar_PARENT_COMP_CODE,
			COMP_CODE				=	Ar_PARENT_COMP_CODE,
			DEPT_CODE				=	ls_MakeDeptCode,
			CLASS_CODE				=	Ar_CLASS_CODE,
			VAT_CODE				=	NULL,
			VAT_DT					=	NULL,
			SUPAMT					=	NULL,
			VATAMT					=	NULL,
			BANK_CODE				=	NULL,
			ACCNO					=	NULL,
			RESET_SLIP_ID			=	NULL,
			RESET_SLIP_IDSEQ		=	NULL,
			ORG_SLIP_ID			=	NULL,
			ORG_SLIP_IDSEQ			=	NULL,
			BRAIN_GRP_SEQ			=	NULL,
			BRAIN_SLIP_SEQ1			=	NULL,
			BRAIN_SLIP_SEQ2			=	NULL,
			BRAIN_SLIP_LINE			=	NULL,
			BRAIN_SORT_SEQ			=	NULL,
			BRAIN_ACC_POSITION		=	NULL,
			MODUSERNO				=	Ar_MODUSERNO,
			MODDATE					=	Ar_MODDATE,
			SUMMARY1				=	Ar_SUMMARY1,
			SUMMARY2				=	Ar_SUMMARY2,
			CARD_SEQ				=	Ar_CARD_SEQ,
			CHK_NO					=	NULL,
			BILL_NO					=	NULL,
			REC_BILL_NO				=	NULL,
			CP_NO					=	NULL,
			SECU_NO					=	NULL,
			LOAN_NO					=	NULL,
			LOAN_REFUND_NO			=	NULL,
			LOAN_REFUND_SEQ			=	NULL,
			DEPOSIT_ACCNO			=	NULL,
			PAYMENT_SEQ				=	NULL,
			PAY_CON_CASH			=	NULL,
			PAY_CON_BILL			=	NULL,
			PAY_CON_BILL_DT			=	NULL,
			PAY_CON_BILL_DAYS		=	NULL,
			EMP_NO					=	Ar_EMP_NO,
			ANTICIPATION_DT			=	NULL,
			MNG_ITEM_CHAR1			=	NULL,
			MNG_ITEM_CHAR2			=	NULL,
			MNG_ITEM_CHAR3			=	NULL,
			MNG_ITEM_CHAR4			=	NULL,
			MNG_ITEM_NUM1			=	NULL,
			MNG_ITEM_NUM2			=	NULL,
			MNG_ITEM_NUM3			=	NULL,
			MNG_ITEM_NUM4			=	NULL,
			MNG_ITEM_DT1			=	NULL,
			MNG_ITEM_DT2			=	NULL,
			MNG_ITEM_DT3			=	NULL,
			MNG_ITEM_DT4			=	NULL,
			FIX_ASSET_SEQ			=	NULL
		WHERE	SLIP_ID = Ar_SLIP_ID
		AND		SLIP_IDSEQ = Ar_SLIP_IDSEQ;
	END;
	PROCEDURE	Ins_Parent_Slip
	(
		Ar_SLIP_ID					T_ACC_SLIP_BODY_INS.SLIP_ID%TYPE,
		Ar_SLIP_IDSEQ				T_ACC_SLIP_BODY_INS.SLIP_IDSEQ%TYPE,
		Ar_MAKE_SLIPLINE			T_ACC_SLIP_BODY_INS.MAKE_SLIPLINE%TYPE,
		Ar_ACC_CODE					T_ACC_SLIP_BODY_INS.ACC_CODE%TYPE,
		Ar_DB_AMT					T_ACC_SLIP_BODY_INS.DB_AMT%TYPE,
		Ar_CR_AMT					T_ACC_SLIP_BODY_INS.CR_AMT%TYPE,
		Ar_SUMMARY_CODE				T_ACC_SLIP_BODY_INS.SUMMARY_CODE%TYPE,
		Ar_TAX_COMP_CODE			T_ACC_SLIP_BODY_INS.TAX_COMP_CODE%TYPE,
		Ar_COMP_CODE				T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE,
		Ar_DEPT_CODE				T_ACC_SLIP_BODY_INS.DEPT_CODE%TYPE,
		Ar_CLASS_CODE				T_ACC_SLIP_BODY_INS.CLASS_CODE%TYPE,
		Ar_VAT_CODE					T_ACC_SLIP_BODY_INS.VAT_CODE%TYPE,
		Ar_VAT_DT					T_ACC_SLIP_BODY_INS.VAT_DT%TYPE,
		Ar_SUPAMT					T_ACC_SLIP_BODY_INS.SUPAMT%TYPE,
		Ar_VATAMT					T_ACC_SLIP_BODY_INS.VATAMT%TYPE,
		Ar_CUST_SEQ					T_ACC_SLIP_BODY_INS.CUST_SEQ%TYPE,
		Ar_CUST_NAME				T_ACC_SLIP_BODY_INS.CUST_NAME%TYPE,
		Ar_BANK_CODE				T_ACC_SLIP_BODY_INS.BANK_CODE%TYPE,
		Ar_ACCNO					T_ACC_SLIP_BODY_INS.ACCNO%TYPE,
		Ar_RESET_SLIP_ID			T_ACC_SLIP_BODY_INS.RESET_SLIP_ID%TYPE,
		Ar_RESET_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.RESET_SLIP_IDSEQ%TYPE,
		Ar_MAKE_COMP_CODE			T_ACC_SLIP_BODY_INS.MAKE_COMP_CODE%TYPE,
		Ar_MAKE_DEPT_CODE			T_ACC_SLIP_BODY_INS.MAKE_DEPT_CODE%TYPE,
		Ar_MAKE_DT					T_ACC_SLIP_BODY_INS.MAKE_DT%TYPE,
		Ar_KEEP_DT					T_ACC_SLIP_BODY_INS.KEEP_DT%TYPE,
		Ar_ORG_SLIP_ID				T_ACC_SLIP_BODY_INS.ORG_SLIP_ID%TYPE,
		Ar_ORG_SLIP_IDSEQ			T_ACC_SLIP_BODY_INS.ORG_SLIP_IDSEQ%TYPE,
		Ar_BRAIN_GRP_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_GRP_SEQ%TYPE,
		Ar_BRAIN_SLIP_SEQ1			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ1%TYPE,
		Ar_BRAIN_SLIP_SEQ2			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_SEQ2%TYPE,
		Ar_BRAIN_SLIP_LINE			T_ACC_SLIP_BODY_INS.BRAIN_SLIP_LINE%TYPE,
		Ar_BRAIN_SORT_SEQ			T_ACC_SLIP_BODY_INS.BRAIN_SORT_SEQ%TYPE,
		Ar_BRAIN_ACC_POSITION			T_ACC_SLIP_BODY_INS.BRAIN_ACC_POSITION%TYPE,
		Ar_SLIP_KIND_TAG			T_ACC_SLIP_BODY_INS.SLIP_KIND_TAG%TYPE,
		Ar_TRANSFER_TAG				T_ACC_SLIP_BODY_INS.TRANSFER_TAG%TYPE,
		Ar_IGNORE_SET_RESET_TAG		T_ACC_SLIP_BODY_INS.IGNORE_SET_RESET_TAG%TYPE,
		Ar_CRTUSERNO				T_ACC_SLIP_BODY_INS.CRTUSERNO%TYPE,
		Ar_CRTDATE					T_ACC_SLIP_BODY_INS.CRTDATE%TYPE,
		Ar_MODUSERNO				T_ACC_SLIP_BODY_INS.MODUSERNO%TYPE,
		Ar_MODDATE					T_ACC_SLIP_BODY_INS.MODDATE%TYPE,
		Ar_SUMMARY1					T_ACC_SLIP_BODY_INS.SUMMARY1%TYPE,
		Ar_SUMMARY2					T_ACC_SLIP_BODY_INS.SUMMARY2%TYPE,
		Ar_CARD_SEQ					T_ACC_SLIP_BODY_INS.CARD_SEQ%TYPE,
		Ar_CHK_NO					T_ACC_SLIP_BODY_INS.CHK_NO%TYPE,
		Ar_BILL_NO					T_ACC_SLIP_BODY_INS.BILL_NO%TYPE,
		Ar_REC_BILL_NO				T_ACC_SLIP_BODY_INS.REC_BILL_NO%TYPE,
		Ar_CP_NO					T_ACC_SLIP_BODY_INS.CP_NO%TYPE,
		Ar_SECU_NO					T_ACC_SLIP_BODY_INS.SECU_NO%TYPE,
		Ar_LOAN_NO					T_ACC_SLIP_BODY_INS.LOAN_NO%TYPE,
		Ar_LOAN_REFUND_NO			T_ACC_SLIP_BODY_INS.LOAN_REFUND_NO%TYPE,
		Ar_LOAN_REFUND_SEQ			T_ACC_SLIP_BODY_INS.LOAN_REFUND_SEQ%TYPE,
		Ar_DEPOSIT_ACCNO			T_ACC_SLIP_BODY_INS.DEPOSIT_ACCNO%TYPE,
		Ar_PAYMENT_SEQ				T_ACC_SLIP_BODY_INS.PAYMENT_SEQ%TYPE,
		Ar_PAY_CON_CASH				T_ACC_SLIP_BODY_INS.PAY_CON_CASH%TYPE,
		Ar_PAY_CON_BILL				T_ACC_SLIP_BODY_INS.PAY_CON_BILL%TYPE,
		Ar_PAY_CON_BILL_DT			T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DT%TYPE,
		Ar_PAY_CON_BILL_DAYS		T_ACC_SLIP_BODY_INS.PAY_CON_BILL_DAYS%TYPE,
		Ar_EMP_NO					T_ACC_SLIP_BODY_INS.EMP_NO%TYPE,
		Ar_ANTICIPATION_DT			T_ACC_SLIP_BODY_INS.ANTICIPATION_DT%TYPE,
		Ar_MNG_ITEM_CHAR1			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR1%TYPE,
		Ar_MNG_ITEM_CHAR2			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR2%TYPE,
		Ar_MNG_ITEM_CHAR3			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR3%TYPE,
		Ar_MNG_ITEM_CHAR4			T_ACC_SLIP_BODY_INS.MNG_ITEM_CHAR4%TYPE,
		Ar_MNG_ITEM_NUM1			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM1%TYPE,
		Ar_MNG_ITEM_NUM2			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM2%TYPE,
		Ar_MNG_ITEM_NUM3			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM3%TYPE,
		Ar_MNG_ITEM_NUM4			T_ACC_SLIP_BODY_INS.MNG_ITEM_NUM4%TYPE,
		Ar_MNG_ITEM_DT1				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT1%TYPE,
		Ar_MNG_ITEM_DT2				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT2%TYPE,
		Ar_MNG_ITEM_DT3				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT3%TYPE,
		Ar_MNG_ITEM_DT4				T_ACC_SLIP_BODY_INS.MNG_ITEM_DT4%TYPE,
		Ar_FIX_ASSET_SEQ			T_ACC_SLIP_BODY_INS.FIX_ASSET_SEQ%TYPE,
		Ar_PARENT_COMP_CODE			T_ACC_SLIP_BODY_INS.COMP_CODE%TYPE
	)
	IS
		ls_MakeDeptCode				T_ACC_SLIP_HEAD.MAKE_DEPT_CODE%TYPE;
		lsAccCode					T_ACC_CODE.ACC_CODE%TYPE;
	BEGIN
		ls_MakeDeptCode := Get_Parent_Dept(Ar_Slip_Id);
		lsAccCode := Get_Company_Acc_Code(Ar_COMP_CODE);		--지사의 사업장 계정코드
		INSERT INTO T_ACC_SLIP_BODY
		(
			SLIP_ID,
			SLIP_IDSEQ,
			MAKE_SLIPLINE,
			ACC_CODE,
			DB_AMT,
			CR_AMT,
			SUMMARY_CODE,
			TAX_COMP_CODE,
			COMP_CODE,
			DEPT_CODE,
			CLASS_CODE,
			CRTUSERNO,
			CRTDATE,
			SUMMARY1,
			SUMMARY2,
			EMP_NO
		)
		VALUES
		(
			Ar_SLIP_ID,
			Ar_SLIP_IDSEQ,
			Ar_MAKE_SLIPLINE,
			lsAccCode,
			Ar_DB_AMT,
			Ar_CR_AMT,
			Ar_SUMMARY_CODE,
			Ar_PARENT_COMP_CODE,
			Ar_PARENT_COMP_CODE,
			ls_MakeDeptCode,
			Ar_CLASS_CODE,
			Ar_CRTUSERNO,
			Ar_CRTDATE,
			Ar_SUMMARY1,
			Ar_SUMMARY2,
			Ar_EMP_NO
		);
	END;
END;
/

CREATE OR REPLACE TRIGGER T_ACC_SLIP_BODY_INS_trg
Instead OF INSERT OR UPDATE OR DELETE ON T_ACC_SLIP_BODY_INS
FOR EACH ROW
DECLARE
	ls_MakeCompanyCode				T_ACC_SLIP_HEAD.MAKE_COMP_CODE%TYPE;
BEGIN
	IF INSERTING THEN
		--만약 자신이 지사 전표이면 삭제변경될 수 없습니다.
		IF PKG_T_ACC_SLIP_BODY_INS.Is_Child_Company_Slip(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ) THEN
			RAISE_APPLICATION_ERROR(-20009,'지사 전표는 삭제 또는 수정될 수 없습니다.');
		END IF;
		ls_MakeCompanyCode := PKG_T_ACC_SLIP_BODY_INS.Get_Parent_Company(:NEW.SLIP_ID);
		IF ls_MakeCompanyCode = :NEW.COMP_CODE THEN
			--본지사 전표가 아닌 경우 그냥 Insert 합니다.
			PKG_T_ACC_SLIP_BODY_INS.Ins_Slip(
				:NEW.SLIP_ID,
				:NEW.SLIP_IDSEQ,
				:NEW.MAKE_SLIPLINE,
				:NEW.ACC_CODE,
				:NEW.DB_AMT,
				:NEW.CR_AMT,
				:NEW.SUMMARY_CODE,
				:NEW.TAX_COMP_CODE,
				:NEW.COMP_CODE,
				:NEW.DEPT_CODE,
				:NEW.CLASS_CODE,
				:NEW.VAT_CODE,
				:NEW.VAT_DT,
				:NEW.SUPAMT,
				:NEW.VATAMT,
				:NEW.CUST_SEQ,
				:NEW.CUST_NAME,
				:NEW.BANK_CODE,
				:NEW.ACCNO,
				:NEW.RESET_SLIP_ID,
				:NEW.RESET_SLIP_IDSEQ,
				:NEW.MAKE_COMP_CODE,
				:NEW.MAKE_DEPT_CODE,
				:NEW.MAKE_DT,
				:NEW.KEEP_DT,
				:NEW.ORG_SLIP_ID,
				:NEW.ORG_SLIP_IDSEQ,
				:NEW.BRAIN_GRP_SEQ,
				:NEW.BRAIN_SLIP_SEQ1,
				:NEW.BRAIN_SLIP_SEQ2,
				:NEW.BRAIN_SLIP_LINE,
				:NEW.BRAIN_SORT_SEQ,
				:NEW.BRAIN_ACC_POSITION,
				:NEW.SLIP_KIND_TAG,
				:NEW.TRANSFER_TAG,
				:NEW.IGNORE_SET_RESET_TAG,
				:NEW.CRTUSERNO,
				:NEW.CRTDATE,
				:NEW.MODUSERNO,
				:NEW.MODDATE,
				:NEW.SUMMARY1,
				:NEW.SUMMARY2,
				:NEW.CARD_SEQ,
				:NEW.CHK_NO,
				:NEW.BILL_NO,
				:NEW.REC_BILL_NO,
				:NEW.CP_NO,
				:NEW.SECU_NO,
				:NEW.LOAN_NO,
				:NEW.LOAN_REFUND_NO,
				:NEW.LOAN_REFUND_SEQ,
				:NEW.DEPOSIT_ACCNO,
				:NEW.PAYMENT_SEQ,
				:NEW.PAY_CON_CASH,
				:NEW.PAY_CON_BILL,
				:NEW.PAY_CON_BILL_DT,
				:NEW.PAY_CON_BILL_DAYS,
				:NEW.EMP_NO,
				:NEW.ANTICIPATION_DT,
				:NEW.MNG_ITEM_CHAR1,
				:NEW.MNG_ITEM_CHAR2,
				:NEW.MNG_ITEM_CHAR3,
				:NEW.MNG_ITEM_CHAR4,
				:NEW.MNG_ITEM_NUM1,
				:NEW.MNG_ITEM_NUM2,
				:NEW.MNG_ITEM_NUM3,
				:NEW.MNG_ITEM_NUM4,
				:NEW.MNG_ITEM_DT1,
				:NEW.MNG_ITEM_DT2,
				:NEW.MNG_ITEM_DT3,
				:NEW.MNG_ITEM_DT4,
				:NEW.FIX_ASSET_SEQ
			);
		ELSE
			--본지사 전표인 경우
			--먼저 본사전표를 삽입합니다.
			PKG_T_ACC_SLIP_BODY_INS.Ins_Parent_Slip(
				:NEW.SLIP_ID,
				:NEW.SLIP_IDSEQ,
				:NEW.MAKE_SLIPLINE,
				:NEW.ACC_CODE,
				:NEW.DB_AMT,
				:NEW.CR_AMT,
				:NEW.SUMMARY_CODE,
				:NEW.TAX_COMP_CODE,
				:NEW.COMP_CODE,
				:NEW.DEPT_CODE,
				:NEW.CLASS_CODE,
				:NEW.VAT_CODE,
				:NEW.VAT_DT,
				:NEW.SUPAMT,
				:NEW.VATAMT,
				:NEW.CUST_SEQ,
				:NEW.CUST_NAME,
				:NEW.BANK_CODE,
				:NEW.ACCNO,
				:NEW.RESET_SLIP_ID,
				:NEW.RESET_SLIP_IDSEQ,
				:NEW.MAKE_COMP_CODE,
				:NEW.MAKE_DEPT_CODE,
				:NEW.MAKE_DT,
				:NEW.KEEP_DT,
				:NEW.ORG_SLIP_ID,
				:NEW.ORG_SLIP_IDSEQ,
				:NEW.BRAIN_GRP_SEQ,
				:NEW.BRAIN_SLIP_SEQ1,
				:NEW.BRAIN_SLIP_SEQ2,
				:NEW.BRAIN_SLIP_LINE,
				:NEW.BRAIN_SORT_SEQ,
				:NEW.BRAIN_ACC_POSITION,
				:NEW.SLIP_KIND_TAG,
				:NEW.TRANSFER_TAG,
				:NEW.IGNORE_SET_RESET_TAG,
				:NEW.CRTUSERNO,
				:NEW.CRTDATE,
				:NEW.MODUSERNO,
				:NEW.MODDATE,
				:NEW.SUMMARY1,
				:NEW.SUMMARY2,
				:NEW.CARD_SEQ,
				:NEW.CHK_NO,
				:NEW.BILL_NO,
				:NEW.REC_BILL_NO,
				:NEW.CP_NO,
				:NEW.SECU_NO,
				:NEW.LOAN_NO,
				:NEW.LOAN_REFUND_NO,
				:NEW.LOAN_REFUND_SEQ,
				:NEW.DEPOSIT_ACCNO,
				:NEW.PAYMENT_SEQ,
				:NEW.PAY_CON_CASH,
				:NEW.PAY_CON_BILL,
				:NEW.PAY_CON_BILL_DT,
				:NEW.PAY_CON_BILL_DAYS,
				:NEW.EMP_NO,
				:NEW.ANTICIPATION_DT,
				:NEW.MNG_ITEM_CHAR1,
				:NEW.MNG_ITEM_CHAR2,
				:NEW.MNG_ITEM_CHAR3,
				:NEW.MNG_ITEM_CHAR4,
				:NEW.MNG_ITEM_NUM1,
				:NEW.MNG_ITEM_NUM2,
				:NEW.MNG_ITEM_NUM3,
				:NEW.MNG_ITEM_NUM4,
				:NEW.MNG_ITEM_DT1,
				:NEW.MNG_ITEM_DT2,
				:NEW.MNG_ITEM_DT3,
				:NEW.MNG_ITEM_DT4,
				:NEW.FIX_ASSET_SEQ,
				ls_MakeCompanyCode
			);
			PKG_T_ACC_SLIP_BODY_INS.Ins_Child_Slip(
				:NEW.SLIP_ID,
				:NEW.SLIP_IDSEQ,
				:NEW.MAKE_SLIPLINE,
				:NEW.ACC_CODE,
				:NEW.DB_AMT,
				:NEW.CR_AMT,
				:NEW.SUMMARY_CODE,
				:NEW.TAX_COMP_CODE,
				:NEW.COMP_CODE,
				:NEW.DEPT_CODE,
				:NEW.CLASS_CODE,
				:NEW.VAT_CODE,
				:NEW.VAT_DT,
				:NEW.SUPAMT,
				:NEW.VATAMT,
				:NEW.CUST_SEQ,
				:NEW.CUST_NAME,
				:NEW.BANK_CODE,
				:NEW.ACCNO,
				:NEW.RESET_SLIP_ID,
				:NEW.RESET_SLIP_IDSEQ,
				:NEW.MAKE_COMP_CODE,
				:NEW.MAKE_DEPT_CODE,
				:NEW.MAKE_DT,
				:NEW.KEEP_DT,
				:NEW.ORG_SLIP_ID,
				:NEW.ORG_SLIP_IDSEQ,
				:NEW.BRAIN_GRP_SEQ,
				:NEW.BRAIN_SLIP_SEQ1,
				:NEW.BRAIN_SLIP_SEQ2,
				:NEW.BRAIN_SLIP_LINE,
				:NEW.BRAIN_SORT_SEQ,
				:NEW.BRAIN_ACC_POSITION,
				:NEW.SLIP_KIND_TAG,
				:NEW.TRANSFER_TAG,
				:NEW.IGNORE_SET_RESET_TAG,
				:NEW.CRTUSERNO,
				:NEW.CRTDATE,
				:NEW.MODUSERNO,
				:NEW.MODDATE,
				:NEW.SUMMARY1,
				:NEW.SUMMARY2,
				:NEW.CARD_SEQ,
				:NEW.CHK_NO,
				:NEW.BILL_NO,
				:NEW.REC_BILL_NO,
				:NEW.CP_NO,
				:NEW.SECU_NO,
				:NEW.LOAN_NO,
				:NEW.LOAN_REFUND_NO,
				:NEW.LOAN_REFUND_SEQ,
				:NEW.DEPOSIT_ACCNO,
				:NEW.PAYMENT_SEQ,
				:NEW.PAY_CON_CASH,
				:NEW.PAY_CON_BILL,
				:NEW.PAY_CON_BILL_DT,
				:NEW.PAY_CON_BILL_DAYS,
				:NEW.EMP_NO,
				:NEW.ANTICIPATION_DT,
				:NEW.MNG_ITEM_CHAR1,
				:NEW.MNG_ITEM_CHAR2,
				:NEW.MNG_ITEM_CHAR3,
				:NEW.MNG_ITEM_CHAR4,
				:NEW.MNG_ITEM_NUM1,
				:NEW.MNG_ITEM_NUM2,
				:NEW.MNG_ITEM_NUM3,
				:NEW.MNG_ITEM_NUM4,
				:NEW.MNG_ITEM_DT1,
				:NEW.MNG_ITEM_DT2,
				:NEW.MNG_ITEM_DT3,
				:NEW.MNG_ITEM_DT4,
				:NEW.FIX_ASSET_SEQ,
				ls_MakeCompanyCode
			);
		END IF;
	ELSIF UPDATING THEN
		--만약 자신이 지사 전표이면 삭제변경될 수 없습니다.
		IF PKG_T_ACC_SLIP_BODY_INS.Is_Child_Company_Slip(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ) THEN
			RAISE_APPLICATION_ERROR(-20009,'지사 전표는 삭제 또는 수정될 수 없습니다.');
		END IF;
		ls_MakeCompanyCode := PKG_T_ACC_SLIP_BODY_INS.Get_Parent_Company(:NEW.SLIP_ID);
		IF PKG_T_ACC_SLIP_BODY_INS.Is_Parent_Company_Slip(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ) THEN
		--기존 상태가 본사 전표라면
			IF ls_MakeCompanyCode = :NEW.COMP_CODE THEN
				--만약 신규 상태가 본사전표가 아니라면 지사 전표를 삭제하고 지사 전표 정보도 삭제합니다.
				PKG_T_ACC_SLIP_BODY_INS.Del_Child_Company_Slip(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ);
				PKG_T_ACC_SLIP_BODY_INS.Del_Child_Company_Slip_Info(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ);
			ELSE
				--만약 신규 상태도 역시 본사전표라면
				--귀속 사업장이 바뀌었는지를 먼저 알아봅니다.
				IF :NEW.COMP_CODE = :OLD.COMP_CODE THEN
					--만약 귀속 사업장이 바뀌었다면 지사 전표를 삭제 처리하고 삽입시와 동일한 처리를 합니다.
					PKG_T_ACC_SLIP_BODY_INS.Del_Child_Company_Slip(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ);
					PKG_T_ACC_SLIP_BODY_INS.Del_Child_Company_Slip_Info(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ);
					PKG_T_ACC_SLIP_BODY_INS.Ins_Child_Slip(
						:NEW.SLIP_ID,
						:NEW.SLIP_IDSEQ,
						:NEW.MAKE_SLIPLINE,
						:NEW.ACC_CODE,
						:NEW.DB_AMT,
						:NEW.CR_AMT,
						:NEW.SUMMARY_CODE,
						:NEW.TAX_COMP_CODE,
						:NEW.COMP_CODE,
						:NEW.DEPT_CODE,
						:NEW.CLASS_CODE,
						:NEW.VAT_CODE,
						:NEW.VAT_DT,
						:NEW.SUPAMT,
						:NEW.VATAMT,
						:NEW.CUST_SEQ,
						:NEW.CUST_NAME,
						:NEW.BANK_CODE,
						:NEW.ACCNO,
						:NEW.RESET_SLIP_ID,
						:NEW.RESET_SLIP_IDSEQ,
						:NEW.MAKE_COMP_CODE,
						:NEW.MAKE_DEPT_CODE,
						:NEW.MAKE_DT,
						:NEW.KEEP_DT,
						:NEW.ORG_SLIP_ID,
						:NEW.ORG_SLIP_IDSEQ,
						:NEW.BRAIN_GRP_SEQ,
						:NEW.BRAIN_SLIP_SEQ1,
						:NEW.BRAIN_SLIP_SEQ2,
						:NEW.BRAIN_SLIP_LINE,
						:NEW.BRAIN_SORT_SEQ,
						:NEW.BRAIN_ACC_POSITION,
						:NEW.SLIP_KIND_TAG,
						:NEW.TRANSFER_TAG,
						:NEW.IGNORE_SET_RESET_TAG,
						:NEW.CRTUSERNO,
						:NEW.CRTDATE,
						:NEW.MODUSERNO,
						:NEW.MODDATE,
						:NEW.SUMMARY1,
						:NEW.SUMMARY2,
						:NEW.CARD_SEQ,
						:NEW.CHK_NO,
						:NEW.BILL_NO,
						:NEW.REC_BILL_NO,
						:NEW.CP_NO,
						:NEW.SECU_NO,
						:NEW.LOAN_NO,
						:NEW.LOAN_REFUND_NO,
						:NEW.LOAN_REFUND_SEQ,
						:NEW.DEPOSIT_ACCNO,
						:NEW.PAYMENT_SEQ,
						:NEW.PAY_CON_CASH,
						:NEW.PAY_CON_BILL,
						:NEW.PAY_CON_BILL_DT,
						:NEW.PAY_CON_BILL_DAYS,
						:NEW.EMP_NO,
						:NEW.ANTICIPATION_DT,
						:NEW.MNG_ITEM_CHAR1,
						:NEW.MNG_ITEM_CHAR2,
						:NEW.MNG_ITEM_CHAR3,
						:NEW.MNG_ITEM_CHAR4,
						:NEW.MNG_ITEM_NUM1,
						:NEW.MNG_ITEM_NUM2,
						:NEW.MNG_ITEM_NUM3,
						:NEW.MNG_ITEM_NUM4,
						:NEW.MNG_ITEM_DT1,
						:NEW.MNG_ITEM_DT2,
						:NEW.MNG_ITEM_DT3,
						:NEW.MNG_ITEM_DT4,
						:NEW.FIX_ASSET_SEQ,
						ls_MakeCompanyCode
					);
				ELSE
					--만약 귀속사업장이 바뀌지 않았다면 관련 지사전표 두개를 갱신 처리 합니다.
					PKG_T_ACC_SLIP_BODY_INS.Upd_Child_Slip(
						:NEW.SLIP_ID,
						:NEW.SLIP_IDSEQ,
						:NEW.MAKE_SLIPLINE,
						:NEW.ACC_CODE,
						:NEW.DB_AMT,
						:NEW.CR_AMT,
						:NEW.SUMMARY_CODE,
						:NEW.TAX_COMP_CODE,
						:NEW.COMP_CODE,
						:NEW.DEPT_CODE,
						:NEW.CLASS_CODE,
						:NEW.VAT_CODE,
						:NEW.VAT_DT,
						:NEW.SUPAMT,
						:NEW.VATAMT,
						:NEW.CUST_SEQ,
						:NEW.CUST_NAME,
						:NEW.BANK_CODE,
						:NEW.ACCNO,
						:NEW.RESET_SLIP_ID,
						:NEW.RESET_SLIP_IDSEQ,
						:NEW.MAKE_COMP_CODE,
						:NEW.MAKE_DEPT_CODE,
						:NEW.MAKE_DT,
						:NEW.KEEP_DT,
						:NEW.ORG_SLIP_ID,
						:NEW.ORG_SLIP_IDSEQ,
						:NEW.BRAIN_GRP_SEQ,
						:NEW.BRAIN_SLIP_SEQ1,
						:NEW.BRAIN_SLIP_SEQ2,
						:NEW.BRAIN_SLIP_LINE,
						:NEW.BRAIN_SORT_SEQ,
						:NEW.BRAIN_ACC_POSITION,
						:NEW.SLIP_KIND_TAG,
						:NEW.TRANSFER_TAG,
						:NEW.IGNORE_SET_RESET_TAG,
						:NEW.CRTUSERNO,
						:NEW.CRTDATE,
						:NEW.MODUSERNO,
						:NEW.MODDATE,
						:NEW.SUMMARY1,
						:NEW.SUMMARY2,
						:NEW.CARD_SEQ,
						:NEW.CHK_NO,
						:NEW.BILL_NO,
						:NEW.REC_BILL_NO,
						:NEW.CP_NO,
						:NEW.SECU_NO,
						:NEW.LOAN_NO,
						:NEW.LOAN_REFUND_NO,
						:NEW.LOAN_REFUND_SEQ,
						:NEW.DEPOSIT_ACCNO,
						:NEW.PAYMENT_SEQ,
						:NEW.PAY_CON_CASH,
						:NEW.PAY_CON_BILL,
						:NEW.PAY_CON_BILL_DT,
						:NEW.PAY_CON_BILL_DAYS,
						:NEW.EMP_NO,
						:NEW.ANTICIPATION_DT,
						:NEW.MNG_ITEM_CHAR1,
						:NEW.MNG_ITEM_CHAR2,
						:NEW.MNG_ITEM_CHAR3,
						:NEW.MNG_ITEM_CHAR4,
						:NEW.MNG_ITEM_NUM1,
						:NEW.MNG_ITEM_NUM2,
						:NEW.MNG_ITEM_NUM3,
						:NEW.MNG_ITEM_NUM4,
						:NEW.MNG_ITEM_DT1,
						:NEW.MNG_ITEM_DT2,
						:NEW.MNG_ITEM_DT3,
						:NEW.MNG_ITEM_DT4,
						:NEW.FIX_ASSET_SEQ,
						ls_MakeCompanyCode
					);
				END IF;
			END IF;
		ELSE
			--기존 상태가 본사 전표가 아니라면
			IF ls_MakeCompanyCode = :NEW.COMP_CODE THEN
				--만약 신규 상태도 본사전표가 아니라면 단순히 Update 합니다.
				PKG_T_ACC_SLIP_BODY_INS.Upd_Slip(
					:NEW.SLIP_ID,
					:NEW.SLIP_IDSEQ,
					:NEW.MAKE_SLIPLINE,
					:NEW.ACC_CODE,
					:NEW.DB_AMT,
					:NEW.CR_AMT,
					:NEW.SUMMARY_CODE,
					:NEW.TAX_COMP_CODE,
					:NEW.COMP_CODE,
					:NEW.DEPT_CODE,
					:NEW.CLASS_CODE,
					:NEW.VAT_CODE,
					:NEW.VAT_DT,
					:NEW.SUPAMT,
					:NEW.VATAMT,
					:NEW.CUST_SEQ,
					:NEW.CUST_NAME,
					:NEW.BANK_CODE,
					:NEW.ACCNO,
					:NEW.RESET_SLIP_ID,
					:NEW.RESET_SLIP_IDSEQ,
					:NEW.MAKE_COMP_CODE,
					:NEW.MAKE_DEPT_CODE,
					:NEW.MAKE_DT,
					:NEW.KEEP_DT,
					:NEW.ORG_SLIP_ID,
					:NEW.ORG_SLIP_IDSEQ,
					:NEW.BRAIN_GRP_SEQ,
					:NEW.BRAIN_SLIP_SEQ1,
					:NEW.BRAIN_SLIP_SEQ2,
					:NEW.BRAIN_SLIP_LINE,
					:NEW.BRAIN_SORT_SEQ,
					:NEW.BRAIN_ACC_POSITION,
					:NEW.SLIP_KIND_TAG,
					:NEW.TRANSFER_TAG,
					:NEW.IGNORE_SET_RESET_TAG,
					:NEW.CRTUSERNO,
					:NEW.CRTDATE,
					:NEW.MODUSERNO,
					:NEW.MODDATE,
					:NEW.SUMMARY1,
					:NEW.SUMMARY2,
					:NEW.CARD_SEQ,
					:NEW.CHK_NO,
					:NEW.BILL_NO,
					:NEW.REC_BILL_NO,
					:NEW.CP_NO,
					:NEW.SECU_NO,
					:NEW.LOAN_NO,
					:NEW.LOAN_REFUND_NO,
					:NEW.LOAN_REFUND_SEQ,
					:NEW.DEPOSIT_ACCNO,
					:NEW.PAYMENT_SEQ,
					:NEW.PAY_CON_CASH,
					:NEW.PAY_CON_BILL,
					:NEW.PAY_CON_BILL_DT,
					:NEW.PAY_CON_BILL_DAYS,
					:NEW.EMP_NO,
					:NEW.ANTICIPATION_DT,
					:NEW.MNG_ITEM_CHAR1,
					:NEW.MNG_ITEM_CHAR2,
					:NEW.MNG_ITEM_CHAR3,
					:NEW.MNG_ITEM_CHAR4,
					:NEW.MNG_ITEM_NUM1,
					:NEW.MNG_ITEM_NUM2,
					:NEW.MNG_ITEM_NUM3,
					:NEW.MNG_ITEM_NUM4,
					:NEW.MNG_ITEM_DT1,
					:NEW.MNG_ITEM_DT2,
					:NEW.MNG_ITEM_DT3,
					:NEW.MNG_ITEM_DT4,
					:NEW.FIX_ASSET_SEQ
				);
			ELSE
				--만약 신규 상태는 본사전표라면 해당 전표를 본사 전표 형태로 갱신 후 삽입시와 동일한 처리를 합니다.
				PKG_T_ACC_SLIP_BODY_INS.Upd_Parent_Slip(
					:NEW.SLIP_ID,
					:NEW.SLIP_IDSEQ,
					:NEW.MAKE_SLIPLINE,
					:NEW.ACC_CODE,
					:NEW.DB_AMT,
					:NEW.CR_AMT,
					:NEW.SUMMARY_CODE,
					:NEW.TAX_COMP_CODE,
					:NEW.COMP_CODE,
					:NEW.DEPT_CODE,
					:NEW.CLASS_CODE,
					:NEW.VAT_CODE,
					:NEW.VAT_DT,
					:NEW.SUPAMT,
					:NEW.VATAMT,
					:NEW.CUST_SEQ,
					:NEW.CUST_NAME,
					:NEW.BANK_CODE,
					:NEW.ACCNO,
					:NEW.RESET_SLIP_ID,
					:NEW.RESET_SLIP_IDSEQ,
					:NEW.MAKE_COMP_CODE,
					:NEW.MAKE_DEPT_CODE,
					:NEW.MAKE_DT,
					:NEW.KEEP_DT,
					:NEW.ORG_SLIP_ID,
					:NEW.ORG_SLIP_IDSEQ,
					:NEW.BRAIN_GRP_SEQ,
					:NEW.BRAIN_SLIP_SEQ1,
					:NEW.BRAIN_SLIP_SEQ2,
					:NEW.BRAIN_SLIP_LINE,
					:NEW.BRAIN_SORT_SEQ,
					:NEW.BRAIN_ACC_POSITION,
					:NEW.SLIP_KIND_TAG,
					:NEW.TRANSFER_TAG,
					:NEW.IGNORE_SET_RESET_TAG,
					:NEW.CRTUSERNO,
					:NEW.CRTDATE,
					:NEW.MODUSERNO,
					:NEW.MODDATE,
					:NEW.SUMMARY1,
					:NEW.SUMMARY2,
					:NEW.CARD_SEQ,
					:NEW.CHK_NO,
					:NEW.BILL_NO,
					:NEW.REC_BILL_NO,
					:NEW.CP_NO,
					:NEW.SECU_NO,
					:NEW.LOAN_NO,
					:NEW.LOAN_REFUND_NO,
					:NEW.LOAN_REFUND_SEQ,
					:NEW.DEPOSIT_ACCNO,
					:NEW.PAYMENT_SEQ,
					:NEW.PAY_CON_CASH,
					:NEW.PAY_CON_BILL,
					:NEW.PAY_CON_BILL_DT,
					:NEW.PAY_CON_BILL_DAYS,
					:NEW.EMP_NO,
					:NEW.ANTICIPATION_DT,
					:NEW.MNG_ITEM_CHAR1,
					:NEW.MNG_ITEM_CHAR2,
					:NEW.MNG_ITEM_CHAR3,
					:NEW.MNG_ITEM_CHAR4,
					:NEW.MNG_ITEM_NUM1,
					:NEW.MNG_ITEM_NUM2,
					:NEW.MNG_ITEM_NUM3,
					:NEW.MNG_ITEM_NUM4,
					:NEW.MNG_ITEM_DT1,
					:NEW.MNG_ITEM_DT2,
					:NEW.MNG_ITEM_DT3,
					:NEW.MNG_ITEM_DT4,
					:NEW.FIX_ASSET_SEQ,
					ls_MakeCompanyCode
				);
				PKG_T_ACC_SLIP_BODY_INS.Ins_Child_Slip(
					:NEW.SLIP_ID,
					:NEW.SLIP_IDSEQ,
					:NEW.MAKE_SLIPLINE,
					:NEW.ACC_CODE,
					:NEW.DB_AMT,
					:NEW.CR_AMT,
					:NEW.SUMMARY_CODE,
					:NEW.TAX_COMP_CODE,
					:NEW.COMP_CODE,
					:NEW.DEPT_CODE,
					:NEW.CLASS_CODE,
					:NEW.VAT_CODE,
					:NEW.VAT_DT,
					:NEW.SUPAMT,
					:NEW.VATAMT,
					:NEW.CUST_SEQ,
					:NEW.CUST_NAME,
					:NEW.BANK_CODE,
					:NEW.ACCNO,
					:NEW.RESET_SLIP_ID,
					:NEW.RESET_SLIP_IDSEQ,
					:NEW.MAKE_COMP_CODE,
					:NEW.MAKE_DEPT_CODE,
					:NEW.MAKE_DT,
					:NEW.KEEP_DT,
					:NEW.ORG_SLIP_ID,
					:NEW.ORG_SLIP_IDSEQ,
					:NEW.BRAIN_GRP_SEQ,
					:NEW.BRAIN_SLIP_SEQ1,
					:NEW.BRAIN_SLIP_SEQ2,
					:NEW.BRAIN_SLIP_LINE,
					:NEW.BRAIN_SORT_SEQ,
					:NEW.BRAIN_ACC_POSITION,
					:NEW.SLIP_KIND_TAG,
					:NEW.TRANSFER_TAG,
					:NEW.IGNORE_SET_RESET_TAG,
					:NEW.CRTUSERNO,
					:NEW.CRTDATE,
					:NEW.MODUSERNO,
					:NEW.MODDATE,
					:NEW.SUMMARY1,
					:NEW.SUMMARY2,
					:NEW.CARD_SEQ,
					:NEW.CHK_NO,
					:NEW.BILL_NO,
					:NEW.REC_BILL_NO,
					:NEW.CP_NO,
					:NEW.SECU_NO,
					:NEW.LOAN_NO,
					:NEW.LOAN_REFUND_NO,
					:NEW.LOAN_REFUND_SEQ,
					:NEW.DEPOSIT_ACCNO,
					:NEW.PAYMENT_SEQ,
					:NEW.PAY_CON_CASH,
					:NEW.PAY_CON_BILL,
					:NEW.PAY_CON_BILL_DT,
					:NEW.PAY_CON_BILL_DAYS,
					:NEW.EMP_NO,
					:NEW.ANTICIPATION_DT,
					:NEW.MNG_ITEM_CHAR1,
					:NEW.MNG_ITEM_CHAR2,
					:NEW.MNG_ITEM_CHAR3,
					:NEW.MNG_ITEM_CHAR4,
					:NEW.MNG_ITEM_NUM1,
					:NEW.MNG_ITEM_NUM2,
					:NEW.MNG_ITEM_NUM3,
					:NEW.MNG_ITEM_NUM4,
					:NEW.MNG_ITEM_DT1,
					:NEW.MNG_ITEM_DT2,
					:NEW.MNG_ITEM_DT3,
					:NEW.MNG_ITEM_DT4,
					:NEW.FIX_ASSET_SEQ,
					ls_MakeCompanyCode
				);
			END IF;
		END IF;
	ELSE
		--만약 자신이 지사 전표이면 삭제변경될 수 없습니다.
		IF PKG_T_ACC_SLIP_BODY_INS.Is_Child_Company_Slip(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ) THEN
			RAISE_APPLICATION_ERROR(-20009,'지사 전표는 삭제 또는 수정될 수 없습니다.');
		END IF;
		IF PKG_T_ACC_SLIP_BODY_INS.Is_Parent_Company_Slip(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ) THEN
			--본지사 전표라면 먼저 지사 전표를 삭제한다.
			PKG_T_ACC_SLIP_BODY_INS.Del_Child_Company_Slip(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ);
		END IF;
		PKG_T_ACC_SLIP_BODY_INS.Del_Slip(:OLD.SLIP_ID,:OLD.SLIP_IDSEQ);
	END IF;
END;
/
