Create Or Replace View V_T_CODE_LIST
(
	CODE_GROUP_NO, 
	CODE_GROUP_ID, 
	CODE_GROUP_NAME, 
	CODE_LIST_ID, 
	CODE_LIST_NAME, 
	SEQ, 
	USE_TAG 
) 
As
Select	a.CODE_GROUP_NO,
		a.CODE_GROUP_ID,
		a.CODE_GROUP_NAME,
		b.CODE_LIST_ID,
		b.CODE_LIST_NAME,
		b.SEQ,
		b.USE_TAG
From 	T_CODE_GROUP a,
		T_CODE_LIST b
Where	a.CODE_GROUP_NO = b.CODE_GROUP_NO
/
