CREATE OR REPLACE TRIGGER "ERPW".trg_T_FIX_SHEET_01
After Insert on T_FIX_SHEET
--For Each row
Begin
	insert into t_fix_sheet_temp(FIX_ASSET_SEQ,CRTUSERNO,CRTDATE,MODUSERNO,MODDATE,ASSET_CLS_CODE,ITEM_CODE,
	ITEM_NM_CODE,FIX_ASSET_NO,ASSET_MNG_NO,COMP_CODE,GET_DT,ASSET_NAME,ASSET_SIZE,
	PRODUCTION,CUST_SEQ,USAGE,GET_CLS,DEPREC_CLS,SRVLIFE,ASSET_CNT,BASE_AMT,
	OLD_DEPREC_AMT,GET_COST_AMT,INC_SUM_AMT,SUB_SUM_AMT,NEW_OLD_ASSET,
	INCNTRY_OUTCNTRY_CLS,FIXED_CLS,FIXTURES_CLS,ETC_ASSET_TAG,DISPOSE_YEAR,DEPREC_FINISH,
	CAPITAL_OUT_AMT,GAIN_OUT_AMT,USE_REMARK,MNG_DEPT_CODE,DEPT_CODE,ITEM_NM_SEQ,
	CHG_GET_AMT,SALE_DT,SLIP_ID,SLIP_IDSEQ,WORK_SEQ,START_ASSET_AMT,CURR_ASSET_INC_AMT,
	CURR_ASSET_SUB_AMT,START_APPROP_AMT,
	CURR_APPROP_SUB_AMT,CURR_DEPREC_AMT,REMARK,VAT_AMT, CUST_SEQ2, 
	ESTIMATE_AMT1, ESTIMATE_AMT2, FOREIGN_AMT, MONEY_CLS)  select * from t_fix_sheet a
														 where not exists (select *
															   from t_fix_sheet_temp b
															   where a.fix_asset_seq = b.fix_asset_seq);  
End;
