CREATE OR REPLACE TRIGGER "ERPW".trg_Z_AUTHORITY_USER_bf_iu
BEFORE INSERT OR UPDATE ON Z_AUTHORITY_USER
FOR EACH ROW
BEGIN

	IF INSERTING THEN
		NULL;
	ELSIF UPDATING THEN
		IF :NEW.DEPT_CODE <> :OLD.DEPT_CODE THEN
		   Sp_T_Set_Emp_Auth_Dept_Trans(:NEW.EMPNO, :NEW.EMPNO, :NEW.COMPCODE, :NEW.DEPT_CODE);
		END IF;
	END IF;

	EXCEPTION
		WHEN OTHERS THEN
		-- Consider logging the error and then re-raise
		NULL;
	
END;