SELECT
  	A.COMP_CODE,  
  	A.TAX_COMP_CODE,  
  	A6.COMPANY_NAME TAX_COMP_NAME,  
  	C.RCPTBILL_CLS, 
	D.CODE_LIST_NAME RCPTBILL_CLS_NAME,
  	C.SALEBUY_CLS,  
	E.CODE_LIST_NAME SALEBUY_CLS_NAME,
  	A.PUBL_DT,  
  	A.VAT_CODE,  
  	A5.VAT_NAME,  
  	0 BOOK_NO,  
  	0 BOOK_SEQ,  
  	A.DEPT_CODE,  
  	A4.DEPT_NAME,  
  	A.CUST_SEQ,  
  	A3.CUST_CODE,  
  	A3.CUST_NAME,  
  	A.SUPAMT,  
  	A.VATAMT,  
  	NULL ANNULMENT_CLS,  
  	NULL ANNULMENT_DT,  
  	0 OUT_CNT,  
	A.MISSING_TAG, 
  	A.REMARK,  
  	A.UDT_TAG,  
  	A.SLIP_ID,  
  	A.SLIP_IDSEQ,  
  	A.MAKE_SLIPNOLINE,  
  	A.ACC_CODE,  
  	A2.ACC_NAME,
	C.SUBTR_CLS,
	C.VATOCCUR_CLS,
	C.SLIP_DETAIL_LIST,
	DECODE(F.CASHNO, NULL, G.CARDNO, F.CASHNO) CARD_CASH_NO
FROM
	(
		SELECT   
		  	A1.COMP_CODE,  
		  	A1.TAX_COMP_CODE,  
		  	F_T_DATETOSTRING(A1.VAT_DT) PUBL_DT,  
		  	A1.VAT_CODE,
		  	0 BOOK_NO,  
		  	0 BOOK_SEQ,  
		  	A1.DEPT_CODE,
		  	A1.CUST_SEQ,
		  	A1.SUPAMT,  
		  	A1.VATAMT,  
		  	NULL ANNULMENT_CLS,  
		  	NULL ANNULMENT_DT,  
		  	0 OUT_CNT,  
			CASE
				WHEN A1.VAT_DT < F_T_StringToDate(:BASE_DT_F0) THEN 'T'
				ELSE 'F'
			END MISSING_TAG, 
		  	'' REMARK,  
		  	'O' UDT_TAG,  
		  	A1.SLIP_ID,  
		  	A1.SLIP_IDSEQ,  
		  	A0.MAKE_SLIPNO||'-'||A1.MAKE_SLIPLINE MAKE_SLIPNOLINE,  
		  	A1.ACC_CODE
		  FROM   
		  	T_ACC_SLIP_HEAD A0,
		  	T_ACC_SLIP_BODY1 A1,
			(
				SELECT
					SLIP_ID,
					SLIP_IDSEQ
				FROM
					T_ACC_TAX_BILL_MEDIA
				WHERE
					COMP_CODE =   :COMP_CODE1
				  	AND WORK_NO = :WORK_NO
			) B
			WHERE
			A0.SLIP_ID = A1.SLIP_ID
			AND A1.SLIP_ID = B.SLIP_ID(+)  
			AND A1.SLIP_IDSEQ = B.SLIP_IDSEQ(+) 
			AND A1.KEEP_DT IS NOT NULL
			AND B.SLIP_ID IS NULL
			AND A1.COMP_CODE = :COMP_CODE2
			AND
			(
				A1.VAT_DT BETWEEN F_T_StringToDate(:MISSING_PROCESS_DT_F) AND F_T_StringToDate(:BASE_DT_F1)
				OR
				A1.VAT_DT BETWEEN F_T_StringToDate(:BASE_DT_F2) AND F_T_StringToDate(:BASE_DT_T)
			)
			AND a1.ACC_CODE LIKE '%'|| REPLACE(:SEARCH_CONDITION,' ','%') || '%'
	) A,
	T_ACC_CODE A2,
	T_CUST_CODE A3,
	T_DEPT_CODE A4,
	T_ACC_VAT_CODE A5,
	T_COMPANY A6,
	T_ACC_CODE_EXT01 C,
	(
		SELECT
			CODE_LIST_ID, CODE_LIST_NAME 
		FROM
			V_T_CODE_LIST
		WHERE
			CODE_GROUP_ID = 'RCPTBILL_CLS'
	) D,
	(
		SELECT
			CODE_LIST_ID, CODE_LIST_NAME 
		FROM
			V_T_CODE_LIST
		WHERE
			CODE_GROUP_ID = 'SALEBUY_CLS'
	) E,
	T_ACC_SLIP_EXPENSE_CASH F,
	T_ACC_SLIP_EXPENSE_CARDS G
WHERE
	A.ACC_CODE = A2.ACC_CODE
	AND A.CUST_SEQ = A3.CUST_SEQ(+)
	AND A.DEPT_CODE = A4.DEPT_CODE(+)
	AND A.VAT_CODE = A5.VAT_CODE(+)
	AND A.TAX_COMP_CODE = A6.COMP_CODE(+)
	AND A.ACC_CODE = C.ACC_CODE(+)
	--AND C.RCPTBILL_CLS IN ('01','02')
	AND C.RCPTBILL_CLS IS NOT NULL
	AND C.RCPTBILL_CLS = D.CODE_LIST_ID(+) 
	AND C.SALEBUY_CLS = E.CODE_LIST_ID(+)
	AND A.SLIP_ID = F.SLIP_ID(+) 
	AND A.SLIP_IDSEQ = F.SLIP_IDSEQ(+)
	AND A.SLIP_ID = G.SLIP_ID(+) 
	AND A.SLIP_IDSEQ = G.SLIP_IDSEQ(+)
ORDER BY
  	A.PUBL_DT
