Create Or Replace Procedure SP_T_FB_GET_MAIL_DATA
(
	Ar_Comp_Code						Varchar2,
	Ar_PAY_DUE_YMD						Varchar2,
	Ar_VAT_REGISTRATION_NUM				Varchar2,
	Ar_CRTUSERNO						Varchar2
)
Is
Begin
	--먼저 템프테이블에 집계를 한다...
	Insert Into T_FB_PAYDUE_MAIL_DETAIL_TMP
	(
		COMP_CODE,
		PAY_DUE_YMD,
		VAT_REGISTRATION_NUM,
		MAIL_SUB_SEQ,
		CASH_BILL_GUBUN,
		KEY_VALUE,
		PAY_AMT,
		BANK_CODE,
		IN_ACCOUNT_NO,
		CHECK_NO,
		FUTURE_PAY_DUE_YMD,
		CONSTRUCTION_SITE_CODE,
		CONTRUCTION_SITE_NAME,
		MAIL_SEQ
	)
	Select
		a.COMP_CODE,
		a.PAY_DUE_YMD,
		a.VAT_REGISTRATION_NUM,
		SQ_T_MAIL_SUB_SEQ.NextVal MAIL_SUB_SEQ,
		a.CASH_BILL_GUBUN,
		a.KEY_VALUE,
		a.PAY_AMT,
		a.BANK_CODE,
		a.IN_ACCOUNT_NO,
		a.CHECK_NO,
		a.FUTURE_PAY_DUE_YMD,
		a.CONSTRUCTION_SITE_CODE,
		a.CONTRUCTION_SITE_NAME,
		a.MAIL_SEQ
	From
		(
			Select
				a.COMP_CODE COMP_CODE,
				a.PAY_DUE_YMD PAY_DUE_YMD,
				b.CUST_CODE VAT_REGISTRATION_NUM,
				'C' CASH_BILL_GUBUN,
				To_Char(a.PAY_SEQ) KEY_VALUE,
				a.PAY_AMT PAY_AMT,
				a.IN_BANK_CODE BANK_CODE,
				a.IN_ACCOUNT_NO IN_ACCOUNT_NO,
				Null CHECK_NO,
				Null FUTURE_PAY_DUE_YMD,
				a.DEPT_CODE CONSTRUCTION_SITE_CODE,
				c.DEPT_NAME CONTRUCTION_SITE_NAME,
				Null MAIL_SEQ
			From	T_FB_CASH_PAY_DATA a,
					T_CUST_CODE b,
					T_DEPT_CODE_ORG c
			Where	a.CUST_SEQ = b.CUST_CODE
			And		a.DEPT_CODE = c.DEPT_CODE
			And		a.PAY_DUE_YMD = Ar_PAY_DUE_YMD
			And		a.COMP_CODE = Ar_Comp_Code
			And		b.CUST_CODE Like Ar_VAT_REGISTRATION_NUM || '%'
			And		a.PAY_KIND_GUBUN = 'SE'
			Union All
			Select
				a.COMP_CODE COMP_CODE,
				a.PAY_DUE_YMD PAY_DUE_YMD,
				b.CUST_CODE VAT_REGISTRATION_NUM,
				'B' CASH_BILL_GUBUN,
				To_Char(a.PAY_SEQ) KEY_VALUE,
				a.PAY_AMT PAY_AMT,
				Null BANK_CODE,
				Null IN_ACCOUNT_NO,
				a.CHECK_NO CHECK_NO,
				a.FUTURE_PAY_DUE_YMD FUTURE_PAY_DUE_YMD,
				a.DEPT_CODE CONSTRUCTION_SITE_CODE,
				c.DEPT_NAME CONTRUCTION_SITE_NAME,
				Null MAIL_SEQ
			From	T_FB_BILL_PAY_DATA a,
					T_CUST_CODE b,
					T_DEPT_CODE_ORG c
			Where	a.CUST_SEQ = b.CUST_CODE
			And		a.DEPT_CODE = c.DEPT_CODE
			And		a.PAY_DUE_YMD = Ar_PAY_DUE_YMD
			And		a.COMP_CODE = Ar_Comp_Code
			And		b.CUST_CODE Like Ar_VAT_REGISTRATION_NUM || '%'
			And		a.PAY_KIND_GUBUN = 'SE'
		) a;
	Insert Into T_FB_PAYDUE_MAIL_MASTER_TMP
	(
		COMP_CODE ,
		PAY_DUE_YMD ,
		VAT_REGISTRATION_NUM,
		MAIL_SEQ
	)
	Select
		a.COMP_CODE ,
		a.PAY_DUE_YMD ,
		a.VAT_REGISTRATION_NUM,
		SQ_T_MAIL_SEQ.NextVal
	From
		(
			Select
				a.COMP_CODE ,
				a.PAY_DUE_YMD ,
				a.VAT_REGISTRATION_NUM
			From	T_FB_PAYDUE_MAIL_DETAIL_TMP a
			Group By
				a.COMP_CODE ,
				a.PAY_DUE_YMD ,
				a.VAT_REGISTRATION_NUM
		) a;
	--기존값이 있으면 지운다....
	Delete	T_FB_PAYDUE_MAIL_DETAIL a
	Where	a.MAIL_SEQ In
	(
		Select
			b.MAIL_SEQ
		From	T_FB_PAYDUE_MAIL_MASTER b,
				T_FB_PAYDUE_MAIL_MASTER_TMP c
		Where	b.COMP_CODE = c.COMP_CODE
		And		b.PAY_DUE_YMD = c.PAY_DUE_YMD
		And		b.VAT_REGISTRATION_NUM = c.VAT_REGISTRATION_NUM
	);
	--이미 만들어놓은 자료가 있다면 메일번호를 엎어친다.
	Update	T_FB_PAYDUE_MAIL_MASTER_TMP a
	Set		a.MAIL_SEQ =
			(
				Select	b.MAIL_SEQ
				From	T_FB_PAYDUE_MAIL_MASTER b
				Where	b.COMP_CODE = a.COMP_CODE
				And		b.PAY_DUE_YMD = a.PAY_DUE_YMD
				And		b.VAT_REGISTRATION_NUM = a.VAT_REGISTRATION_NUM
			)
	Where	Exists
	(
		Select	b.MAIL_SEQ
		From	T_FB_PAYDUE_MAIL_MASTER b
		Where	b.COMP_CODE = a.COMP_CODE
		And		b.PAY_DUE_YMD = a.PAY_DUE_YMD
		And		b.VAT_REGISTRATION_NUM = a.VAT_REGISTRATION_NUM
	);
	--하위 템프에 MAIL_SEQ를 엎어친다.
	Update	T_FB_PAYDUE_MAIL_DETAIL_TMP a
	Set		a.MAIL_SEQ = (
				Select
					b.MAIL_SEQ
				From	T_FB_PAYDUE_MAIL_MASTER_TMP b
				Where	b.COMP_CODE = a.COMP_CODE
				And		b.PAY_DUE_YMD = a.PAY_DUE_YMD
				And		b.VAT_REGISTRATION_NUM = a.VAT_REGISTRATION_NUM
				);
	--마스터 머지
	Merge Into T_FB_PAYDUE_MAIL_MASTER t
	Using
	(
		Select
			a.MAIL_SEQ MAIL_SEQ,
			a.PAY_DUE_YMD PAY_DUE_YMD,
			a.VAT_REGISTRATION_NUM VAT_REGISTRATION_NUM,
			b.CUST_NAME VENDOR_NAME,
			Null MAIL_SEND_DATE,
			'N' MAIL_SEND_YN,
			'' MAIL_SEND_RESULT_MSG,
			'자료 재생성' MAIL_SEND_RESULT_MSG_NEW,
			a.COMP_CODE COMP_CODE,
			SysDate CREATION_DATE,
			Ar_CRTUSERNO CREATION_EMP_NO,
			SysDate LAST_MODIFY_DATE,
			Ar_CRTUSERNO LAST_MODIFY_EMP_NO,
			b.TR_MANAGER_NAME TR_MANAGER_NAME,
			b.TR_MANAGER_EMAIL TR_MANAGER_EMAIL
		From	T_FB_PAYDUE_MAIL_MASTER_TMP a,
				T_CUST_CODE b
		Where	a.VAT_REGISTRATION_NUM = b.CUST_CODE (+)
	) s
	On
	(
		s.MAIL_SEQ = t.MAIL_SEQ
	)
	When Matched Then
	Update
	Set
		t.MAIL_SEND_RESULT_MSG = s.MAIL_SEND_RESULT_MSG_NEW,
		t.LAST_MODIFY_DATE = s.LAST_MODIFY_DATE,
		t.LAST_MODIFY_EMP_NO = s.LAST_MODIFY_EMP_NO
	When Not Matched Then
	Insert
	(
		MAIL_SEQ,
		PAY_DUE_YMD,
		VAT_REGISTRATION_NUM,
		VENDOR_NAME,
		COMP_CODE,
		CREATION_DATE,
		CREATION_EMP_NO,
		TR_MANAGER_NAME,
		TR_MANAGER_EMAIL
	)
	Values
	(
		s.MAIL_SEQ,
		s.PAY_DUE_YMD,
		s.VAT_REGISTRATION_NUM,
		s.VENDOR_NAME,
		s.COMP_CODE,
		s.CREATION_DATE,
		s.CREATION_EMP_NO,
		s.TR_MANAGER_NAME,
		s.TR_MANAGER_EMAIL
	);
	--Detail Insert
	Insert Into T_FB_PAYDUE_MAIL_DETAIL
	(
		MAIL_SEQ,
		MAIL_SUB_SEQ,
		CASH_BILL_GUBUN,
		KEY_VALUE,
		PAY_AMT,
		BANK_CODE,
		IN_ACCOUNT_NO,
		CHECK_NO,
		FUTURE_PAY_DUE_YMD,
		CONSTRUCTION_SITE_CODE,
		CONTRUCTION_SITE_NAME
	)
	Select
		MAIL_SEQ,
		MAIL_SUB_SEQ,
		CASH_BILL_GUBUN,
		KEY_VALUE,
		PAY_AMT,
		BANK_CODE,
		IN_ACCOUNT_NO,
		CHECK_NO,
		FUTURE_PAY_DUE_YMD,
		CONSTRUCTION_SITE_CODE,
		CONTRUCTION_SITE_NAME
	From	T_FB_PAYDUE_MAIL_DETAIL_TMP;
End;
/
