CREATE OR REPLACE PROCEDURE Sp_T_Log_Acc_Slip_Head_I
(
	AR_SLIP_ID                                 NUMBER,
	AR_UPDATE_CLS                              VARCHAR2,
	AR_CRTUSERNO                               VARCHAR2 DEFAULT NULL
)
IS
	sqLOG_NO NUMBER;
BEGIN
	SELECT
		SQ_T_LOG_ID.NEXTVAL
	INTO sqLOG_NO
	FROM DUAL;

	--T_LOG_ACC_SLIP_HEAD
	INSERT INTO T_LOG_ACC_SLIP_HEAD
	SELECT
		sqLOG_NO LOG_NO,
		AR_UPDATE_CLS UPDATE_CLS,
		A.*,
		DECODE(AR_CRTUSERNO, NULL, DECODE(A.MODUSERNO, NULL, A.CRTUSERNO, A.MODUSERNO), AR_CRTUSERNO) LOG_CRTUSERNO,
		SYSDATE LOG_CRTDATE
	FROM
		T_ACC_SLIP_HEAD A
	WHERE
		A.SLIP_ID = AR_SLIP_ID;

	-- T_LOG_ACC_SLIP_BODY1
	INSERT INTO T_LOG_ACC_SLIP_BODY1
	SELECT
		sqLOG_NO LOG_NO,
		AR_UPDATE_CLS UPDATE_CLS,
		A.SLIP_ID,
		A.SLIP_IDSEQ,
		A.MAKE_SLIPLINE,
		A.ACC_CODE,
		A.DB_AMT,
		A.CR_AMT,
		A.SUMMARY_CODE,
		A.TAX_COMP_CODE,
		A.COMP_CODE,
		A.DEPT_CODE,
		A.CLASS_CODE,
		A.VAT_CODE,
		A.VAT_DT,
		A.SUPAMT,
		A.VATAMT,
		A.CUST_SEQ,
		A.CUST_NAME,
		A.BANK_CODE,
		A.ACCNO,
		A.RESET_SLIP_ID,
		A.RESET_SLIP_IDSEQ,
		A.MAKE_COMP_CODE,
		A.MAKE_DEPT_CODE,
		A.MAKE_DT,
		A.SLIP_KIND_TAG,
		A.TRANSFER_TAG,
		A.IGNORE_SET_RESET_TAG,
		A.KEEP_DT
		--A.ORG_SLIP_ID,
		--A.ORG_SLIP_IDSEQ,
	FROM
		T_ACC_SLIP_BODY1 A
	WHERE
		A.SLIP_ID = AR_SLIP_ID;

	--T_LOG_ACC_SLIP_BODY2
	INSERT INTO T_LOG_ACC_SLIP_BODY2(
		LOG_ID           ,
		UPDATE_CLS       ,
		SLIP_ID          ,
		SLIP_IDSEQ       ,
		CRTUSERNO        ,
		CRTDATE          ,
		MODUSERNO        ,
		MODDATE          ,
		SUMMARY1         ,
		SUMMARY2         ,
		CHK_NO           ,
		BILL_NO          ,
		REC_BILL_NO      ,
		CP_NO            ,
		SECU_NO          ,
		LOAN_NO          ,
		LOAN_REFUND_NO   ,
		LOAN_REFUND_SEQ  ,
		DEPOSIT_ACCNO    ,
		PAYMENT_SEQ      ,
		PAY_CON_CASH     ,
		PAY_CON_BILL     ,
		PAY_CON_BILL_DT  ,
		PAY_CON_BILL_DAYS,
		EMP_NO           ,
		ANTICIPATION_DT  ,
		MNG_ITEM_CHAR1   ,
		MNG_ITEM_CHAR2   ,
		MNG_ITEM_CHAR3   ,
		MNG_ITEM_CHAR4   ,
		MNG_ITEM_NUM1    ,
		MNG_ITEM_NUM2    ,
		MNG_ITEM_NUM3    ,
		MNG_ITEM_NUM4    ,
		MNG_ITEM_DT1     ,
		MNG_ITEM_DT2     ,
		MNG_ITEM_DT3     ,
		MNG_ITEM_DT4
	)
	SELECT
		sqLOG_NO LOG_NO,
		AR_UPDATE_CLS UPDATE_CLS,
		A.SLIP_ID          ,
		A.SLIP_IDSEQ       ,
		A.CRTUSERNO        ,
		A.CRTDATE          ,
		A.MODUSERNO        ,
		A.MODDATE          ,
		A.SUMMARY1         ,
		A.SUMMARY2         ,
		A.CHK_NO           ,
		A.BILL_NO          ,
		A.REC_BILL_NO      ,
		A.CP_NO            ,
		A.SECU_NO          ,
		A.LOAN_NO          ,
		A.LOAN_REFUND_NO   ,
		A.LOAN_REFUND_SEQ  ,
		A.DEPOSIT_ACCNO    ,
		A.PAYMENT_SEQ      ,
		A.PAY_CON_CASH     ,
		A.PAY_CON_BILL     ,
		A.PAY_CON_BILL_DT  ,
		A.PAY_CON_BILL_DAYS,
		A.EMP_NO           ,
		A.ANTICIPATION_DT  ,
		A.MNG_ITEM_CHAR1   ,
		A.MNG_ITEM_CHAR2   ,
		A.MNG_ITEM_CHAR3   ,
		A.MNG_ITEM_CHAR4   ,
		A.MNG_ITEM_NUM1    ,
		A.MNG_ITEM_NUM2    ,
		A.MNG_ITEM_NUM3    ,
		A.MNG_ITEM_NUM4    ,
		A.MNG_ITEM_DT1     ,
		A.MNG_ITEM_DT2     ,
		A.MNG_ITEM_DT3     ,
		A.MNG_ITEM_DT4
	FROM
		T_ACC_SLIP_BODY2 A
	WHERE
		A.SLIP_ID = AR_SLIP_ID;

	--T_LOG_ACC_SLIP_EXPENSE_CARDS
	INSERT INTO T_LOG_ACC_SLIP_EXPENSE_CARDS
	SELECT
		sqLOG_NO LOG_NO,
		AR_UPDATE_CLS UPDATE_CLS,
		A.*
	FROM
		T_ACC_SLIP_EXPENSE_CARDS A
	WHERE
		A.SLIP_ID = AR_SLIP_ID;

	--T_LOG_ACC_SLIP_EXPENSE_CASH
	INSERT INTO T_LOG_ACC_SLIP_EXPENSE_CASH
	SELECT
		sqLOG_NO LOG_NO,
		AR_UPDATE_CLS UPDATE_CLS,
		A.*
	FROM
		T_ACC_SLIP_EXPENSE_CASH A
	WHERE
		A.SLIP_ID = AR_SLIP_ID;

	--T_LOG_FIN_SECURTY
	INSERT INTO T_LOG_FIN_SECURTY
	SELECT
		sqLOG_NO LOG_NO,
		AR_UPDATE_CLS UPDATE_CLS,
		A.*
	FROM
		T_FIN_SECURTY A
	WHERE
		A.SECU_NO IN (
			SELECT
				SECU_NO
			FROM
				T_ACC_SLIP_BODY2 A
			WHERE
				A.SLIP_ID = AR_SLIP_ID
		);

	--T_LOG_FIN_CP_BUY
	INSERT INTO T_LOG_FIN_CP_BUY
	SELECT
		sqLOG_NO LOG_NO,
		AR_UPDATE_CLS UPDATE_CLS,
		A.*
	FROM
		T_FIN_CP_BUY A
	WHERE
		A.CP_NO IN (
			SELECT
				CP_NO
			FROM
				T_ACC_SLIP_BODY2 A
			WHERE
				A.SLIP_ID = AR_SLIP_ID
		);

	--T_LOG_FIN_RECEIVE_CHK_BILL
	INSERT INTO T_LOG_FIN_RECEIVE_CHK_BILL
	SELECT
		sqLOG_NO LOG_NO,
		AR_UPDATE_CLS UPDATE_CLS,
		A.*
	FROM
		T_FIN_RECEIVE_CHK_BILL A
	WHERE
		A.REC_CHK_BILL_NO IN (
			SELECT
				REC_CHK_BILL_NO
			FROM
				T_ACC_SLIP_BODY2 A
			WHERE
				A.SLIP_ID = AR_SLIP_ID
		);
END;
/



CREATE OR REPLACE Procedure SP_T_LOG_ACC_SLIP_HEAD_D
(
	AR_SLIP_ID                                 NUMBER
)
Is
Begin
	DELETE FROM T_LOG_FIN_RECEIVE_CHK_BILL 
	WHERE SLIP_ID = AR_SLIP_ID;
	
	DELETE FROM T_LOG_FIN_CP_BUY 
	WHERE SLIP_ID = AR_SLIP_ID;
	
	DELETE FROM T_LOG_FIN_SECURTY 
	WHERE SLIP_ID = AR_SLIP_ID;
	
	DELETE FROM T_LOG_ACC_SLIP_EXPENSE_CASH 
	WHERE SLIP_ID = AR_SLIP_ID;
	
	DELETE FROM T_LOG_ACC_SLIP_EXPENSE_CARDS 
	WHERE SLIP_ID = AR_SLIP_ID;
	
	DELETE FROM T_LOG_ACC_SLIP_BODY2 
	WHERE SLIP_ID = AR_SLIP_ID;
	
	DELETE FROM T_LOG_ACC_SLIP_BODY1 
	WHERE SLIP_ID = AR_SLIP_ID;
	
	DELETE FROM T_LOG_ACC_SLIP_HEAD 
	WHERE SLIP_ID = AR_SLIP_ID;
End;
/