Create Or Replace Procedure SP_T_PL_GET_FORE_CONS_INFO
(
	Ar_COMP_CODE				T_PL_COMP_DEPT_PLAN_EXEC.COMP_CODE%Type,
	Ar_CLSE_ACC_ID				T_PL_COMP_DEPT_PLAN_EXEC.CLSE_ACC_ID%Type,
	Ar_DEPT_CODE				T_PL_COMP_DEPT_PLAN_EXEC.DEPT_CODE%Type,
	Ar_QUARTER_YEAR				Number,
	Ar_CRTUSERNO				T_PL_COMP_DEPT_PLAN_EXEC.CRTUSERNO%Type
)
Is
Begin
	PKG_PL_DEPT_FORE.ProcessBatch(Ar_COMP_CODE,Ar_CLSE_ACC_ID,0,Ar_DEPT_CODE,Ar_QUARTER_YEAR,Ar_CRTUSERNO);
	SP_T_PL_PROJ_FORE_SUMUP(Ar_COMP_CODE,Ar_CLSE_ACC_ID,0,Ar_DEPT_CODE,Ar_QUARTER_YEAR);
End;
/
