Create Or Replace Procedure SP_T_FL_MONTH_COM_FORE_SUM
(
	Ar_COMP_CODE				Varchar2,
	Ar_CLSE_ACC_ID				Varchar2,
	Ar_QUARTER_YEAR				Number
)
Is
Begin
	SP_T_FL_MONTH_COM_FORE_SUMUP(Ar_COMP_CODE,Ar_CLSE_ACC_ID,Ar_QUARTER_YEAR);
	PKG_FL_COM_FORE.ProcessAutoRecal(Ar_COMP_CODE,Ar_CLSE_ACC_ID,Ar_QUARTER_YEAR,'0');
	SP_T_FL_MONTH_COM_FORE_SUMUP(Ar_COMP_CODE,Ar_CLSE_ACC_ID,Ar_QUARTER_YEAR);
End;
/
