Create Or Replace Procedure SP_T_BUDG_LAST_CONFIRM
(
	Ar_COMP_CODE					Varchar2,
	Ar_CLSE_ACC_ID					Varchar2,
	Ar_DEPT_CODE					Varchar2,
	Ar_CRTUSERNO					Varchar2
)
Is
	ln_CHG_SEQ						T_BUDG_DEPT_H.CHG_SEQ%Type;
Begin
	Delete	T_BUDG_MONTH_AMT
	Where	COMP_CODE = AR_COMP_CODE
	And		CLSE_ACC_ID = AR_CLSE_ACC_ID
	And		DEPT_CODE = AR_DEPT_CODE;

	Delete	T_BUDG_DEPT_ITEM
	Where	COMP_CODE = AR_COMP_CODE
	And		CLSE_ACC_ID = AR_CLSE_ACC_ID
	And		DEPT_CODE = AR_DEPT_CODE;
	
	Begin
		Select
			Max(CHG_SEQ)
		Into
			ln_CHG_SEQ
		From	T_BUDG_DEPT_H
		Where	COMP_CODE = AR_COMP_CODE
		And		CLSE_ACC_ID = AR_CLSE_ACC_ID
		And		DEPT_CODE = AR_DEPT_CODE
		And		CONFIRM_TAG = 'T';
	Exception When No_Data_Found Then
		ln_CHG_SEQ := Null;
	End;
	If ln_CHG_SEQ Is Null Then
		Update	T_BUDG_DEPT
		Set		LAST_CONFIRMED_SEQ = Null,
				MODUSERNO = Ar_CRTUSERNO,
				MODDATE = SysDate
		Where	COMP_CODE = AR_COMP_CODE
		And		CLSE_ACC_ID = AR_CLSE_ACC_ID
		And		DEPT_CODE = AR_DEPT_CODE;
		Return ;
	End If;
	Update	T_BUDG_DEPT
	Set		LAST_CONFIRMED_SEQ = ln_CHG_SEQ,
			MODUSERNO = Ar_CRTUSERNO,
			MODDATE = SysDate
	Where	COMP_CODE = AR_COMP_CODE
	And		CLSE_ACC_ID = AR_CLSE_ACC_ID
	And		DEPT_CODE = AR_DEPT_CODE;
	Insert Into T_BUDG_DEPT_ITEM
	(
		COMP_CODE,
		CLSE_ACC_ID,
		DEPT_CODE,
		BUDG_CODE_NO,
		RESERVED_SEQ,
		CRTUSERNO,
		CRTDATE,
		MODUSERNO,
		MODDATE,
		TARGET_DEPT_CODE,
		BUDG_ADD_AMT,
		BUDG_ITEM_REQ_AMT,
		BUDG_ITEM_ASSIGN_AMT
	)
	Select
		a.COMP_CODE COMP_CODE,
		a.CLSE_ACC_ID CLSE_ACC_ID,
		a.DEPT_CODE DEPT_CODE,
		a.BUDG_CODE_NO BUDG_CODE_NO,
		a.RESERVED_SEQ RESERVED_SEQ,
		Ar_CRTUSERNO CRTUSERNO,
		Sysdate CRTDATE,
		Null MODUSERNO,
		Null MODDATE,
		a.TARGET_DEPT_CODE TARGET_DEPT_CODE,
		a.BUDG_ADD_AMT BUDG_ADD_AMT,
		a.BUDG_ITEM_REQ_AMT BUDG_ITEM_REQ_AMT,
		a.BUDG_ITEM_ASSIGN_AMT BUDG_ITEM_ASSIGN_AMT
	From	T_BUDG_DEPT_ITEM_H a
	Where	a.COMP_CODE = Ar_COMP_CODE
	And		a.CLSE_ACC_ID = Ar_CLSE_ACC_ID
	And		a.DEPT_CODE = Ar_DEPT_CODE
	And		a.CHG_SEQ = ln_CHG_SEQ;
	Insert Into T_BUDG_MONTH_AMT
	(
		COMP_CODE,
		CLSE_ACC_ID,
		DEPT_CODE,
		BUDG_CODE_NO,
		RESERVED_SEQ,
		BUDG_YM,
		CRTUSERNO,
		CRTDATE,
		MODUSERNO,
		MODDATE,
		BUDG_MONTH_REQ_AMT,
		BUDG_MONTH_ASSIGN_AMT
	)
	Select
		COMP_CODE,
		CLSE_ACC_ID,
		DEPT_CODE,
		BUDG_CODE_NO,
		RESERVED_SEQ,
		BUDG_YM,
		CRTUSERNO,
		CRTDATE,
		MODUSERNO,
		MODDATE,
		BUDG_MONTH_REQ_AMT,
		BUDG_MONTH_ASSIGN_AMT
	From	T_BUDG_MONTH_AMT_H a
	Where	a.COMP_CODE = Ar_COMP_CODE
	And		a.CLSE_ACC_ID = Ar_CLSE_ACC_ID
	And		a.DEPT_CODE = Ar_DEPT_CODE
	And		a.CHG_SEQ = ln_CHG_SEQ;
End;
/
