Create Or Replace Procedure SP_T_PROCESS_REQUEST
(
	Ar_MENU_NO					T_PROGRAM_REQUEST.MENU_NO%Type,
	Ar_PROGRAM_NO				T_PROGRAM_REQUEST.PROGRAM_NO%Type,
	Ar_REQ_NO					T_PROGRAM_REQUEST.REQ_NO%Type,
	Ar_PROCESS_DT				Varchar2,
	Ar_PROCESS_TAG				T_PROGRAM_REQUEST.PROCESS_TAG%Type,
	Ar_CHANGE_PROGRAMMER		T_PROGRAM_STATUS.CHANGE_PROGRAMMER%Type
)
Is
Begin
	Update T_PROGRAM_REQUEST
	Set
		PROCESS_DT = F_T_STRINGTODATE(AR_PROCESS_DT),
		PROCESS_TAG = AR_PROCESS_TAG
	Where	MENU_NO = AR_MENU_NO
	And	PROGRAM_NO = AR_PROGRAM_NO
	And	REQ_NO = AR_REQ_NO;
	Update T_PROGRAM_STATUS
	Set
		CHANGE_PROGRAMMER = Ar_CHANGE_PROGRAMMER,
		CHANGE_DT = F_T_STRINGTODATE(AR_PROCESS_DT)
	Where	MENU_NO = AR_MENU_NO
	And		PROGRAM_NO = AR_PROGRAM_NO;
End;
/
