Create Or Replace Procedure SP_T_BUDG_ASSIGN_ALL
(
	Ar_COMP_CODE					Varchar2,
	Ar_CLSE_ACC_ID					Varchar2,
	Ar_DEPT_CODE					Varchar2,
	Ar_CHG_SEQ						Number,
	Ar_CRTUSERNO					Varchar2
)
Is
Begin
	SP_T_BUDG_CHECK_CONFIRM(AR_COMP_CODE,AR_CLSE_ACC_ID,AR_DEPT_CODE,AR_CHG_SEQ);
	Update	T_BUDG_MONTH_AMT_H
	Set		BUDG_MONTH_ASSIGN_AMT = BUDG_MONTH_REQ_AMT
	Where	COMP_CODE = Ar_COMP_CODE
	And		CLSE_ACC_ID = Ar_CLSE_ACC_ID
	And		DEPT_CODE = Ar_DEPT_CODE
	And		CHG_SEQ = Ar_CHG_SEQ;
	Update	T_BUDG_DEPT_ITEM_H
	Set		BUDG_ITEM_ASSIGN_AMT = BUDG_ITEM_REQ_AMT
	Where	COMP_CODE = Ar_COMP_CODE
	And		CLSE_ACC_ID = Ar_CLSE_ACC_ID
	And		DEPT_CODE = Ar_DEPT_CODE
	And		CHG_SEQ = Ar_CHG_SEQ;
End;
/
